### ISSUE TITLE
Add scanimagejs user to lp for Ubuntu install 

### ISSUE THREAD

**Issue by poikilos** [sbs20/scanservjs#102]
**Describe the bug**
Using either install method, the spinning wait symbol keeps spinning forever.

#### Docker install:
- Upon opening the web interface, it can't find any device, even though the following list the device:
```
scanimage -L
sane-find-scanner -q
```

#### Manual install:
Upon opening the web interface, a red popup briefly appears:
- `Command failed: /usr/bin/scanimage -d 'brother4:bus9;dev1' -A Output format is not set, using pnm as a default. scanimage: open of device brother4:bus9;dev1 failed: Invalid argument`
- upon refresh, there is no error, and the spinning wait symbol continues forever.

**To Reproduce**
1. Open http://localhost:8080

**Expected behavior**
Find the scanner, scan.

**Screenshots**

**Client (please complete the following information):**
 - Browser N/A

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 Focal Fossa
 - Node version 12.20.0
 - NPM version 6.14.8
 - Docker version N/A

This may be useful

**Additional context**
If I manually type `/usr/bin/scanimage -d 'brother4:bus9;dev1' -A` in a terminal, I get:
```
Output format is not set, using pnm as a default.
scanimage: rounded value of br-x from 215.9 to 215.88
scanimage: rounded value of br-y from 355.6 to 355.567

All options specific to device `brother4:bus9;dev1':
  Mode:
    --mode Black & White|Gray[Error Diffusion]|True Gray|24bit Color[Fast] [24bit Color[Fast]]
        Select the scan mode
    --resolution 100|150|200|300|400|600|1200|2400|4800|9600dpi [200]
        Sets the resolution of the scanned image.
    --source FlatBed|Automatic Document Feeder(left aligned)|Automatic Document Feeder(left aligned,Duplex)|Automatic Document Feeder(centrally aligned)|Automatic Document Feeder(centrally aligned,Duplex) [Automatic Document Feeder(left aligned)]
        Selects the scan source (such as a document-feeder).
    --brightness -50..50% (in steps of 1) [inactive]
        Controls the brightness of the acquired image.
    --contrast -50..50% (in steps of 1) [inactive]
        Controls the contrast of the acquired image.
  Geometry:
    -l 0..215.9mm (in steps of 0.0999908) [0]
        Top-left x position of scan area.
    -t 0..355.6mm (in steps of 0.0999908) [0]
        Top-left y position of scan area.
    -x 0..215.9mm (in steps of 0.0999908) [215.88]
        Width of scan-area.
    -y 0..355.6mm (in steps of 0.0999908) [355.567]
        Height of scan-area.
```

I can successfully scan using the terminal as follows:
```
SCAN_NAME="ScanImage_`date '+%Y-%m-%d_%H..%m..%S'`.png"
SCAN_PATH=~/$SCAN_NAME
/usr/bin/scanimage -d 'brother4:bus9;dev1' --source FlatBed --format=png --output-file $SCAN_PATH
```

**Comment by sbs20** [comment]
Thanks for sharing the scanimage output, that will be helpful. Can you run `docker logs scanservjs-container > log.txt` and upload it please?

**Comment by poikilos** [comment]
I installed docker only for this then uninstalled it because I don't know how to control it or change any config files in my container and I don't want the service to run as root. I'll see what log I can do later if possible.

**Comment by sbs20** [comment]
As an alternative, you could try [installing it manually](https://github.com/sbs20/scanservjs/blob/master/docs/install.md#tldr-debian-10). 

And there may be useful information in this [ask ubuntu post](https://askubuntu.com/a/447283)

Given that you can make it work from the command line it seems likely that this isn't a driver issue, but more likely a permissions one (which is mentioned in the post above).

Sorry not to be of more assistance. If you do happen to stumble across something - and I can make the installation work better, please do let me know.

**Comment by poikilos** [comment]
I installed it manually after removing the docker one, see original post.

**Comment by poikilos** [comment]
Ok, as per the link you suggested, I did `sudo usermod -a -G lp scanservjs` and that made the `scanservjs` user able to scan after logging in again with `sudo -u scanservjs bash`. After `sudo systemctl restart scanservjs`, the software now works--thanks!
