### ISSUE TITLE
Configurable delimiter instead of semicolon

### ISSUE THREAD

**Issue by felipefideli** [sbs20/scanservjs#105]
Hi! Is it possible to have an environment variable to change the separator of the split section from devices.js? Some local printers have a semicolon on the address (example: brother4:bus1;dev3) and the split ends up breaking in those cases, so, if I could change to a pipe "|", I guess it would fix the matter, like:

docker run -d -p 8080:8080 -e DEVICES="brother4:bus1;dev3" -e SCANIMAGE_LIST_IGNORE=true --name scanservjs --privileged sbs20/scanservjs:latest

Thank you for this excelent tool.

**Comment by sbs20** [comment]
If you're up for it, you can test this in the staging build. I need to document it but use the `DELIMITER` environment variable.
