### ISSUE TITLE
Support for manual ADF duplex mode

### ISSUE THREAD

**Issue by ubuergi** [sbs20/scanservjs#110]
Hi,

would it be possible to add manual duplex mode as batch option? I.e. to scan all pages from ADF, promt user to turn pages and feed back to ADF, scan again and merge to PDF.

**Comment by sbs20** [comment]
I like it. I might be a bit slow getting round to it.

**Comment by sbs20** [comment]
Just to clarify, presumably this would mean scanning pages 1, 3, 5 then 2, 4, 6 - correct?

**Comment by ubuergi** [comment]
Yes, exactl. It would scan 1,3,5,... until ADF is emtpy, then scan 2,4,6...
I actually wanted to post some sample code since I implemented this last year for the sane cli. But I can't find it anymore.  :-\

**Comment by sbs20** [comment]
No worries, that's cool. Thanks!

**Comment by ubuergi** [comment]
Thanks for working on this. Something is not quite right though:
When I add two double-sided pages to the ADF and select _source: ADF_, _batch: Manual (with promt)_, it scans the first page, then a prompt appears asking "Scan page 2?", when I click OK, I get the following error message:

`/usr/bin/scanimage -d 'airscan:w0:Canon TR7500' --mode 'Color' --source 'ADF' --resolution 300 -l 5 -t 3 -x 210 -y 290 --format 'tiff' --brightness 0 --contrast 0 > ./data/temp/~tmp-scan-0002.tif exited with code: 3, stderr: scanimage: sane_start: Device busy`

I think when scanning from ADF, my Canon expects this to be a job that runs until all pages have been scanned. Scanning individually from ADF is probably not supported. Might this be the reason?

**Comment by sbs20** [comment]
Try source `ADF` and batch `Auto (Duplex 1, 3... 2, 4)`

What should happen is that it run two multi-page ADF scans. The first should be the odd pages. It should then prompt you to turn the pages, and set it off to do a second scan.

If you're doing a manual batch, try setting the source to `Flatbed` or similar.
