### ISSUE TITLE
FeatureRequest : Batch Duplex Reverse

### ISSUE THREAD

**Issue by toxic0berliner** [sbs20/scanservjs#125]
Either I'm entirely an idiot for not understanding how the batch duplex should work, Or it's not really helpful for me.

My scanner has an automatic document feeder that works only for one side of the page, and not the other one.
So when I want to create a single pdf of all pages in the proper order, with the current Duplex, I have to reverse the order of all the pages before turning them to scan their backside, and after I'm done, I still need to reverse all the pages once again...

In fact, when I feed the pages, it will scan in the following order : 1,3,5,6,4,2. And of cource I'd like the tool to rearrange them in the proper order...
It seems right now it expects the pages to be scanned 1,3,5,2,4,6 but I cannot achieve that without shuffeling everything...

**Comment by sbs20** [comment]
Ah ok. Interesting. Let me have a think and I'll try and get something sorted.

**Comment by sbs20** [comment]
Yeah, this was all wrong. Thanks for spotting it. There are two options for collation - you want the standard one.
