### ISSUE TITLE
[Feature] button to store scan settings as default

### ISSUE THREAD

**Issue by Andrwe** [sbs20/scanservjs#132]
Hi,

currently scanservjs creates `config/devices.json` when it's missing based on the scan settings return by the scanner.
The only way to overwrite the default scan settings is either by changing the settings on every scan or the administrator modifies the config on filesystem.

It would be nice to have a button that stores the current scan settings into the devices config for the given scanner.

Regards,
Andrwe

**Comment by sbs20** [comment]
Do you mean the settings you've chosen in the UI? If so, these are stored in LocalStorage. Each time I use it, it retains the settings from my last session - provided I'm using the same browser. Does this not work for you? What browser are you using? Are you using private browsing / incognito?

**Comment by Andrwe** [comment]
Yes I mean those settings.
I'm using scanservjs to give my 3 children the possibility to scan their homework as they need to.
Therefore several different clients and browsers are used.
To simplify the usage across those I already changed the default values for the scanner in the file `config/devices.json`.
That's why all browser use the same default settings and noone has to change the settings manually.

IMHO it would be a nice addition to the project to allow storing senseful defaults on server-side.
I can try to create a PR for that.

**Comment by sbs20** [comment]
Interesting. The thing that complicates this is that each device is different. Could you enumerate all the defaults / settings you've changed? I'll have a think.

**Comment by Andrwe** [comment]
The diff looks like this:
```
--- devices.json        2021-02-22 08:41:49.685386896 +0100
+++ devices.json_mod    2021-02-17 19:46:41.894157269 +0100
@@ -4,7 +4,7 @@
     "version": "2.6.0",
     "features": {
       "--mode": {
-        "default": "Lineart",
+        "default": "Color",
         "parameters": "Lineart|Gray|Color",
         "options": [
           "Lineart",
@@ -13,7 +13,7 @@
         ]
       },
       "--resolution": {
-        "default": 75,
+        "default": 200,
         "parameters": "75|100|200|300|600|1200dpi",
         "options": [
           75,
@@ -32,7 +32,7 @@
         ]
       },
       "--brightness": {
-        "default": 1000,
+        "default": 1500,
         "parameters": "0..2000",
         "limits": [
           0,
@@ -91,4 +91,4 @@
       }
     }
   }
-]
\ Kein Zeilenumbruch am Dateiende.
+]
```

It changes the following keys for `Deskjet_2050_J510_series`:
* `features.default`
* `--resolution.default`
* `--brightness.default`

**Comment by Andrwe** [comment]
For the loading implementation I'd go for something like this:
1. load scanner defaults detected and stored in `config/devices.json`
2. load option overwrite from `config/devices.local.json`

For the storing implementation:
1. configure settings as needed in web-UI
2. press 'store as default'-button
3. send settings to API
4. API writes settings that defer from `config/devices.json` into `config/devices.local.json`

What do you think about this approach?

**Comment by sbs20** [comment]
See #137
