### ISSUE TITLE
ScanDevice overrides

### ISSUE THREAD

**Issue by sbs20** [sbs20/scanservjs#137]
## Problem
Scanners have bad default values. Sometimes they're just bad. Sometimes they're just not quite what users want.

## Current situation
The web app already stores the user's settings in `LocalStorage` which will meet the most common use case. Nonetheless, if you need to perform a reset then those settings are lost. Furthermore, if there are a number of users then this feature is irrelevant.

## Complicating matters
* `devices.json` stores the real values from the scanners
* `LocalStorage` stores the user's values
* There can be more than one `ScanDevice`

## Options
1. Allow the user to persist defaults back to the server
   * To do this properly this needs to respect the current scanner (there can be more than one)
   * It should also, ideally, be done in the settings section, rather than the primary scan UI - which itself brings usability tradeoffs
   * Should it overwrite all settings or just some?
   * It allows for settings wars between users
   * Where to store? If it's not `devices.json` (which I think it should not be) then that's a **third** place to store settings.
   * It's a fair amount of effort, and additional code to maintain, for a relatively rare use-case
2. Add a ScanDevices override, just as there is a Config override
   * This is controlled by the admin
   * It can provide exact overrides
   * It impacts the code minimally since it's just an extension to the existing mechanisms
   * It easily handles specific devices
   * It requires a bit of coding (less good)

## Decision
Option 2

**Comment by sbs20** [comment]
See commit: https://github.com/sbs20/scanservjs/commit/4d39afb178b23b694d2d71ba773261bdf499b101

**Comment by Andrwe** [comment]
If I understand the commit correctly the intention is to allow defining an option `afterDevices` in `config/config.local.js` which must be a function.
IMHO this approach is very hard for the administrators of the system unless they are able to write nodejs code.
It already was hard for me to understand how to change the default filename as this option must be a function, too.
And for the scanner configuration it will be much harder to develop a nodejs function that will change the defaults based on the device.

To reduce the developer skills required to just change the default settings the PR should at least provide a descriptive sample definition in the config file.

**Comment by sbs20** [comment]
It's part of a wider set of commits. There is no PR yet - it's still in development.

Example code here:

https://github.com/sbs20/scanservjs/blob/498baa7fe297e868614170e2e25303adfee9cfea/server/config/config.default.js#L98

**Comment by Andrwe** [comment]
Oh, right I opened a commit of yours, sorry for the confusion.
That one look promising. :)
