### ISSUE TITLE
Enhancement : container-ready installer

### ISSUE THREAD

**Issue by toxic0berliner** [sbs20/scanservjs#15]
Your installer script is very nice and does work even for me inside a docker container.

But it still complains that the container hass no init.d subsystem, it tries to start the service after installing it...
If I get around to it I'll probably make a PR to add an optional argument to have the installer "container-friendly" or at least "silent install".

**Comment by sbs20** [comment]
I think this is probably resolved in v1.0.2. Happy for this to be re-opened if not.
