### ISSUE TITLE
Add internationalisation

### ISSUE THREAD

**Issue by txapelgorri** [sbs20/scanservjs#151]
Would be great to be able to translate to other languages :)

**Comment by sbs20** [comment]
I love this idea. It's been on my mind a while!

**Comment by txapelgorri** [comment]
I can deal with 2 languages: spanish and basque. Is there anything I can help with in order to set the system ready for I18n? :)

**Comment by sbs20** [comment]
Awesome. Not quite yet, I need to lay some foundations. But I'll update this issue when I'm done.

**Comment by sbs20** [comment]
Ok. I haven't figured out the best way to translate pipelines yet, but the dev branch now has basic translations. Here's the [english translation file](https://github.com/sbs20/scanservjs/blob/6548c94466f223504de858de840f939813ed8561/webui/src/locales/en.json#L1). If you are happy to provide translations then that would be brilliant. If you do a PR then please target the development branch.

**Comment by sbs20** [comment]
See #154
