### ISSUE TITLE
Scanner not detected by scanservjs

### ISSUE THREAD

**Issue by ferbulous** [sbs20/scanservjs#168]
Hi, I'm running scanservjs (manual install) on armbian (orange pi zero).
I already have sane setup, and I'm able to scan using sanewin (windows) and sanedroid (Android)

But scanservjs is still not picking up my scanner.

![Screenshot_2021-04-03-19-52-21-405_com android chrome](https://user-images.githubusercontent.com/24526737/113477693-3b03de00-94b6-11eb-875e-ebf5d083d575.jpg)

I have also tried installing docker (from another github that supports arm) but i had a similar issue there

![IMG_20210403_195809_846](https://user-images.githubusercontent.com/24526737/113477783-ee6cd280-94b6-11eb-92b8-23b67708142e.jpg)

I haven't add udev rule for the scanner, is that a requirement?

May I how to generate logs for this issue?

**Comment by sbs20** [comment]
> I haven't add udev rule for the scanner, is that a requirement?

Not definitely, but very probably.

You're more likely to get it working (at least it's easier to debug) without Docker. There are some useful steps [here](https://github.com/sbs20/scanservjs/blob/master/docs/sane.md#validate-sane-is-working)

I'd suggest running a few steps manually at the command line to start with.

Try:

```sh
# Run as default user - this may or may not work
scanimage -L

# Run as root - this really should work
sudo scanimage -L

# Switch to the scanservjs user
sudo su scanservjs

# This is likely not to work (since it's not working above)
scanimage -L
```

If the last command doesn't work, then I expect it's a udev rule.

You will need to `lsusb` - you should see something like this (but for your HP)

```
Bus 001 Device 003: ID 04a9:220d Canon, Inc. CanoScan N670U/N676U/LiDE 20
```

You can then use `04a9` and `220d` to put in the udev rule. I seem to recall (but can't be sure) you need to reboot.

**Comment by ferbulous** [comment]
> > I haven't add udev rule for the scanner, is that a requirement?
> 
> Not definitely, but very probably.
> 
> You're more likely to get it working (at least it's easier to debug) without Docker. There are some useful steps [here](https://github.com/sbs20/scanservjs/blob/master/docs/sane.md#validate-sane-is-working)
> 
> I'd suggest running a few steps manually at the command line to start with.
> 
> Try:
> 
> ```shell
> # Run as default user - this may or may not work
> scanimage -L
> 
> # Run as root - this really should work
> sudo scanimage -L
> 
> # Switch to the scanservjs user
> sudo su scanservjs
> 
> # This is likely not to work (since it's not working above)
> scanimage -L
> ```
> 
> If the last command doesn't work, then I expect it's a udev rule.
> 
> You will need to `lsusb` - you should see something like this (but for your HP)
> 
> ```
> Bus 001 Device 003: ID 04a9:220d Canon, Inc. CanoScan N670U/N676U/LiDE 20
> ```
> 
> You can then use `04a9` and `220d` to put in the udev rule. I seem to recall (but can't be sure) you need to reboot.

I have done those and seems to work fine

![Screenshot_2021-04-03-20-24-05-884_com sonelli juicessh](https://user-images.githubusercontent.com/24526737/113478293-a059ce00-94ba-11eb-8ba4-a44d3d8eba41.jpg)

I have also added to udev rule 

`ATTRS{idVendor}=="03f0", ATTRS{idProduct}=="c111", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes"
`

But it looks scanservjs is still not detecting my scanner.

I'm no longer running on docker, using manual install as mentioned on my post. I posted the one from the docker since it's the only way i could get logs

**Comment by sbs20** [comment]
It doesn't look as though you've run `scanimage -L` after switching user.

```
# Switch to the scanservjs user
sudo su scanservjs

# Run scanimage as the scanservjs user
scanimage -L
```

Also worth checking that the `scanservjs` user is a member of the `scanner` group...

```
groups scanservjs
```

**Comment by sbs20** [comment]
You can get the logs by running `journalctl -xe` - you may need to sudo

**Comment by ferbulous** [comment]
Hi, for scanservjs group

**Comment by ferbulous** [comment]
Hi, so it looks like scanservjs is already in scanner group but it still
can't detect scanner

However when I'm logged in as root I can detect the scannet with scan -L
command

**Comment by sbs20** [comment]
So, the short version is: the problem is that the `scanservjs` user (which is what the app runs as) does not have permissions to access the scanner. Usually this happens via the `scanner`group and udev rules. I haven't specifically tested with Armbian - but I'd have thought it should work. Perhaps you can share the udev rule you created, ensure you've rebooted and maybe try again.

**Comment by ferbulous** [comment]
Hi, I placed it here

/etc/udev/rules.d/55-libsane.rules

for the udev rules

ATTRS{idVendor}=="03f0", ATTRS{idProduct}=="c111", MODE="0666",
GROUP="scanner", ENV{libsane_matched}="yes"

**Comment by sbs20** [comment]
It all looks ok, I'm not sure what I else I can suggest. I've had a bit of a search around such as [this](https://feeding.cloud.geek.nz/posts/setting-up-a-network-scanner-using-sane/), [this](https://wiki.debian.org/Scanner) and [this](https://wiki.archlinux.org/index.php/udev) and it all looks similar.

You could try running scanservjs as your standard user or even root (change the user in `/etc/systemd/system/scanservjs.service`) - but that's not ideal. The problem isn't specifically with scanserv but with the underlying linux permissions.

If you do find the answer, it would be great if you can share here in case I can improve the documentation.

**Comment by ferbulous** [comment]
Thanks, indeed it's linux permissions issue
I've changed the user to root, and it's working now, not the best solution
but I guess that'll do for armbian

**Comment by ferbulous** [comment]
I think i hit another snag
I can select preview for the scan preview, but I'm getting this error when
I select scan

[image: image.png]

**Comment by sbs20** [comment]
You need to file this on GitHub rather than via email as the image doesn't show up.

**Comment by ferbulous** [comment]
> You need to file this on GitHub rather than via email as the image doesn't show up.

Sorry here's the error when I select scan

![image](https://user-images.githubusercontent.com/24526737/113489229-9a351300-94f5-11eb-8cd2-b17ba4b7a23b.png)

{"message":no matching pipeline","code":-1

**Comment by sbs20** [comment]
Ah yes, that's this https://github.com/sbs20/scanservjs/issues/167

There's a fix on its way. For now, just select a format and it will sort it out.

**Comment by ferbulous** [comment]
Thanks! Looking forward to it
