### ISSUE TITLE
Failed to restart the service (node 8 / file exists)

### ISSUE THREAD

**Issue by xxjkzs** [sbs20/scanservjs#172]
Every time I reboot the host or just try to restart the scanservjs.service , it will stop working. To fix this , I have to manually remove the ./data/output/ and ./data/temp/ directories.

I have the latest build v2.8.3 manually installed on a Ubuntu 18.04.5 LTS . 

The journalctl -xe shows as bellow:
> -- Unit scanservjs.service has finished starting up.
> --
> -- The start-up result is RESULT.
> Apr 07 14:50:09 daeserv sudo[2306]: pam_unix(sudo:session): session closed for user root
> Apr 07 14:50:10 daeserv server.js[2309]: fs.js:885
> Apr 07 14:50:10 daeserv server.js[2309]:   return binding.mkdir(pathModule._makeLong(path),
> Apr 07 14:50:10 daeserv server.js[2309]:                  ^
> Apr 07 14:50:10 daeserv server.js[2309]: Error: EEXIST: file already exists, mkdir './data/output/'
> Apr 07 14:50:10 daeserv server.js[2309]:     at Object.fs.mkdirSync (fs.js:885:18)
> Apr 07 14:50:10 daeserv server.js[2309]:     at initialize (/var/www/scanservjs/server/configure.js:57:6)
> Apr 07 14:50:10 daeserv server.js[2309]:     at module.exports (/var/www/scanservjs/server/configure.js:62:3)
> Apr 07 14:50:10 daeserv server.js[2309]:     at Object.<anonymous> (/var/www/scanservjs/server/server.js:11:1)
> Apr 07 14:50:10 daeserv server.js[2309]:     at Module._compile (module.js:653:30)
> Apr 07 14:50:10 daeserv server.js[2309]:     at Object.Module._extensions..js (module.js:664:10)
> Apr 07 14:50:10 daeserv server.js[2309]:     at Module.load (module.js:566:32)
> Apr 07 14:50:10 daeserv server.js[2309]:     at tryModuleLoad (module.js:506:12)
> Apr 07 14:50:10 daeserv server.js[2309]:     at Function.Module._load (module.js:498:3)
> Apr 07 14:50:10 daeserv server.js[2309]:     at Function.Module.runMain (module.js:694:10)
> Apr 07 14:50:10 daeserv systemd[1]: scanservjs.service: Main process exited, code=exited, status=1/FAILURE
> Apr 07 14:50:10 daeserv systemd[1]: scanservjs.service: Failed with result 'exit-code'.
> Apr 07 14:55:02 daeserv CRON[2373]: pam_unix(cron:session): session opened for user root by (uid=0)
> Apr 07 14:55:02 daeserv CRON[2374]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
> Apr 07 14:55:02 daeserv CRON[2373]: pam_unix(cron:session): session closed for user root

**Comment by sbs20** [comment]
That's annoying - nodejs should not throw an error when `recursive` is set to true and the directory exists.

Which version of node are you using? `nodejs -v`

**Comment by sbs20** [comment]
I just added a quick check with a try catch. I am fairly certain this is due to node8 - the error fits and Ubuntu 18 comes with node8 by default. I thought about a fuller fix, but even node 10 is going out of LTS soon so I thought this might be enough for now. Do let me know if this isn't enough though!

**Comment by xxjkzs** [comment]
Thanks for this quick fix. It works with node8 now. I would call this good enough.

> Apr 07 23:12:36 daeserv systemd[1]: Stopping scanservjs...
>  Unit scanservjs.service has begun shutting down.
> Apr 07 23:12:36 daeserv systemd[1]: Stopped scanservjs.
> Unit scanservjs.service has finished shutting down.
> Apr 07 23:12:36 daeserv systemd[1]: Started scanservjs.
> Unit scanservjs.service has finished starting up.
>  The start-up result is RESULT.
> Apr 07 23:12:36 daeserv sudo[1747]: pam_unix(sudo:session): session closed for user root
> **Apr 07 23:12:36 daeserv server.js[1751]: [2021-04-07T15:12:36.887Z] WARN (Http): Error ensuring output and temp directories exist: Error: EEXIST: file already exists, mkdir './data/output/'
> Apr 07 23:12:36 daeserv server.js[1751]: [2021-04-07T15:12:36.896Z] WARN (Http): Currently running node version v8.17.0.
> Apr 07 23:12:36 daeserv server.js[1751]: [2021-04-07T15:12:36.914Z] INFO (server): Started**

**Comment by xxjkzs** [comment]
Thanks for this quick fix. It works with node8 now. I would call this good enough.

> Apr 07 23:12:36 daeserv systemd[1]: Stopping scanservjs...
>  Unit scanservjs.service has begun shutting down.
> Apr 07 23:12:36 daeserv systemd[1]: Stopped scanservjs.
> Unit scanservjs.service has finished shutting down.
> Apr 07 23:12:36 daeserv systemd[1]: Started scanservjs.
> Unit scanservjs.service has finished starting up.
>  The start-up result is RESULT.
> Apr 07 23:12:36 daeserv sudo[1747]: pam_unix(sudo:session): session closed for user root
> **Apr 07 23:12:36 daeserv server.js[1751]: [2021-04-07T15:12:36.887Z] WARN (Http): Error ensuring output and temp directories exist: Error: EEXIST: file already exists, mkdir './data/output/'
> Apr 07 23:12:36 daeserv server.js[1751]: [2021-04-07T15:12:36.896Z] WARN (Http): Currently running node version v8.17.0.
> Apr 07 23:12:36 daeserv server.js[1751]: [2021-04-07T15:12:36.914Z] INFO (server): Started**
