### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#179]
Hi,

You can find bellow the file fr.json translated in french.

If there is a problem in the file, don't hesitate to contact me.

[fr.json.zip](https://github.com/sbs20/scanservjs/files/6290940/fr.json.zip)

**Comment by sbs20** [comment]
Thank you!!!

**Comment by GG700** [comment]
Hi,

I made an upgrade of the french traduction.
Can you use this new file ?
[fr.json.zip](https://github.com/sbs20/scanservjs/files/6409642/fr.json.zip)

**Comment by sbs20** [comment]
Yes. Thanks for this! There's more coming soon - but may be best to wait until the next release for that.
