### ISSUE TITLE
Help to configurate config.local.js

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#181]
Hi,

scanservjs can't start when I use a local config.

Can you help me ? What is the problem In the file ?
In the folder /config, I have 2 files :

- config.local.js
- config.default.js
[config.local.js.zip](https://github.com/sbs20/scanservjs/files/6291378/config.local.js.zip)

**Comment by sbs20** [comment]
I can only look on my phone right now. My guess is the string on line 25 isn't terminated. You'll get better information looking at the logs using journalctl.

**Comment by sbs20** [comment]
Ok, had a chance to look more closely. There are a few things up with it. I can't be sure, but I suspect you want something like this:

```javascript
module.exports = {
  /**
   * @param {Configuration} config 
   */
  afterConfig(config) {
    config.ocrLanguage = 'fra';
    config.previewResolution = 300;

    // Add a custom print pipeline
    config.pipelines.push({
      extension: 'pdf',
      description: 'IMPRESSION & PDF',
      commands: [
        'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg',
        'convert @- scan-0000.pdf',
        'lp -d Lexmark_Optra_E312 scan-0000.pdf',
        'ls scan-*.*'
        ]
      });
  },

  /**
   * @param {ScanDevice[]} devices 
   */
  afterDevices(devices) {
  }
};

```

**Comment by GG700** [comment]
Thanks !!

you are right, I made a mistake in line 25.

**Comment by GG700** [comment]
Hi,

I have a new demand about the pipelines.

If I want to make a modification of the pipelines in interaction with tesseract, how can I do ?
Is that possible with the file config.local.js ?

(I would like to have I scan with OCR and and Low quality of the jpg).

**Comment by sbs20** [comment]
You can modify existing pipelines - you would need to find the specific pipeline item and then change it. However, the only way you could do that would be to filter by name, and then modify the existing command. The thing is, I can't make any guarantee that the pipelines won't change a little bit in a future release (either the name or the specific commands).

The better option would be to create a new pipeline option which is all your own. Something like the following (note `-quality 50`)

```javascript
    // Add a custom print pipeline
    config.pipelines.push({
        extension: 'pdf',
        description: '@:pipeline.ocr | PDF (JPG | @:pipeline.low-quality)',
        commands: [
          'convert @- -quality 50 tmp-%d.jpg && ls tmp-*.jpg',
          `${this.tesseract} -l ${this.ocrLanguage} -c stream_filelist=true - - pdf > scan-0001.pdf`,
          'ls scan-*.*'
        ]
      });
```

**Comment by sbs20** [comment]
Is this ok? Can it be closed?

**Comment by GG700** [comment]
Hi,

thanks, but scanservjs returns an error. I don't know how to resolve this problem.

![Capture du 2021-04-13 11-21-33](https://user-images.githubusercontent.com/49592541/114530734-843cf600-9c4b-11eb-8f51-c88a1cbcd43f.png)
[config.local.js.zip](https://github.com/sbs20/scanservjs/files/6302669/config.local.js.zip)


I also would like to "force" the parameters BATCH and FORMAT of the output file with this file config.local.js but I don't find any parameter or variable to do this. Is there a solution ?


<pre>Apr 13 10:21:12 SPRINT server.js[1275]: [2021-04-13T09:21:12.489Z] DEBUG (Http): request:  {
Apr 13 10:21:12 SPRINT server.js[1275]:   method: &apos;POST&apos;,
Apr 13 10:21:12 SPRINT server.js[1275]:   path: &apos;/scanner/scan&apos;,
Apr 13 10:21:12 SPRINT server.js[1275]:   body: {
Apr 13 10:21:12 SPRINT server.js[1275]:     version: &apos;2.8.4&apos;,
Apr 13 10:21:12 SPRINT server.js[1275]:     params: {
Apr 13 10:21:12 SPRINT server.js[1275]:       deviceId: &apos;epson2:libusb:001:004&apos;,
Apr 13 10:21:12 SPRINT server.js[1275]:       top: 0,
Apr 13 10:21:12 SPRINT server.js[1275]:       left: 0,
Apr 13 10:21:12 SPRINT server.js[1275]:       width: 215,
Apr 13 10:21:12 SPRINT server.js[1275]:       height: 297,
Apr 13 10:21:12 SPRINT server.js[1275]:       resolution: 300,
Apr 13 10:21:12 SPRINT server.js[1275]:       mode: &apos;Color&apos;
Apr 13 10:21:12 SPRINT server.js[1275]:     },
Apr 13 10:21:12 SPRINT server.js[1275]:     filters: [],
Apr 13 10:21:12 SPRINT server.js[1275]:     pipeline: &apos;@:pipeline.ocr | PDF (JPG | @:pipeline.low-quality)&apos;,
Apr 13 10:21:12 SPRINT server.js[1275]:     batch: &apos;none&apos;,
Apr 13 10:21:12 SPRINT server.js[1275]:     index: 1
Apr 13 10:21:12 SPRINT server.js[1275]:   }
Apr 13 10:21:12 SPRINT server.js[1275]: }
Apr 13 10:21:12 SPRINT server.js[1275]: [2021-04-13T09:21:12.495Z] DEBUG (Scan): Scanning
Apr 13 10:21:12 SPRINT server.js[1275]: [2021-04-13T09:21:12.496Z] DEBUG (Scanimage): {&quot;context&quot;:{&quot;devices&quot;:[{&quot;id&quot;:&quot;epson2:libusb:001:004&quot;,&quot;version&quot;:&quot;2.8.4&quot;,&quot;features&quot;:{&quot;--mode&quot;:{&quot;default&quot;:&quot;Color&quot;,&quot;parameters&quot;:&quot;Lineart|Gray|Color&quot;,&quot;option
Apr 13 10:21:12 SPRINT server.js[1275]: [2021-04-13T09:21:12.497Z] DEBUG (Process): /usr/bin/scanimage -d &apos;epson2:libusb:001:004&apos; --mode &apos;Color&apos; --resolution 300 -l 0 -t 0 -x 215 -y 297 --format &apos;tiff&apos; &gt; ./data/temp/~tmp-scan-0-0001.tif, 
Apr 13 10:21:26 SPRINT server.js[1275]: [2021-04-13T09:21:26.182Z] DEBUG (Scan): Post processing: @:pipeline.ocr | PDF (JPG | @:pipeline.low-quality)
Apr 13 10:21:26 SPRINT server.js[1275]: [2021-04-13T09:21:26.185Z] DEBUG (Process): /usr/bin/convert &apos;./data/temp/~tmp-scan-0-0001.tif&apos; -background &apos;#808080&apos; -extent &apos;2539.3700787401576x3507.8740157480315-0-0&apos; -resize 868 &apos;./data/preview/
Apr 13 10:21:29 SPRINT server.js[1275]: [2021-04-13T09:21:29.002Z] DEBUG (Scan): Executing cmds: [
Apr 13 10:21:29 SPRINT server.js[1275]:   &apos;convert @- -quality 50 tmp-%d.jpg &amp;&amp; ls tmp-*.jpg&apos;,
Apr 13 10:21:29 SPRINT server.js[1275]:   &apos;undefined -l undefined -c stream_filelist=true - - pdf &gt; scan-0001.pdf&apos;,
Apr 13 10:21:29 SPRINT server.js[1275]:   &apos;ls scan-*.*&apos;
Apr 13 10:21:29 SPRINT server.js[1275]: ]
Apr 13 10:21:29 SPRINT server.js[1275]: [2021-04-13T09:21:29.003Z] DEBUG (Process): convert @- -quality 50 tmp-NaN.jpg &amp;&amp; ls tmp-*.jpg,  , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:false,&quot;cwd&quot;:&quot;./data/temp/&quot;}
Apr 13 10:21:31 SPRINT server.js[1275]: [2021-04-13T09:21:31.022Z] DEBUG (Process): undefined -l undefined -c stream_filelist=true - - pdf &gt; scan-0001.pdf,  &lt;Buffer 74 6d 70 2d 30 2e 6a 70 67 0a&gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBu
Apr 13 10:21:31 SPRINT server.js[1275]: [2021-04-13T09:21:31.033Z] ERROR (Http): Error: undefined -l undefined -c stream_filelist=true - - pdf &gt; scan-0001.pdf exited with code: 127, stderr: /bin/sh: 1: undefined: not found
Apr 13 10:21:31 SPRINT server.js[1275]:     at ChildProcess.&lt;anonymous&gt; (/var/www/scanservjs/server/process.js:54:18)
Apr 13 10:21:31 SPRINT server.js[1275]:     at ChildProcess.emit (events.js:314:20)
Apr 13 10:21:31 SPRINT server.js[1275]:     at maybeClose (internal/child_process.js:1047:16)
Apr 13 10:21:31 SPRINT server.js[1275]:     at Socket.&lt;anonymous&gt; (internal/child_process.js:438:11)
Apr 13 10:21:31 SPRINT server.js[1275]:     at Socket.emit (events.js:314:20)
Apr 13 10:21:31 SPRINT server.js[1275]:     at Pipe.&lt;anonymous&gt; (net.js:672:12)</pre>

**Comment by sbs20** [comment]
Ah, I see the problem. The code I pasted used variables which are only available in `Config.js`. 

This line...

```javascript
          `${this.tesseract} -l ${this.ocrLanguage} -c stream_filelist=true - - pdf > scan-0001.pdf`,
```

Should become

```javascript
          `${config.tesseract} -l ${config.ocrLanguage} -c stream_filelist=true - - pdf > scan-0001.pdf`,
```

If you still have problems then you can hard code the values.

```javascript
          `/usr/bin/tesseract -l fra -c stream_filelist=true - - pdf > scan-0001.pdf`,
```

**Comment by sbs20** [comment]
> I also would like to "force" the parameters BATCH and FORMAT of the output file with this file config.local.js but I don't find any parameter or variable to do this. Is there a solution ?

There is currently no way to do this, and it's unlikely to become a feature. That said, the browser should remember your last decision.

**Comment by GG700** [comment]
> Ah, I see the problem. The code I pasted used `this` which is only available in `Config.js`.
> 
> This line...
> 
> ```js
>           `${this.tesseract} -l ${this.ocrLanguage} -c stream_filelist=true - - pdf > scan-0001.pdf`,
> ```
> 
> Should become
> 
> ```js
>           `${config.tesseract} -l ${config.ocrLanguage} -c stream_filelist=true - - pdf > scan-0001.pdf`,
> ```
> 
> If you still have problems then you can hard code the values.
> 
> ```js
>           `/usr/bin/tesseract -l fra -c stream_filelist=true - - pdf > scan-0001.pdf`,
> ```

THANKS, it's OK with this line !

**Comment by GG700** [comment]
> > I also would like to "force" the parameters BATCH and FORMAT of the output file with this file config.local.js but I don't find any parameter or variable to do this. Is there a solution ?
> 
> There is currently no way to do this, and it's unlikely to become a feature. That said, the browser should remember your last decision.

I agree with you, the browser remember my last selection. But I have to make a RESET when the scanner restart because the USB ID change after.
