### ISSUE TITLE
FEATURE REQUEST: tag docker image

### ISSUE THREAD

**Issue by whysthatso** [sbs20/scanservjs#185]
besides 'latest' would it be difficult to add the release tag to the docker image on docker hub?

i am usually updating all my docker-run apps by bumping the release tag in an ansible inventory file and that change will trigger a docker-compose rerun including a pull. with latest, that would mean i would have to trigger that run in a different way.

furthermore, this way i can easily discern what version i exactly run when reviewing docker ps output, or looking at my own documentation.

i'm not sure exactly how the docker hub image is built, i might be able to contribute here.

**Comment by sbs20** [comment]
I am very much in favour of doing this. At the moment, I use docker hub to automate the docker build. But it's not completely clear to me what I would need to do to make this work and I am short on time to investigate.

My guess is to maybe create a VERSION inside the image and then read that on dockerhub to add a tag. Any suggestions and approaches very welcome!

**Comment by whysthatso** [comment]
just now saw your comments, and because i went through the research i leave this here for future reference :D

![screenshot](https://user-images.githubusercontent.com/1685114/114388581-8b58fb00-9b9c-11eb-8b48-d0c7be8a174e.png)

**Comment by sbs20** [comment]
Done!

docker pull sbs20/scanservjs:release-v2.9.1
