### ISSUE TITLE
Merge with Cups (balena)

### ISSUE THREAD

**Issue by colofdurty** [sbs20/scanservjs#186]
Hey, 

is it possible to merge it with cups? 

The easiest way would be to add it to: [Balena cups](https://github.com/willswire/balenaPrint) 

That users can install it with one click

Regards

**Comment by sbs20** [comment]
Hi. Thanks for taking the time to suggest this. It's not something I really have time to focus on and while I suspect there is a definite overlap with those who want CUPS, I think giving users the flexibility to choose is my preference.

If someone else wants to take this on then I'm happy to help where possible.
