### ISSUE TITLE
Preview results in termination on low-memory platforms

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#187]
Hi,

I report a problem of crash of scanserv when I asked a preview of my scan.
The web page didn't respond any more, (the other services of my raspberry too, cups by example).

You can see below my journal  
<pre>Apr 12 16:57:51 SPRINT server.js[20121]: [2021-04-12T15:57:51.286Z] DEBUG (Http): request:  {
Apr 12 16:57:51 SPRINT server.js[20121]:   method: &apos;POST&apos;,
Apr 12 16:57:51 SPRINT server.js[20121]:   path: &apos;/scanner/preview&apos;,
Apr 12 16:57:51 SPRINT server.js[20121]:   body: {
Apr 12 16:57:51 SPRINT server.js[20121]:     version: &apos;2.8.4&apos;,
Apr 12 16:57:51 SPRINT server.js[20121]:     params: {
Apr 12 16:57:51 SPRINT server.js[20121]:       deviceId: &apos;epson2:libusb:001:014&apos;,
Apr 12 16:57:51 SPRINT server.js[20121]:       top: 0,
Apr 12 16:57:51 SPRINT server.js[20121]:       left: 0,
Apr 12 16:57:51 SPRINT server.js[20121]:       width: 210,
Apr 12 16:57:51 SPRINT server.js[20121]:       height: 295,
Apr 12 16:57:51 SPRINT server.js[20121]:       resolution: 300,
Apr 12 16:57:51 SPRINT server.js[20121]:       mode: &apos;Color&apos;
Apr 12 16:57:51 SPRINT server.js[20121]:     },
Apr 12 16:57:51 SPRINT server.js[20121]:     filters: [],
Apr 12 16:57:51 SPRINT server.js[20121]:     pipeline: &apos;PDF (JPG | @:pipeline.low-quality)&apos;,
Apr 12 16:57:51 SPRINT server.js[20121]:     batch: &apos;manual&apos;,
Apr 12 16:57:51 SPRINT server.js[20121]:     index: -1
Apr 12 16:57:51 SPRINT server.js[20121]:   }
Apr 12 16:57:51 SPRINT server.js[20121]: }
Apr 12 16:57:51 SPRINT server.js[20121]: [2021-04-12T15:57:51.303Z] DEBUG (Scanimage): {&quot;context&quot;:{&quot;devices&quot;:[{&quot;id&quot;:&quot;epson2:libusb:001:014&quot;,&quot;version&quot;:&quot;2.8.4&quot;,&quot;features&quot;:{&quot;--mode&quot;:{&quot;default&quot;:&quot;Color&quot;,&quot;parameters&quot;:&quot;Lineart|Gray|Color&quot;,&quot;optio
Apr 12 16:57:51 SPRINT server.js[20121]: [2021-04-12T15:57:51.304Z] DEBUG (Process): /usr/bin/scanimage -d &apos;epson2:libusb:001:014&apos; --mode &apos;Color&apos; --resolution 300 -l 0 -t 0 -x 215 -y 297 --format &apos;tiff&apos; &gt; ./data/temp/~tmp-scan-0-0001.tif 
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.354Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.360Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.405Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.409Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.456Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.460Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.521Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.544Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:54 SPRINT server.js[20121]: [2021-04-12T15:57:54.567Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:55 SPRINT server.js[20121]: [2021-04-12T15:57:55.293Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:55 SPRINT server.js[20121]: [2021-04-12T15:57:55.297Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:55 SPRINT server.js[20121]: [2021-04-12T15:57:55.402Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:56 SPRINT server.js[20121]: [2021-04-12T15:57:56.291Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:56 SPRINT server.js[20121]: [2021-04-12T15:57:56.295Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:56 SPRINT server.js[20121]: [2021-04-12T15:57:56.402Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:57 SPRINT server.js[20121]: [2021-04-12T15:57:57.283Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:57 SPRINT server.js[20121]: [2021-04-12T15:57:57.293Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:57 SPRINT server.js[20121]: [2021-04-12T15:57:57.408Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:58 SPRINT server.js[20121]: [2021-04-12T15:57:58.291Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:58 SPRINT server.js[20121]: [2021-04-12T15:57:58.294Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:58 SPRINT server.js[20121]: [2021-04-12T15:57:58.400Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:59 SPRINT server.js[20121]: [2021-04-12T15:57:59.293Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:57:59 SPRINT server.js[20121]: [2021-04-12T15:57:59.295Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:57:59 SPRINT server.js[20121]: [2021-04-12T15:57:59.400Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer &gt; , {&quot;encoding&quot;:&quot;binary&quot;,&quot;shell&quot;:true,&quot;maxBuffer&quot;:16384,&quot;ignoreErrors&quot;:true}
Apr 12 16:58:02 SPRINT server.js[20121]: [2021-04-12T15:58:02.102Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:58:02 SPRINT server.js[20121]: [2021-04-12T15:58:02.120Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:58:02 SPRINT server.js[20121]: [2021-04-12T15:58:02.164Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:58:02 SPRINT server.js[20121]: [2021-04-12T15:58:02.185Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:58:02 SPRINT server.js[20121]: [2021-04-12T15:58:02.286Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:58:02 SPRINT server.js[20121]: [2021-04-12T15:58:02.302Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:58:03 SPRINT server.js[20121]: [2021-04-12T15:58:03.388Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:58:03 SPRINT server.js[20121]: [2021-04-12T15:58:03.416Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:58:04 SPRINT server.js[20121]: [2021-04-12T15:58:04.501Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:58:04 SPRINT server.js[20121]: [2021-04-12T15:58:04.588Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:58:14 SPRINT server.js[20121]: [2021-04-12T15:58:14.235Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:58:14 SPRINT server.js[20121]: [2021-04-12T15:58:14.354Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:58:55 SPRINT server.js[20121]: [2021-04-12T15:58:55.345Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer 49 49 2a 00 68 3d 97 01 aa a6 b2 ac b1 b1 b2 b6 b6 b8 b9 bb b7 bc bd bc bf bf c1 c3 c4 c3 c5 c8 c5 c6 c6 c9 c8 c9 c
Apr 12 16:58:59 SPRINT server.js[20121]: [2021-04-12T15:58:59.686Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer 49 49 2a 00 68 3d 97 01 aa a6 b2 ac b1 b1 b2 b6 b6 b8 b9 bb b7 bc bd bc bf bf c1 c3 c4 c3 c5 c8 c5 c6 c6 c9 c8 c9 c
Apr 12 16:59:06 SPRINT server.js[20121]: [2021-04-12T15:59:06.871Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer 49 49 2a 00 68 3d 97 01 aa a6 b2 ac b1 b1 b2 b6 b6 b8 b9 bb b7 bc bd bc bf bf c1 c3 c4 c3 c5 c8 c5 c6 c6 c9 c8 c9 c
Apr 12 16:59:11 SPRINT server.js[20121]: [2021-04-12T15:59:11.011Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:59:12 SPRINT server.js[20121]: [2021-04-12T15:59:12.302Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:59:12 SPRINT server.js[20121]: [2021-04-12T15:59:12.383Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:59:12 SPRINT server.js[20121]: [2021-04-12T15:59:12.484Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:59:12 SPRINT server.js[20121]: [2021-04-12T15:59:12.534Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/preview&apos; }
Apr 12 16:59:12 SPRINT server.js[20121]: [2021-04-12T15:59:12.635Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 00 2a 00 00 00 08 00 10 00 fe 00 04 00 00 00 01 00 00 00 00 01 00 00 03 00 00 00 01 09 e8 00 00 01 01 00 03 00 00 00 01 
Apr 12 16:59:21 SPRINT server.js[20121]: [2021-04-12T15:59:21.989Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer 49 49 2a 00 68 3d 97 01 aa a6 b2 ac b1 b1 b2 b6 b6 b8 b9 bb b7 bc bd bc bf bf c1 c3 c4 c3 c5 c8 c5 c6 c6 c9 c8 c9 c
Apr 12 16:59:31 SPRINT server.js[20121]: [2021-04-12T15:59:31.433Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer 49 49 2a 00 68 3d 97 01 aa a6 b2 ac b1 b1 b2 b6 b6 b8 b9 bb b7 bc bd bc bf bf c1 c3 c4 c3 c5 c8 c5 c6 c6 c9 c8 c9 c
Apr 12 16:59:38 SPRINT server.js[20121]: [2021-04-12T15:59:38.216Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Buffer 49 49 2a 00 68 3d 97 01 aa a6 b2 ac b1 b1 b2 b6 b6 b8 b9 bb b7 bc bd bc bf bf c1 c3 c4 c3 c5 c8 c5 c6 c6 c9 c8 c9 c
Apr 12 17:00:15 SPRINT systemd[1]: <b>scanservjs.service: Main process exited, code=killed, status=9/KILL</b>
Apr 12 17:00:15 SPRINT systemd[1]: <b>scanservjs.service: Failed with result &apos;signal&apos;.</b>
Apr 12 17:00:15 SPRINT systemd[1]: scanservjs.service: Service RestartSec=100ms expired, scheduling restart.
Apr 12 17:00:15 SPRINT systemd[1]: scanservjs.service: Scheduled restart job, restart counter is at 2.
Apr 12 17:00:15 SPRINT systemd[1]: Stopped scanservjs.
Apr 12 17:00:15 SPRINT systemd[1]: Started scanservjs.
Apr 12 17:00:19 SPRINT server.js[21933]: [2021-04-12T16:00:19.145Z] INFO (server): Started
</pre>

**Comment by sbs20** [comment]
`Apr 12 17:00:15 SPRINT systemd[1]: scanservjs.service: Main process exited, code=killed, status=9/KILL`

Something killed it. Not sure what. Out of memory? https://serverfault.com/a/1008495

Anything in dmesg that gives a clue?

**Comment by GG700** [comment]
Hi,

I had the problem two times on sunday.
But now, I can't reproduce the bug...
And I must restart the raspberry and <pre>dmesg | grep &apos;scanservjs&apos;
</pre> returns anything.

It is certainly a problem of out of memory..

**Comment by sbs20** [comment]
My suggestion for now would be to reduce the preview image resolution. I haven't done a memory profile of the usage but I do know that the preview is reading the uncompressed TIF image from disk and dynamically generating JPG conversions in memory. As the TIF gets larger, the memory used increases too. Generally speaking the memory usage should be trivial for a device which has 1gb of RAM but perhaps if the device is doing other things then maybe there isn't enough available. 

IMHO preview shouldn't need 300dpi - 100dpi should be more than enough. The only reason to use something else is for cases where the scanner itself doesn't work at the default resolution.

**Comment by GG700** [comment]
OK.

You suggest that the limitation at 100 dpi for a preview is made in the hardcode or It have to be selected by the user ?

**Comment by sbs20** [comment]
The user cannot override the preview resolution. It's set in the configuration. Your config.local.js is specifically overriding it:

```javascript
module.exports = {
  /**
   * @param {Configuration} config 
   */
  afterConfig(config) {
    // config.port = 8080;
    // config.devices = [];
    config.ocrLanguage = 'fra';
    // config.log.level = 'DEBUG';
    // config.scanimage = '/usr/bin/scanimage';
    // config.convert = '/usr/bin/convert';
    // config.tesseract = '/usr/bin/tesseract';
    config.previewResolution = 300; // This line here. Change to 100 or just remove it completely.

```

**Comment by GG700** [comment]
I'm confused !

**Comment by sbs20** [comment]
I am happy to help further, let me know.

**Comment by sbs20** [comment]
By default, scanservjs will just use 100dpi for preview.

It is possible to override this setting - to do so you must create a `config.local.js` and set `config.previewResolution = 300;` (or whatever dpi you want) in `afterConfig` - which you are doing. I am guessing you are doing this by accident because you copied and pasted the readme.

I can see that it's set to 300 at the moment - because of the logs above, and also the `config.local.js` you shared in another issue.

The solution is either just to remove that line (the last line in the excerpt above) or change 300 to 100.

**Comment by GG700** [comment]
Hi @sbs20 

When You answered me, I didn't test again.

But I confirm that I have already a problem with the preview even if I put the line config` config.previewResolution` in comment, or if I force ` config.previewResolution` to 100 in the file `config.local.js`.

Can you help me !

<pre>May 01 14:57:14 SPRINT server.js[25492]: [2021-05-01T13:57:14.194Z] INFO (server): Started
May 01 14:58:01 SPRINT server.js[25492]: [2021-05-01T13:58:01.833Z] DEBUG (Http): request:  { method: &apos;GET&apos;, path: &apos;/c
May 01 14:58:02 SPRINT server.js[25492]: [2021-05-01T13:58:02.692Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:02 SPRINT server.js[25492]: [2021-05-01T13:58:02.795Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 
May 01 14:58:15 SPRINT server.js[25492]: [2021-05-01T13:58:15.897Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:58:51 SPRINT server.js[25492]: [2021-05-01T13:58:51.246Z] DEBUG (Http): request:  {
May 01 14:58:51 SPRINT server.js[25492]:   method: &apos;POST&apos;,
May 01 14:58:51 SPRINT server.js[25492]:   path: &apos;/scanner/preview&apos;,
May 01 14:58:51 SPRINT server.js[25492]:   body: {
May 01 14:58:51 SPRINT server.js[25492]:     version: &apos;2.11.0&apos;,
May 01 14:58:51 SPRINT server.js[25492]:     params: {
May 01 14:58:51 SPRINT server.js[25492]:       deviceId: &apos;epson2:libusb:001:004&apos;,
May 01 14:58:51 SPRINT server.js[25492]:       top: 0,
May 01 14:58:51 SPRINT server.js[25492]:       left: 0,
May 01 14:58:51 SPRINT server.js[25492]:       width: 210,
May 01 14:58:51 SPRINT server.js[25492]:       height: 297,
May 01 14:58:51 SPRINT server.js[25492]:       resolution: 300,
May 01 14:58:51 SPRINT server.js[25492]:       mode: &apos;Color&apos;
May 01 14:58:51 SPRINT server.js[25492]:     },
May 01 14:58:51 SPRINT server.js[25492]:     filters: [],
May 01 14:58:51 SPRINT server.js[25492]:     pipeline: &apos;@:pipeline.ocr | PDF (JPG | @:pipeline.low-quality)&apos;,
May 01 14:58:51 SPRINT server.js[25492]:     batch: &apos;manual&apos;,
May 01 14:58:51 SPRINT server.js[25492]:     index: -1
May 01 14:58:51 SPRINT server.js[25492]:   }
May 01 14:58:51 SPRINT server.js[25492]: }
May 01 14:58:51 SPRINT server.js[25492]: [2021-05-01T13:58:51.293Z] DEBUG (Scanimage): {&quot;context&quot;:{&quot;devices&quot;:[{&quot;id&quot;:&quot;e
May 01 14:58:51 SPRINT server.js[25492]: [2021-05-01T13:58:51.294Z] DEBUG (Process): /usr/bin/scanimage -d &apos;epson2:lib
May 01 14:58:52 SPRINT server.js[25492]: [2021-05-01T13:58:52.228Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:52 SPRINT server.js[25492]: [2021-05-01T13:58:52.232Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:58:52 SPRINT server.js[25492]: [2021-05-01T13:58:52.366Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:58:53 SPRINT server.js[25492]: [2021-05-01T13:58:53.184Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:53 SPRINT server.js[25492]: [2021-05-01T13:58:53.185Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:58:53 SPRINT server.js[25492]: [2021-05-01T13:58:53.260Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:58:54 SPRINT server.js[25492]: [2021-05-01T13:58:54.182Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:54 SPRINT server.js[25492]: [2021-05-01T13:58:54.184Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:58:54 SPRINT server.js[25492]: [2021-05-01T13:58:54.294Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:58:55 SPRINT server.js[25492]: [2021-05-01T13:58:55.182Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:55 SPRINT server.js[25492]: [2021-05-01T13:58:55.185Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:58:55 SPRINT server.js[25492]: [2021-05-01T13:58:55.295Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:58:56 SPRINT server.js[25492]: [2021-05-01T13:58:56.311Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:56 SPRINT server.js[25492]: [2021-05-01T13:58:56.313Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:58:56 SPRINT server.js[25492]: [2021-05-01T13:58:56.423Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:58:57 SPRINT server.js[25492]: [2021-05-01T13:58:57.182Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:57 SPRINT server.js[25492]: [2021-05-01T13:58:57.184Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:58:57 SPRINT server.js[25492]: [2021-05-01T13:58:57.287Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:58:59 SPRINT server.js[25492]: [2021-05-01T13:58:59.912Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:58:59 SPRINT server.js[25492]: [2021-05-01T13:58:59.915Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:59:00 SPRINT server.js[25492]: [2021-05-01T13:59:00.024Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:59:00 SPRINT server.js[25492]: [2021-05-01T13:59:00.441Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:00 SPRINT server.js[25492]: [2021-05-01T13:59:00.442Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:59:00 SPRINT server.js[25492]: [2021-05-01T13:59:00.495Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:59:01 SPRINT server.js[25492]: [2021-05-01T13:59:01.243Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:01 SPRINT server.js[25492]: [2021-05-01T13:59:01.245Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer &gt; , {&quot;
May 01 14:59:01 SPRINT server.js[25492]: [2021-05-01T13:59:01.355Z] DEBUG (Process): convert - -quality 75 jpg:-,  &lt;Bu
May 01 14:59:01 SPRINT server.js[25492]: [2021-05-01T13:59:01.623Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:01 SPRINT server.js[25492]: [2021-05-01T13:59:01.626Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 
May 01 14:59:02 SPRINT server.js[25492]: [2021-05-01T13:59:02.545Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:02 SPRINT server.js[25492]: [2021-05-01T13:59:02.561Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 
May 01 14:59:03 SPRINT server.js[25492]: [2021-05-01T13:59:03.771Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:03 SPRINT server.js[25492]: [2021-05-01T13:59:03.802Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 
May 01 14:59:04 SPRINT server.js[25492]: [2021-05-01T13:59:04.616Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:04 SPRINT server.js[25492]: [2021-05-01T13:59:04.661Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 
May 01 14:59:06 SPRINT server.js[25492]: [2021-05-01T13:59:06.413Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:06 SPRINT server.js[25492]: [2021-05-01T13:59:06.495Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 
May 01 14:59:14 SPRINT server.js[25492]: [2021-05-01T13:59:14.849Z] DEBUG (Http): request:  { method: &apos;POST&apos;, path: &apos;/
May 01 14:59:15 SPRINT server.js[25492]: [2021-05-01T13:59:15.664Z] DEBUG (Process): convert -  tif:-,  &lt;Buffer 4d 4d 
<span style="background-color:#FFFFFF"><font color="#3F3F3F">lines 1327-1385/1385 (END)</font></span>
</pre>

**Comment by sbs20** [comment]
Hi. Unfortunately the logs above appear truncated. Are you able to get the full lines as you did on the previous bug report?

**Comment by GG700** [comment]
[log scanservjs.zip](https://github.com/sbs20/scanservjs/files/6411448/log.scanservjs.zip)

I tried with `if (filters && filters.length) {` and it seems to be ok.

I let you close the issue if you want ?

**Comment by sbs20** [comment]
Ok great! I'll keep the issue open until the code reaches `master`

**Comment by GG700** [comment]
Hi,

I made a test with the new version V2.12.1

I am sorry but I have the same problem of low memory...

the line 88 is ok : 
`   if (filters && filters.length) {`
[210507_log_scanservjs.zip](https://github.com/sbs20/scanservjs/files/6439526/210507_log_scanservjs.zip)

**Comment by sbs20** [comment]
Remove all filters for now (you have blur enabled). Filtering increases the memory load.

Also - I note that you are still running the preview resolution at 300dpi. Please, please change it - this increases the memory load on preview by 9 times.

Please share your config.local.js

**Comment by sbs20** [comment]
I don't think that's the config.local.js that's actually being used because it has some errors in it - notably this bit:

```
    // TEST PROVISOIRE
    config.filters.push({
          description: 'Rotate 90',
          params: '-rotate 90'
        });
```

The file is not valid javascript (becuase it's not inside a function) and causes the app not to start at all.

You need to find the real file somewhere (it should be `/var/www/scanservjs/config/config.local.js`). Once you have it, replace with this:

```javascript
module.exports = {
  /**
   * @param {Configuration} config 
   */
  afterConfig(config) {
    config.ocrLanguage = 'fra';

    // Add a custom print pipeline
    config.pipelines.push({
      extension: 'pdf',
      description: '@:pipeline.ocr | PDF (JPG | @:pipeline.low-quality)',
      commands: [
        'convert @- -quality 50 tmp-%d.jpg && ls tmp-*.jpg',
        `${config.tesseract} -l ${config.ocrLanguage} -c stream_filelist=true - - pdf > scan-0001.pdf`,
        'ls scan-*.*'
      ]
    },
    {
      extension: 'pdf',
      description: 'PRINT LEXMARK & PDF',
      commands: [
        'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg',
        'convert @- scan-0000.pdf',
        'lp -d Lexmark_Optra_E312 scan-0000.pdf',
        'ls scan-*.*'
      ]
    });

    // TEST PROVISOIRE
    config.filters.push({
      description: 'Rotate 90',
      params: '-rotate 90'
    });
  },

  /**
   * @param {ScanDevice[]} devices 
   */
  afterDevices(devices) {
    // Override the defaults for plustek scanners
    const device = devices.filter(d => d.id.startsWith('epson'))[0];
    if (device) {
      device.features['--mode'].default = 'Color';
      device.features['--resolution'].default = 300;
    }
  }
};
```

**Comment by GG700** [comment]
I confirm that it is the file witch is in `scanservjs/config/config.local.js`.
But I deleted the bad function in the file.

**Comment by sbs20** [comment]
Ah - you need to restart the service too. The only way the software could possibly be running with the previous invalid file is if it hadn't been restarted.

`sudo systemctl restart scanservjs.service`

**Comment by GG700** [comment]
Hi,

I restarted and it was ok.
I don't remember who I resolved the problem but the modification you made seems to be ok.
I have no problem at this time with the last version V2.15.0.

**Comment by sbs20** [comment]
Brilliant! Thanks for reporting!
