### ISSUE TITLE
FEATURE REQUEST : turn +/- 90°, 180°, cancel when SCAN with prompt

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#188]
Hi,

When we scan with the Batch MANUAL PROMPT, Is that possible to have those complementary buttons : 

- turn doc 90°
- turn doc -90°
- turn doc +180°
- Cancel scan.

It would be very usefull.
![Capture du 2021-04-12 18-05-06](https://user-images.githubusercontent.com/49592541/114532234-eea26600-9c4c-11eb-9b16-7feee3c94ece.png)

**Comment by sbs20** [comment]
Cancel would be relatively easy - though not much different from `Finish`

The rotation gets much more difficult on a "per page" basis.

However, it **is** possible to add rotation as a filter for all pages in the batch - you add the following to config.local.js

```javascript
    config.filters.push({
      description: 'Rotate 90',
      params: '-rotate 90'
    });
```

Would that be sufficient?

**Comment by GG700** [comment]
Hi,

I agree : Cancel is similar to Finish. But without generating the output file.

I don't understand what you mean when you says "it is possible to add rotation as filter in the batch"?

- it is possible to add it in the batch "Manual prompt " ?
- Or it is possible to add it in this filter below ?
![Capture du 2021-04-29 14-14-53](https://user-images.githubusercontent.com/49592541/116550089-9929b280-a8f6-11eb-8123-33d22f36d143.png)

I think it is important to have this function in the batch "Manual with prompt" because we can realize that we have put the document in the scanner upside down after having launched the scan.

**Comment by sbs20** [comment]
I've added cancel to the batch dialog.

I am going to pass on adding rotation within the scan for now. It's rather a lot of effort and would get messy quickly. The workaround is to rescan that single page.
