### ISSUE TITLE
FEATURE REQUEST: Standard paper sizes

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#192]
Hi, this scanning web app is very good and useful. Although there is one thing missing - way to choose paper size from standard paper sizes (for ex. A4, A5, US letter). I need to search for the right size of the standard I need to use and it's anoying work... :D Better option is just simply select the standard size from the list.

I thought about select input under inputs for manually typing size parameters. It could only set these parameters by the choose of the list of standard values. Minimum and maximum values could be computed from size parameters, too. In case some of the size parameters (for ex. x) is changed, "Paper size" (or different name) will be set to "Custom" (or whatever).

Could you add it, please?

**Comment by sbs20** [comment]
So just to confirm, you want to scan a document which is, say, US Letter, you press a button / select something and the width and height become 11x8.5 (in mm)?

**Comment by ceskyDJ** [comment]
Yes, you're correct. Manually typed (or counting after selecting region in preview) are good if you need to crop image to indefinite size but without whitespaces around. For digitalizing documents (mostly A4 in Czech) it's not very good for reasons I've written above.

**Comment by sbs20** [comment]
Sounds good to me.

**Comment by ceskyDJ** [comment]
Ok, thanks.
