### ISSUE TITLE
Assist: `no devices found` in docker

### ISSUE THREAD

**Issue by poikilos** [sbs20/scanservjs#202]
Why split into 2 issues: This error is happening from the docker install (not the one-line install which overlapped the install in #198 and is now uninstalled) 

**Describe the bug**
The web interface has an undefined error.

**To Reproduce**
1. Run one-line install
2. Go to the web interface (remotely via LAN in my case)

**Expected behavior**
- Show specific error instead of "undefined" in the web interface

**Screenshots**

**Client (please complete the following information):**

- Browser: Brave
- Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit)
 
**Server (please complete the following information):**
 - OS: Debian 10
 - Node version 10.24.0
 - NPM version 7.10.0
 - Docker version N/A

**Logs**
 - Please include application logs (see commands below)
 
This may be useful

# Logs if installed manually
`sudo journalctl | grep server.js > scanservjs.log.installed.txt`
n/a

# Logs if in docker
`docker logs scanservjs-container > scanservjs.log.docker.txt`
```
[2021-04-17T23:20:42.635Z] INFO (server): Started
[2021-04-17T23:20:49.393Z] DEBUG (Http): request:  { method: 'GET', path: '/context', params: { force: undefined } }
[2021-04-17T23:20:49.397Z] DEBUG (Devices): devices.json contains no devices. Reloading
[2021-04-17T23:20:49.398Z] DEBUG (Devices): Config.devices:  []
[2021-04-17T23:20:49.398Z] DEBUG (CmdBuilder): build() /usr/bin/scanimage -L
[2021-04-17T23:20:58.784Z] DEBUG (Devices): Device list:  
No scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).

[2021-04-17T23:20:58.874Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
[2021-04-17T23:20:58.881Z] DEBUG (Devices): devices.json contains no devices. Reloading
[2021-04-17T23:20:58.881Z] DEBUG (Devices): Config.devices:  []
[2021-04-17T23:20:58.881Z] DEBUG (CmdBuilder): build() /usr/bin/scanimage -L
[2021-04-17T23:21:06.736Z] DEBUG (Devices): Device list:  
No scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).

[2021-04-17T23:21:06.737Z] ERROR (Http): TypeError: Cannot read property 'features' of undefined
    at Function.readPreview (/app/server/api.js:90:34)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /app/server/configure.js:109:22
[2021-04-17T23:24:13.777Z] DEBUG (Http): request:  { method: 'GET', path: '/context', params: { force: undefined } }
[2021-04-17T23:24:13.778Z] DEBUG (Devices): devices.json contains no devices. Reloading
[2021-04-17T23:24:13.778Z] DEBUG (Devices): Config.devices:  []
[2021-04-17T23:24:13.778Z] DEBUG (CmdBuilder): build() /usr/bin/scanimage -L
[2021-04-17T23:24:21.684Z] DEBUG (Devices): Device list:  
No scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).

[2021-04-17T23:24:21.722Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
[2021-04-17T23:24:21.723Z] DEBUG (Devices): devices.json contains no devices. Reloading
[2021-04-17T23:24:21.724Z] DEBUG (Devices): Config.devices:  []
[2021-04-17T23:24:21.724Z] DEBUG (CmdBuilder): build() /usr/bin/scanimage -L
[2021-04-17T23:24:29.670Z] DEBUG (Devices): Device list:  
No scanners were identified. If you were expecting something different,
check that the scanner is plugged in, turned on and detected by the
sane-find-scanner tool (if appropriate). Please read the documentation
which came with this software (README, FAQ, manpages).

[2021-04-17T23:24:29.670Z] ERROR (Http): TypeError: Cannot read property 'features' of undefined
    at Function.readPreview (/app/server/api.js:90:34)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /app/server/configure.js:109:22

```

**Additional context**
- `sudo -u scanservjs scanimage -L` works fine:
```
device `brother4:net1;dev0' is a Brother MFC-L2740DW MFC-L2740DW
device `brother4:bus2;dev2' is a Brother MFC-L2740DW USB scanner
```

But upon visiting the web interface there are two red popups immediately after loading:

1:

> Found no devices

2:

> {"message":"Cannot read property 'features' of undefined", "code":-1}

I have the udev rules file /etc/udev/rules.d/55-libsane.rules containing `ATTRS{idVendor}=="04f9", ATTRS{idProduct}=="0320", MODE="0666", GROUP="scanner", ENV{libsane_matched}="yes"`

I tried:
- `udevadm control --reload-rules`
- `docker restart scanservjs-container`
- `reboot`

After each command, the issue (the 2 red popups) remained the same.

**Comment by sbs20** [comment]
There are a couple of issues here:

1. `{"message":"Cannot read property 'features' of undefined", "code":-1}`: This is actually the same root cause as `Found no devices`. I am updating the code in dev to just remove this error.
2. The devices can't be found.

Questions:
* How did you create the docker container in the first place? Did you use `privileged` or are you mapping `device`? 
* How are you connecting to the scanner from within docker? [See here](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md#accessing-hardware). You may have more luck sharing the scanner over the network (from host to container).
* Did it work when you just ran the one line install instead (no docker)?

**Comment by poikilos** [comment]
The last time it worked was with Ubuntu using the manual install instructions, but I switched to Debian 10. The one-line install didn't get tried (except overlapping this install which I failed to realize, but I removed it).

- Install steps:
```
apt remove docker
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
apt-cache policy docker-ce
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt-cache policy docker-ce
apt install docker-ce
systemctl status docker
docker pull sbs20/scanservjs:staging
docker rm --force scanservjs-container 2> /dev/null
docker run -d -p 8080:8080 -v /var/run/dbus:/var/run/dbus --restart unless-stopped --name scanservjs-container --privileged sbs20/scanservjs:staging
```
- I assume the question about how I'm connecting from docker is irrelevant since I used the priveleged option and the URL you provide says that is an alternative to device mapping. I added 172.16.0.0/12 to /etc/ as recommended by the "[share the host scanner over the network](https://github.com/sbs20/scanservjs/issues/129#issuecomment-800226184)" URL on the page you said to "[See here](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md#accessing-hardware)".
  - The docker container is listed as being 0.0.0.0 so I'm not sure how to ensure that 172 is correct:
```
# docker container ls -l
CONTAINER ID   IMAGE                      COMMAND     CREATED       STATUS        PORTS                    NAMES
5c6629766f24   sbs20/scanservjs:staging   "/run.sh"   6 weeks ago   Up 20 hours   0.0.0.0:8080->8080/tcp   scanservjs-container
```
  - Consider changing docker.md so that the part about allowing the host network is a step in the main install section--it is behind a URL in a subsection. After that, you may want to explicitly state the command   `sudo systemctl enable saned.socket` after that, because `sudo systemctl enable saned` will not work (it is not a service but a socket, so there will be an error saying it is masked if you try without the .socket part; I only figured out the problem from knowing some things about systemd). It still doesn't work, so I assume that it isn't being used (Does it use USB passthrough by default?). I will wait for the fix you describe, because this is getting to be too much time for me right now.

**Comment by sbs20** [comment]
> you mean don't display an error, not make the root cause not happen

Correct. The root cause is that sane inside the container can't see the scanner outside it. There's nothing else the software can do other than report it, which it already is (`No devices found`).

I think there are two options:

1. Just use the one line install. This is how I use it; on a debian 10 server as a plain old direct install. I personally don't like docker for this project - for exactly the reasons you're experiencing. 

2. If using docker, share the scanner over the network on your Debian host (it sounds like you've done this already). What you also need to do is let the docker container know to look for it - but the documentation could be better. I will fix that. It's the `SANED_NET_HOSTS` [environment variable](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md#environment-variables) you need.

What you ran before

```
docker rm --force scanservjs-container 2> /dev/null
docker run -d -p 8080:8080 -v /var/run/dbus:/var/run/dbus --restart unless-stopped --name scanservjs-container --privileged sbs20/scanservjs:staging
```

Try this (where you replace `172.16.0.4` with the DEBIAN host ip.

```
docker rm --force scanservjs-container 2> /dev/null
docker run -d -p 8080:8080 -e SANED_NET_HOSTS="172.16.0.4" -v /var/run/dbus:/var/run/dbus --restart unless-stopped --name scanservjs-container --privileged sbs20/scanservjs:staging
```

**Comment by sbs20** [comment]
Hi. Did you have any success with the suggestion above? It's also worth looking at #221 and the updated docker docs.

**Comment by sbs20** [comment]
I think it would be useful to break this down.

## Docker

1. Check that the host can reach its SANED binding. Just run `scanimage -d 'net:192.168.1.5:brother4:net1;dev0' -A` on the host. It should return something. If it doesn't then nothing else will work. Check that `saned.socket` is enabled (`sudo systemctl status saned.socket`) and that `net` is listed in `/etc/sane.d/dll.conf`.
2. Check that the docker container can reach it. Run the image interactively and as root: `docker run -it -u 0 --entrypoint=/bin/bash sbs20/scanservjs:latest`. You should land at a prompt.
3. Run `scanimage -L`. This should fail.
4. Now add your host to the container's net list: echo "192.168.1.5" >> /etc/sane.d/net.conf`
5. Run `scanimage -L`. This should work.
6. At this point you should be able to run `scanimage -d 'net:192.168.1.5:brother4:net1;dev0' -A`

`docker-scan-plugin` looks like a vulnerability scanning tool and is nothing to do with scanners.

## Local Debian
Does it work if you just `scanimage -L` and then `scanimage -d 'brother4:net1;dev0' -A`? At the heart of all this, scanservjs just runs SANE command lines. If we can debug those without the software then it will be easier to figure out.

**Comment by poikilos** [comment]
No, `/usr/bin/scanimage -d 'brother4:net1:dev0' -A` does not work ("scanimage: open of device brother4:net1:dev0 failed: Invalid argument"). `/usr/bin/scanimage -L` says:
```
device `brother4:net1;dev0' is a Brother MFC-L2740DW MFC-L2740DW
device `brother4:bus2;dev4' is a Brother MFC-L2740DW USB scanner
```

So I tried `/usr/bin/scanimage -d 'brother4:bus2;dev4' -A` and that works (lists device characteristics).

**Comment by sbs20** [comment]
I think I've figured out what's going on.

The software runs `scanimage -L` to find the scanners. Then for each one that's returned it runs `scanimage -A` to find out more about it.

In Docker above you had this...

```
# docker run -d -p 8080:8080 -e SANED_NET_HOSTS="$SANED_NET_HOSTS" -v /var/run/dbus:/var/run/dbus --restart unless-stopped --name scanservjs-container --privileged sbs20/scanservjs:staging
    # ^ from https://github.com/sbs20/scanservjs/issues/202
    # ^ result:
    # {"message":"Command failed: /usr/bin/scanimage -d 'net:192.168.1.5:brother4:net1;dev0' -A\nscanimage: open of device net:192.168.1.5:brother4:net1;dev0 failed: Invalid argument\n", "code":1}
    # then
    # "Found no devices"
```

This is working from a SANE point of view but the software is bailing out once it hits `brother4:net1;dev0` because `scanimage -A` is returning `Invalid argument`.

The same thing is happening running natively (the one-line install).

And you just reproduced it at the command line.

What I don't understand is why `/usr/bin/scanimage -d 'brother4:net1;dev0'` results in `"scanimage: open of device brother4:net1;dev0 failed: Invalid argument")` That seems like a SANE bug to me but it's at the edge of my knowledge (and I haven't googled it yet).

So our job is to work around that. The good news is that it's possible - but it is going to take a small amount of work.

## Native install (the one liner)

Create `./config/config.local.js`, add the following and restart:

```javascript
module.exports = {
  /**
   * @param {Configuration} config 
   */
  afterConfig(config) {
    // Stop attempting `scanimage -L`
    config.devicesFind = false;
    // Specify the scanner directly
    config.devices = ['brother4:bus2;dev4'];
  }
};
```

## Docker

I am unable to test this right now but I'm fairly sure the following will work.

You need to tell it not to search for scanners, specify the net device and because the device id contains a semicolon `;` you need to change the deliimiter to something else which isn't used - I chose `^` but it could be anything.

```sh
docker run -d -p 8080:8080 \
  -e SANED_NET_HOSTS="$SANED_NET_HOSTS" \
  -e SCANIMAGE_LIST_IGNORE=true \
  -e DEVICES="net:192.168.1.5:brother4:bus2;dev4" \
  -e DELIMITER="^" \
  -v /var/run/dbus:/var/run/dbus \
  --restart unless-stopped \
  --name scanservjs-container \
  --privileged sbs20/scanservjs:staging
```

Thanks for sticking with this. I am going to have a think about the best way to handle this sort of bad behaviour.

Please let me know how you get on!

**Comment by sbs20** [comment]
Just googled it.... this looks similar: https://askubuntu.com/a/447283

**Comment by poikilos** [comment]
Ok, thank you! I can confirm that the config works. Here are explicit steps for the workaround for now:
- `nano /var/www/scanservjs/config/config.local.js`
  - The config only goes in that location for the manual/1-line install.
  - Add the lines even if the file doesn't exist yet as in my case.
  - Change the suggested config to use the bus and port found via `scanimage -L` (the bus and/or port may change on restart as in my case or after unplugging&reinserting the USB device)

I understand this is a workaround and I look forward to an update so I don't have to change the file whenever the port changes (update&restart changed it this time). I'll look into the sane issue and the related URL that you posted.

**Comment by sbs20** [comment]
Great news! I'll keep this issue open while I think about ways to handle. Let me know how you get on with the other link too and I'll document it if useful.

**Comment by sbs20** [comment]
How would you feel about applying [this patch](https://github.com/sbs20/scanservjs/commit/91ae2fa71e15e768fe850bfb214532273c357849), temporarily commenting out the custom config and restarting? I am unable to test this end to end and it would be helpful to know if it works. Effectively it logs errors but continues. I just want to see if the error that comes out provides enough info.
