### ISSUE TITLE
Dots in scan file name

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#211]
Hi, I use Linux OS so I haven't any problems with extensions. There is more complicated situation on Windows. Files are recognized by its extensions and should have only one dot in its name (with exception for special format such as *.tar.gz). Instead of dots you could you dashes.

**Comment by sbs20** [comment]
I've never had a problem on windows with this. However, if you want to change it, you can do so by overriding it in `config.local.js`.

```javascript
const dayjs = require('dayjs');

module.exports = {
  /**
   * @param {Configuration} config 
   */
  afterConfig(config) {
    config.filename = () => {
      return `scan_${dayjs().format('DD-MM-YYYY HH-mm-ss')}`;
    };
  }
};
```

**Comment by ceskyDJ** [comment]
Ok, thanks for your help.
