### ISSUE TITLE
Fix incorrect paper sizes for A4 and A5

### ISSUE THREAD

**Issue by vaagnavanesyan** [sbs20/scanservjs#215]
**Describe the bug**
I've noticed that selecting A4 or A5 predefined paper sizes will produce additional white line in result. Actual A4 size is 297mm x 210mm which is also matches with [ISO paper sizes](https://en.wikipedia.org/wiki/Paper_size#Overview_of_ISO_paper_sizes) and as a consequence A5 should be half of A4 size: 210mm x ~148mm

**To Reproduce**
1. Go to 'Scan'
2. Click on 'Paper Size'
3. Select 'A4' or 'A5'
4. See values in 'Width' and 'Height'

**Expected behavior**
Width is 210 and Height is 297 for A4
Width is 148 and Height is 210 for A5

**Actual behavior**
Width is 215 and Height is 297 for A4 (5 mm wider)
Width is 148 and Height is 215 for A5 (5 mm wider)

**Client (please complete the following information):**
 - Windows 10 Pro 20H2 x64 (Russian language pack)
 - Google Chrome 90.0.4430.85 x64

**Server (please complete the following information):**
 - OS: [DietPi](https://dietpi.com/) v7.0.2 on Raspberry PI 3 Model B+ (aarch64). Additional OS info: 
 ```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"; 
NAME="Debian GNU/Linux"; 
VERSION_ID="10"; 
VERSION="10 (buster)"; 
VERSION_CODENAME=buster; 
ID=debian; 
HOME_URL="https://www.debian.org/"; 
SUPPORT_URL="https://www.debian.org/support"; 
BUG_REPORT_URL="https://bugs.debian.org/"
```
 - Node version v10.24.0
 - NPM version 7.11.1
 - Docker are not used, scanservjs installed by one-line script into the system
 - Logs are attached
[scanservjs.log.installed.txt](https://github.com/sbs20/scanservjs/files/6375917/scanservjs.log.installed.txt)

**Comment by sbs20** [comment]
You're completely right! Whoops! Thank you for raising the issue.
