### ISSUE TITLE
Widen browser support in line with browserslist recommendations

### ISSUE THREAD

**Issue by xxjkzs** [sbs20/scanservjs#243]
It's not a big thing, easily solved , just to let you know.

When I tried to scan some file today with a  computer which hadn't been turned on for a few weeks.  This occured:

Device shown as UNSPECIFIED , the preview window is blank ,  none of the settings are configurable on the Scan page. 
If I click Preview or  Scan it will still work with the default settings, just don't show the preview .

This happened to both Chrome and Firefox, same to the phone browsers. At first I thought it was the server's problem, but after I upgrade the browsers to the latest version (84 -> 90)  everything works fine.

**Comment by sbs20** [comment]
I was convinced this was not true - so I even installed Chrome 84 to prove it... and you're completely correct! Thank you for raising this.

Having looked into the reasons why, I am going to open up the browser support a little bit wider. Having said that, even with the new (and recommended) settings, Chrome 84 wouldn't have worked.

**Comment by sbs20** [comment]
This is actually less to do with the browserslist config and more to do with a missing import for corejs.
