### ISSUE TITLE
Help needed to get it work behind reverse proxy

### ISSUE THREAD

**Issue by xorbetto** [sbs20/scanservjs#250]
hello,
not really an issue, I need some help trying to get it work behind reverse proxy (apache2).
The scanning page/preview/scan finder works all well but the file download doesn't.
My apache2 conf:

```
<Location /scanner/>
       ProxyPass "http://127.0.0.1:8080/"
       ProxyPassReverse "http://127.0.0.1:8080/"
</Location>
```

The result trying to download an acquired image is "Not Found":
​ GET http://172.16.16.2/scanner/files/data%2Foutput%2Fscan_2021-05-14%2015.48.12.jpg 404 (Not Found)

Thank you for the software and for any help

**Comment by sbs20** [comment]
Hi. I'll do what I can to help, but might be a bit slow to get a test rig setup. I don't know the issue off the top of my head but what I'd look for is where the 404 is coming from (Apache or scanservjs). If it's Apache, maybe a rewrite rule is required. If it's scanservjs then see what's in the logs. I'm happy to make any fixes to help it work.

**Comment by sbs20** [comment]
I've just attempted a quick setup with apache2 and it's not currently working at all with the snippet above.

The initial HTML returns absolute paths to `js` and `css` resources e.g. `/css/chunk-vendors.4926465d.css`. All these requests return `404` from apache - which is expected - since they're not under the `/scanner/` path.

Have you also added rewrite rules to your apache config? Could you share this as well please?

**Comment by xxjkzs** [comment]
@ xorbetto I guess if you replace all  `%2F` in the download url to `/ `you can still download the files.
If it is the case, adding  `AllowEncodedSlashes On ` to your `apache2.conf` should solve this problem.

But I also wander how you can make your scanner work by using `<Location>` . I got same error as  ##

**Comment by xorbetto** [comment]
@xxjkzs Thank you! With ```AllowEncodedSlashes On``` I can download and delete files successfully!
@sbs20 You're right, 
the complete configuration is like this:
```
AllowEncodedSlashes On
<Location /scanner/>
        ProxyPass "http://172.16.16.2:8080/"
        ProxyPassReverse "http://172.16.16.2:8080/"
        AddOutputFilterByType SUBSTITUTE text/html
        Substitute "s|172.16.16.2:8080/|172.16.16.2/scanner/|ni"
        Substitute "s|css/|scanner/css/|ni"
        Substitute "s|js/|scanner/js/|ni"
        Substitute "s|favicon.ico|scanner/favicon.ico|ni"
</Location>
```

Obviously in apache2 mod_substitute.so is loaded and enabled. With this conf the js and css
are loaded fine and Im able to scan and preview but settings and file download/delete isn't working.
Adding to the conf ```AllowEncodedSlashes On```  fixes download/delete problems, the only
minor issue is the settings page. When I change color or language the setting itself is applied
but the subsequent refresh didn't work, the app show the page "Error Loading Page" in the middle.

Thank you for the support and for this great software, you made my scanner back to life!

**Comment by sbs20** [comment]
Thanks for the additional info. I'm working on making it more friendly to proxy servers #266
