### ISSUE TITLE
ocrLanguage in  config.local.js does not seem to work

### ISSUE THREAD

**Issue by xxjkzs** [sbs20/scanservjs#251]
with v2.12.3
I tried to change the ocrLanguage in config.local.js, then restarted the service , it seems still use the default language "eng" .
I tried a few different languages, the problem remained. In the same section , I only tried to change the port number , that works fine.

If I change the setting in server/config.js , then restart the service , it takes effect.

**Comment by sbs20** [comment]
I realise now I've never properly tested this. If you need this to work in the mean time, you need to edit the language in `server/config.js`. Sorry about that.
