### ISSUE TITLE
Move reset to Settings

### ISSUE THREAD

**Issue by sbs20** [sbs20/scanservjs#253]
Reset can have unintended consequences if not all scanners are powered on. Also, reset and clear can easily be confused. Since reset is a less commonly used option and can be annoying, move it to Settings

**Comment by GG700** [comment]
Hi,

With my scanner and my raspberry, Each time I start my scanner, I have to use "Reset" button.

Then this is very inconvenient, I have to do a lot of clicks before using this function "Reset".

==> Is that possible to :
- put this button "DEVICE" like in the attachment (in red in the picture),
- OR is that possible to make a "Reset" when we refresh the web page (F5).
![scanservjs_btn](https://user-images.githubusercontent.com/49592541/123551421-f6fd3e00-d771-11eb-8719-d15de3f98dc2.png)
