### ISSUE TITLE
Fix toast message `os.version is not a function` in About page

### ISSUE THREAD

**Issue by xxjkzs** [sbs20/scanservjs#257]
It comes with the latest development branch. 
I can tell it is because os.version() is added in nodejs v13.11 ,  my Ubuntu 20.04 is still using the default nodejs v10.19. 
I guess you are using v14 as develop environment. So I just suggest to add those node upgrade  codes to the installer.sh , by installing the same node version as yours , lots of issues could be avoided.

**Comment by sbs20** [comment]
I have just made it work with v10 rather than force dependency on 14.
