### ISSUE TITLE
Display language names instead of locale names in Settings

### ISSUE THREAD

**Issue by xxjkzs** [sbs20/scanservjs#264]
It is conventional to use codes like `en.UK` or `zh.CN `for locales in programming. We can easily tell what that stands for. But for end users , it is better to display the language names it self like  English or 中文 , users can then  choose the locale faster by reading their native language.

I tried to make the changes myself , but failed , it seems to be more complicated than I expect. ╮（╯＿╰）╭

**Comment by sbs20** [comment]
Yeah, I was being lazy. I can do that.

**Comment by sbs20** [comment]
When you come to add the translation for the locale names, just do the one for Chinese in the `en` file - as that's the fallback. Each language will be in its own language if you see what I mean. So `fr` == `Francais` rather than `French`
