### ISSUE TITLE
Keep last settings for Batch Mode

### ISSUE THREAD

**Issue by deveth0** [sbs20/scanservjs#265]
**Describe the bug**

I'm currently evaluating solutions to resurrect my old scanner and using scanservjs with sane is my best bet right now.
It's a duplex scanner with document feeder (Canon P208) and i saw, that all settings in the webui are persisted upon navigation but not the "batch" config. Is there any chance that you can add this setting to the saved properties? 

**To Reproduce**
1. Open Scan page
2. configure Batch
3. Reload Page
4. Verify that Batch still has the same setting

**Expected behavior**
All Settings should be persisted

**Client (please complete the following information):**
 - Chrome - Latest

**Server (please complete the following information):**
 - latest Docker Image
 
**Additional context**
You already save a json in the local storage (key "request") but this one does not contain the setting for batch.

**Comment by sbs20** [comment]
Oh, you're right. That's weird, I'll investigate.

**Comment by sbs20** [comment]
Thanks. I found the issue. It'll be in the next release. I can't say when it will be exactly, but likely within the next week or so.

**Comment by deveth0** [comment]
No hurry from my side, thanks for the quick fix!
