### ISSUE TITLE
Displayed Date does not flip to next day

### ISSUE THREAD

**Issue by deveth0** [sbs20/scanservjs#268]
**Describe the bug**
I just scanned a document (local time 00:27, server time 22:27) and i got the feeling, the displayed date is not 100% correct ;)

![date](https://user-images.githubusercontent.com/1718655/118893184-4e51f800-b902-11eb-9a16-5b7bd8f5156e.PNG)

**Comment by sbs20** [comment]
Oh my. I have a feeling you're correct!

**Comment by sbs20** [comment]
So I've narrowed it down to this code:

```javascript
      const date = new Date('2021-05-19T23:45:03.236Z');
      console.log(new Intl.DateTimeFormat('en', { dateStyle: 'full', timeStyle: 'long', hour12: false }).format(date));
```

It seems as though Chrome doesn't like that there is no region - the second part of the locale (the `GB` in `en-GB`). I guess the fix is just to put default regions in for everywhere.

**Comment by deveth0** [comment]
Are you sure? I just checked your snippet in my chrome and the output seems to be fine.

```javascript
const date = new Date('2021-05-19T23:45:03.236Z');
console.log(new Intl.DateTimeFormat('en', { dateStyle: 'full', timeStyle: 'long', hour12: false }).format(date));
Thursday, May 20, 2021, 01:45:03 GMT+2

console.log(new Intl.DateTimeFormat('en-GB', { dateStyle: 'full', timeStyle: 'long', hour12: false }).format(date));
Thursday, 20 May 2021 at 01:45:03 CEST

```

**Comment by deveth0** [comment]
Narf... that's a really funny bug 🗡️ 

https://support.google.com/chrome/thread/29828561/chrome-80-shows-timestamp-24-xx-instead-of-00-00?hl=en

**Comment by sbs20** [comment]
Haha - narf indeed!

And good job finding the bug and workaround - I was searching last night and my google fu was weak. The fix will be finding its way into the dev branch soon. Thanks for your help!

**Comment by deveth0** [comment]
Happy to support wherever I can!! looking forward for the merge!
