### ISSUE TITLE
502 Error using Nginx Reverse Proxy

### ISSUE THREAD

**Issue by r7l** [sbs20/scanservjs#273]
**Describe the bug**

I am running a custom Docker image for scanservjs as i plan to extend it later on. I've added a second image with Nginx to be able to use the scanner from all the devices i have in my network. I was following what's written in the Proxy Manual and most things work as expected and i can scan images with my scanner using the web UI. I see all the buttons, favicon and can use all the settings. But i don't see any preview images or scanned images and i am getting an error (sometimes even multiple times) when using the web UI or when scanning:

`SyntaxError: Unexpected token < in JSON at position 0`

The error comes from a POST request to `/preview`. This is the browsers debug console output:

`Failed to load resource: the server responded with a status of 502 () .......... /preview:1`

Later on it fails with another error on console:

`Failed to load resource: net::ERR_INVALID_URL .............. data:image/jpeg;bas…:1`

And another one like this:

`GET data:image/jpeg;base64,undefined net::ERR_INVALID_URL .............. data:image/jpeg;bas…:1`

This is the part of my Nginx config for the scanner proxy:

```
server {

listen 80;
server_name scanner.local;
root /srv/http/scanner/htdocs;

location / {

    proxy_pass http://scanner-image:8080;

    proxy_set_header    X-Real-IP           $remote_addr;

    proxy_connect_timeout 300;
    proxy_read_timeout 300;
    proxy_send_timeout 300;

  }
}
```
What i am wondering is, that i had another VueJS based project hosted some time back and the config was different. Should there be something else added for the client as there is the client directory containing the index.html?

Thanks for you help and for providing this software.

**Comment by sbs20** [comment]
Hi. Which version of the software are you running?

**Comment by r7l** [comment]
I am using the most recent: v2.14.0

**Comment by sbs20** [comment]
Ok. Thanks. Let me investigate.

**Comment by sbs20** [comment]
> What i am wondering is, that i had another VueJS based project hosted some time back and the config was different. Should there be something else added for the client as there is the client directory containing the index.html?

The client directory is mapped as static in server.js so it just appears as the root directory.

I can't reproduce this. I had thought it was because you were mapping to the base path `/` and I'd overlooked testing that, but I've changed it and it still seems to work. Very odd.

A few questions:

* How "modified" is the docker image? Does it work with the supplied one?
* Does it work if you go direct (and miss out nginx)
* What browser are you using?
* If you look at the network tab in the browser debug tools, are there any clues there? Is the content type incorrect?
* Are you running nginx inside the image?

**Comment by r7l** [comment]
Sorry for taking so long but i've figured it out. I had an issue with a missing dependency for Imagemagick, which wasn't obvious as the error returned as 502 at first. It even stayed as 502 when i was replacing Nginx with Traefik. I've thought it might be worth a shot to replace Nginx with Traefik given your suggestion to run the image directly.

But i've finally figured it when i was investigating the output on CLI. Scanservjs fails and crashes when there is an issue with `convert`. Due to the image being restarted instantly, it was hard to guess the source.

My image is pretty simple. Just NodeJS, Imagemagick, Sane and the other dependencies Scanservjs needs. I'm running this image on my NAS, where my scanner is connected to. 

It works perfectly now! Thanks allot for your work and quick reply.

**Comment by sbs20** [comment]
I'm really pleased! It's always satisfying to figure it out. Thanks for letting me know and your kind words.
