### ISSUE TITLE
Contrast and Brightness not shown 

### ISSUE THREAD

**Issue by xxjkzs** [sbs20/scanservjs#280]
"os": {
    "arch": "x64",
    "freemem": 3030,
    "platform": "linux",
    "release": "5.4.0-73-generic",
    "type": "Linux",
    "version": "#82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021"
  },
  "node": "v14.15.1",
  "npm": "7.11.2",
  "docker": false

I guess I have had  this problem for a while , at least since v2.12.3 . I just didn't notice it till I upgrade it to the latest version v2.15 today. When the page is loading or found no device, the Contrast and Brightness section was there , once the device is ready , they went missing. Everything else seems work fine.

**Comment by sbs20** [comment]
This is probably correct behaviour. Can you attach the results of `scanimage -A`? The scanner most likely doesn't support it.

**Comment by xxjkzs** [comment]
Here it is . I am sure I have used these functions before with the same device. 
```
xxx@yyy:~$ scanimage -A
Output format is not set, using pnm as a default.
scanimage: rounded value of br-x from 211.9 to 211.881
scanimage: rounded value of br-y from 355.6 to 355.567

All options specific to device `brother4:bus1;dev1':
  Mode:
    --mode Black & White|Gray[Error Diffusion]|True Gray|24bit Color[Fast] [24bit Color[Fast]]
        Select the scan mode
    --resolution 100|150|200|300|400|600|1200|2400|4800|9600dpi [200]
        Sets the resolution of the scanned image.
    --source FlatBed [FlatBed]
        Selects the scan source (such as a document-feeder).
    --brightness -50..50% (in steps of 1) [inactive]
        Controls the brightness of the acquired image.
    --contrast -50..50% (in steps of 1) [inactive]
        Controls the contrast of the acquired image.
  Geometry:
    -l 0..211.9mm (in steps of 0.0999908) [0]
        Top-left x position of scan area.
    -t 0..355.6mm (in steps of 0.0999908) [0]
        Top-left y position of scan area.
    -x 0..211.9mm (in steps of 0.0999908) [211.881]
        Width of scan-area.
    -y 0..355.6mm (in steps of 0.0999908) [355.567]
        Height of scan-area.
```

**Comment by sbs20** [comment]
I can't really explain what's happened before, but SANE is reporting those functions unavailable (`[inactive]`). The app is behaving as expected. It may be the SANE backend.

**Comment by xxjkzs** [comment]
Thanks for the hint. I just didn't realise I also updated the device driver.
