### ISSUE TITLE
Device discovery errors not handled gracefully

### ISSUE THREAD

**Issue by mbugert** [sbs20/scanservjs#285]
**Describe the bug**
During device discovery, the list of scanners from `scanimage -L` are checked in sequence. If one is unavailable, device discovery stops immediately even if a scanner further down the list would be available.

**To Reproduce**
1. Configure two network scanners and make sure that the one appearing first in `scanimage -L` is offline.
2. Start scanservjs (without having a devices.json).
3. Open in browser to trigger device discovery
4. Log output:
```
scanservjs | [2021-05-27T19:40:21.957Z] INFO (server): Started
scanservjs | [2021-05-27T19:40:28.712Z] DEBUG (Http): request:  { method: 'GET', path: '/context' }
scanservjs | [2021-05-27T19:40:28.716Z] DEBUG (Devices): devices.json does not exist. Reloading
scanservjs | [2021-05-27T19:40:28.716Z] DEBUG (Devices): Config.devices:  []
scanservjs | [2021-05-27T19:40:33.556Z] DEBUG (Devices): Device list:  device `brother4:net1;dev1' is a Brother ADS-2600W-Wired ADS-2600W
scanservjs | device `brother4:net1;dev0' is a Brother ADS-2600W-Wifi ADS-2600W
scanservjs | 
scanservjs | [2021-05-27T19:40:55.978Z] ERROR (Http): Error: Command failed: /usr/bin/scanimage -d 'brother4:net1;dev1' -A
scanservjs | scanimage: open of device brother4:net1;dev1 failed: Invalid argument
scanservjs | 
scanservjs |     at ChildProcess.exithandler (child_process.js:319:12)
scanservjs |     at ChildProcess.emit (events.js:376:20)
scanservjs |     at maybeClose (internal/child_process.js:1055:16)
scanservjs |     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
scanservjs |   killed: false,
scanservjs |   code: 1,
scanservjs |   signal: null,
scanservjs |   cmd: "/usr/bin/scanimage -d 'brother4:net1;dev1' -A",
scanservjs |   stdout: '',
scanservjs |   stderr: 'scanimage: open of device brother4:net1;dev1 failed: Invalid argument\n'
scanservjs | }
scanservjs | [2021-05-27T19:40:56.020Z] DEBUG (Http): request:  { method: 'POST', path: '/preview' }
scanservjs | [2021-05-27T19:40:56.022Z] DEBUG (Devices): devices.json does not exist. Reloading
scanservjs | [2021-05-27T19:40:56.022Z] DEBUG (Devices): Config.devices:  []
scanservjs | [2021-05-27T19:41:00.554Z] DEBUG (Devices): Device list:  device `brother4:net1;dev1' is a Brother ADS-2600W-Wired ADS-2600W
scanservjs | device `brother4:net1;dev0' is a Brother ADS-2600W-Wifi ADS-2600W
scanservjs |
```
It appears to unsuccessfully retry device discovery until the request times out.

**Expected behavior**
Unavailable devices are ignored.

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Node version: v14.17.0
 - NPM version: 7.11.2
 - Docker version: 19.03.12, build 48a66213fe
 - scanservjs: latest master, commit b5fbc8cbf515601c0acbf1d5955bcfbf63d26548

**PR with suggested fix will come shortly**

**Comment by sbs20** [comment]
Thanks for reporting. Does this work? https://github.com/sbs20/scanservjs/issues/202#issuecomment-850568123

**Comment by mbugert** [comment]
Thanks, I didn't try out the patch but it's essentially the same fix I've attempted. Funny how it's even the same `brother4` backend... I suppose you can close this issue then (and the PR). :sweat_smile:

**Comment by sbs20** [comment]
Not only that, but fixed on the same day! One thing though, you changed a couple of additional things in your PR. I want to check that they're not required. The only problem is it's difficult for me to test (no brother scanner). If you get a moment, would it be possible to test the Dev branch?

**Comment by mbugert** [comment]
I just tried the development branch and your changes are sufficient (my JS knowledge is limited, so please ignore my changes).
However, I think it would be useful to have a debug output before `scanimage -A`. It takes 20 to 30 seconds to timeout when a device is unreachable, and in this time, users are left guessing a bit what is going on.

Apart from that, this is a great project! The touchscreen and buttons on my Brother scanner are broken, meaning the device is useless by itself because one cannot trigger scans, but with this project I can trigger it remotely just fine.

**Comment by sbs20** [comment]
Awesome thank you. I'll make some changes then get this pushed out to master.

**Comment by sbs20** [comment]
#202
