### ISSUE TITLE
Use of Docker ARG for customizing UID/GID

### ISSUE THREAD

**Issue by mbugert** [sbs20/scanservjs#287]
Like you are writing in [the documentation](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md), one has to pay attention to the UID/GID when mapping host volumes.
Would you be fine with adding build ARG statements to allow customizing the currently hardcoded UID/GID in the Dockerfile?
Like so:
```
ARG UID=2001
ARG GID=2001
ARG UNAME=scanservjs
RUN groupadd -g $GID -o $UNAME
RUN useradd -o -u $UID -g $GID -m -s /bin/bash $UNAME
[...]
RUN chown -R $UID:$GID config data /etc/sane.d/net.conf /etc/sane.d/airscan.conf
USER $UNAME
```
Users could then choose to build a Docker image with a custom UID/GID via `docker build --build-arg UID=1234 --build-arg GID=5678 .` which would pose a fourth solution to the volume mapping problem.

The issue has been touched upon in #136 and #177 before. Neither of the three current solutions are making me happy because:
1. From the side of the host, the group will be correct but a user with uid 2001 may not exist, making this an imperfect solution.
2. Like in #136, I'm running scanservjs on a Synology NAS so I don't have full control over the UID/GID space. I would rather like to use UIDs/GIDs which Synology is giving me instead of risking to introduce problems by creating new users myself.
3. `chmod 777` is not a secure choice for production systems.

Right now I'm editing the Dockerfile (I have to anyway for the proprietary Brother drivers) but having to make less changes would be cool.
It were even more convenient for users if UID/GID could be chosen at runtime, but (as you probably know) docker does not provide a clean solution to this right now and the workarounds (fixuid, entrypoint script) are a bit hacky.

WDYT?

**Comment by sbs20** [comment]
So, 2001 would still be a default and if left unspecified would still work as today? Assuming so, I am perfectly happy with this approach.

Are you happy to do a PR against the dev branch?

**Comment by mbugert** [comment]
> So, 2001 would still be a default and if left unspecified would still work as today? Assuming so, I am perfectly happy with this approach.

Exactly.

> Are you happy to do a PR against the dev branch?

Sure!

**Comment by sbs20** [comment]
> Right now I'm editing the Dockerfile (I have to anyway for the proprietary Brother drivers) but having to make less changes would be cool.

Would you be up for sharing this? It might be good to add an extract with instructions for others in a similar situation for Synology / Brother

**Comment by mbugert** [comment]
Yes, no problem. To which file in the docs/ folder should I add this information? Setting up the drivers is not necessarily related to Docker, yet I am of course modifying the Dockerfile to make it work for my scenario.

While we're at it, I can also contribute how to set up a custom pipeline for using [ocrmypdf](https://github.com/jbarlow83/OCRmyPDF), which deskews and rotates scanned pages automatically in addition to using tesseract for OCR. Again, I wouldn't be sure where to best put this information right now, so please let me know.

**Comment by sbs20** [comment]
> Yes, no problem. To which file in the docs/ folder should I add this information? Setting up the drivers is not necessarily related to Docker, yet I am of course modifying the Dockerfile to make it work for my scenario.

I see your point. I think the non-docker part of it (the plain driver install) could go in [troubleshooting](https://github.com/sbs20/scanservjs/blob/master/docs/troubleshooting.md). I think the example of how you extend a docker file could go in [docker](https://github.com/sbs20/scanservjs/blob/master/docs/docker.md). If you happen to publish your own then feel free to link to it.

> While we're at it, I can also contribute how to set up a custom pipeline for using ocrmypdf, which deskews and rotates scanned pages automatically in addition to using tesseract for OCR

This should go under [config recipes](https://github.com/sbs20/scanservjs/blob/master/docs/config.md#recipes)

Thank you! I really appreciate the suggestions and help.

**Comment by mbugert** [comment]
Ok. I'll open a separate issue for the extra documentation todos.

**Comment by sbs20** [comment]
I'll keep this open until it's in master
