### ISSUE TITLE
Fails to build and run

### ISSUE THREAD

**Issue by apfeiffe** [sbs20/scanservjs#3]
Tried to install scanservjs on a Raspi running Debian jessi light.

./install.sh will fail with

`0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/bin/nodejs',`
`1 verbose cli   '/usr/bin/npm',`
`1 verbose cli   'install',`
`1 verbose cli   '--only=production' ]`
`2 info using npm@1.4.21`
`3 info using node@v0.10.2`
`4 error install Couldn't read dependencies`
`5 error Error: Invalid name: "@sbs20/scanservjs"`
`5 error     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)` 

Changed name in package.json to 
`{
  "name": "scanservjs",`
to complete installation.

---

`Jan 13 09:20:12 printscan server.js[4655]: /var/www/scanservjs/classes/Config.js:14`
`Jan 13 09:20:12 printscan server.js[4655]: SupportsDepth: false;`
`Jan 13 09:20:12 printscan server.js[4655]: ^`
`Jan 13 09:20:12 printscan server.js[4655]: SyntaxError: Unexpected token ;`

Changed the `;` into `,` in `/var/www/scanservjs/classes/Config.js`

---

`Jan 13 09:30:08 printscan server.js[4978]: /var/www/scanservjs/classes/System.js:27`
`Jan 13 09:30:08 printscan server.js[4978]: execute(cmd) {`
`Jan 13 09:30:08 printscan server.js[4978]: ^`
`Jan 13 09:30:08 printscan server.js[4978]: SyntaxError: Unexpected token (`

Changed in `/var/www/scanservjs/classes/System.js` to
`execute: function(cmd) {`

---

The webserver starts w/o errors, but the UI is missing. You'll see:

scanserv.js
Command line testing »
Input Box with button "exec" right next to it

Anything else missing or needs to be changed?

**Comment by sbs20** [comment]
Hi thanks for taking the time with this - that was really helpful. There were a bunch of fails with all this! I've added linting now so I've fixed the errors you pointed out and more. That said you may still have issues with the package name - I'm using Node 7 with npm 4 - I'd be interested to know. If everything else works I might just change the package name to maximise compatibility.

I have a feeling you might be using an unbuilt version of the code - did you just download the project or go to releases? I've updated the install notes and put comments in the script which might improve matters.

Sam

**Comment by apfeiffe** [comment]
Hi Sam,
thanks for fixing these kind of issues. I followed your suggestion and updated node to v7:

`root@printscan:~/node-v7.4.0-linux-armv6l# node -v && npm -v`
`v7.4.0`
`4.0.5`

The ./install.sh in the scanserv-release archive seems to have the wrong encoding:

`root@printscan:~/scanserv-release# ./install.sh `
`./install.sh: Zeile 1: $'\r': Command not found`

therefore:

`root@printscan:~/scanserv-release# dos2unix install.sh `
`root@printscan:~/scanserv-release# ./install.sh `

`@sbs20/scanservjs@0.1.0 /var/www/scanservjs`
`├─┬ body-parser@1.15.2 `
`│ ├── bytes@2.4.0 `

The script finishes successfully and systemd starts the service:

`root@printscan:~/scanserv-release# systemctl status scanservjs`
`● scanservjs.service - scanservjs`
`   Loaded: loaded (/etc/systemd/system/scanservjs.service; enabled)`
`   Active: active (running) since Sa 2017-01-14 11:46:21 CET; 3s ago`
` Main PID: 992 (node)`
`   CGroup: /system.slice/scanservjs.service`
`           └─992 node /var/www/scanservjs/server.js`
` `
`Jan 14 11:46:21 printscan systemd[1]: Stopping scanservjs...`
`Jan 14 11:46:21 printscan systemd[1]: Starting scanservjs...`
`Jan 14 11:46:21 printscan systemd[1]: Started scanservjs.`

Unfortunately other error are thrown now:

`journalctl -u scanservjs.service -f`
`-- Logs begin at Sa 2017-01-14 11:34:47 CET. --`
` `
`Jan 14 11:46:58 printscan systemd[1]: Starting scanservjs...`
`Jan 14 11:46:58 printscan systemd[1]: Started scanservjs.`
`Jan 14 11:47:02 printscan server.js[1065]: module.js:472`
`Jan 14 11:47:02 printscan server.js[1065]: throw err;`
`Jan 14 11:47:02 printscan server.js[1065]: ^`
`Jan 14 11:47:02 printscan server.js[1065]: Error: Cannot find module './classes/Config'`
`Jan 14 11:47:02 printscan server.js[1065]: at Function.Module._resolveFilename (module.js:470:15)`
`Jan 14 11:47:02 printscan server.js[1065]: at Function.Module._load (module.js:418:25)`
`Jan 14 11:47:02 printscan server.js[1065]: at Module.require (module.js:498:17)`
`Jan 14 11:47:02 printscan server.js[1065]: at require (internal/module.js:20:19)`
`Jan 14 11:47:02 printscan server.js[1065]: at Object.<anonymous> (/var/www/scanservjs/server.js:7:14)`
`Jan 14 11:47:02 printscan server.js[1065]: at Module._compile (module.js:571:32)`
`Jan 14 11:47:02 printscan server.js[1065]: at Object.Module._extensions..js (module.js:580:10)`
`Jan 14 11:47:02 printscan server.js[1065]: at Module.load (module.js:488:32)`
`Jan 14 11:47:02 printscan server.js[1065]: at tryModuleLoad (module.js:447:12)`
`Jan 14 11:47:02 printscan server.js[1065]: at Function.Module._load (module.js:439:3)`
`Jan 14 11:47:02 printscan systemd[1]: scanservjs.service: main process exited, code=exited, status=1/FAILURE`
`Jan 14 11:47:02 printscan systemd[1]: Unit scanservjs.service entered failed state.`

Any further help is appreciated!
Andy.

PS: Using the package version of nodejs (0.10.2) and npm (1.4.12) gives the same failure messages.

**Comment by sbs20** [comment]
Hi! Andy

I'll fix up the EOL encoding - thanks!

Could you do me a favour and send the output of `find /var/www/scanservjs/'?

That the service can't find ./classes/Config (from `Jan 14 11:47:02 printscan server.js[1065]: Error: Cannot find module './classes/Config'`) suggests that either the file isn't there or perhaps it doesn't have permission. So if the files exist can you try running `/var/www/scanservjs/server.js` from the command line. And then `sudo /var/www/scanservjs/server.js` if it fails. Just ignore the service part of it for now.

Sam

**Comment by apfeiffe** [comment]
Hi Sam,
alright; seems to be a permission issue. 

Just to be/make sure:

`root@printscan:/var/www# chown -R scanservjs:scanservjs scanservjs`

The `classes` are there, beside many other files:
`133010    4 drw-r--r--   2 scanservjs scanservjs     4096 Jan 14 11:41 /var/www/scanservjs/classes`
`133017    4 -rw-r--r--   1 scanservjs scanservjs     1309 Jan 14 11:41 /var/www/scanservjs/classes/System.js`
`133012    4 -rw-r--r--   1 scanservjs scanservjs      389 Jan 14 11:41 /var/www/scanservjs/classes/Config.js`

Running as root from /var/www/scanservjs:

`root@printscan:/var/www/scanservjs# ./server.js 
listening`
`System.execute:start=/usr/bin/convert  ./data/preview/preview.tif ./data/preview/preview.jpg`
`System.execute:start=/usr/bin/convert  ./data/preview/preview.tif ./data/preview/preview.jpg`

non-root, as user scanservjs

`root@printscan:/var/www/scanservjs# sudo -u scanservjs bash`
`scanservjs@printscan:/var/www/scanservjs $ ./server.js 
module.js:472`
`    throw err;`
`    ^`
` `
`Error: Cannot find module './classes/Config'`
`    at Function.Module._resolveFilename (module.js:470:15)`

/Andy

**Comment by apfeiffe** [comment]
Sam,

I guess it would help to change the permission from all directories, e.g. `classes` to 755. Same counts for other files. 
Otherwise the user `scanservjs` will fail to access:

`scanservjs@printscan:/var/www/scanservjs $ ./server.js `
`listening`
`System.execute:start=/usr/bin/convert  ./data/preview/preview.tif ./data/preview/preview.jpg`
`Error: EACCES: permission denied, stat '/var/www/scanservjs/assets/css/images/ui-bg_highlight-soft_100_eeeeee_1x100.png'`

/Andy

**Comment by sbs20** [comment]
Ok good news! Thanks for your suggestions. I will have a look and test when I next get a chance and update the script accordingly
