### ISSUE TITLE
Improve multi file delete usability

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#302]
**Describe the bug**
There is a problem with Delete all button (represented by the blue icon) on the Raspberry Pi OSes. I tried it on Raspberry Pi 2B+ and 4B and it doesn't work for both of them.

**To Reproduce**
1. Go to the "Files" section
2. Click on the blue trash icon (delete all records button)
4. It does nothing

**Expected behavior**
It should delete all of the records in the table (all scanned files).

**Screenshots**
Nothing happens with the page, there is nothing to take screenshot of.

**Client (please complete the following information):**
 - Browser: Google Chrome for Linux (OpenSUSE Tumbleweed)
 - Version: 91.0.4472.77 (Official Build) (64-bit)

**Server (please complete the following information):**
 - OS: Raspbian GNU/Linux 10 (buster)
 - Node version: v12.22.0
 - NPM version: 7.11.2
 - Docker version: none (I have it installed manually)

**Logs**
 - Attached here: [scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/6611777/scanservjs.log.installed.txt.gz)

**Comment by ceskyDJ** [comment]
[console-client.log](https://github.com/sbs20/scanservjs/files/6611805/console-client.log)
Here is log of the console on the client side. This errors showed after some time, not just right after clicking the button.

**Comment by sbs20** [comment]
Are you selecting any of the files first? It's not meant to delete all, just the selected ones. Though you can select all with the checkbox at the very top. (Declaration: I haven't been able to look at the logs yet)

**Comment by ceskyDJ** [comment]
Oh, I'm sorry. I just misunderstood the feature. When I select records, it works well. Thanks for explanation.

**Comment by sbs20** [comment]
Don't be sorry. In truth I took a lazy option in not adding text because it means more translation. Do you think the page would benefit from explanatory text? My guess is yes since it wasn't obvious. (Though I'm glad it works technically)

**Comment by ceskyDJ** [comment]
Hmm, I don't know. What do you think about concretely? Add a name to the button, for example "Delete selected" or something else?

I agree with you, with more text comes more translation needs. So, it's difficult question - add it or not?

**Comment by sbs20** [comment]
For the time being I am just going to make the button invisible unless anything is selected and see how that pans out.

**Comment by ceskyDJ** [comment]
Ok, that sounds good.
