### ISSUE TITLE
ocrmypdf pipline page sequence wrong

### ISSUE THREAD

**Issue by Fahrenheit92** [sbs20/scanservjs#304]
When using the ocrmypdf pipline as descriped in https://github.com/sbs20/scanservjs/blob/master/docs/config.md with a duplex multipage scan on Auto-Sequence (Document Feeder) in the final pdf the pages are in the wrong sequence. Is there any specific configuration required?

If not could be an issue of multi-threading and "empty" pages being processed faster than "used" pages might screw over the sequence potentially.

Thanks for this great piece of software,
Kai

**Comment by sbs20** [comment]
Hi!

Does this happen with the other PDF options or just ocrmypdf?

If you scan 4 pages, what order do they end up? Eg 1,4,3,2?

**Comment by Fahrenheit92** [comment]
ocrmypdf only, but It seems that it only happend with one specific document, I will recheck again tomorrow with some other.

The order in the file was: Pg. 1, 11, 12, 2, 3 and correct thereafter. Pg. 11 & 12 being the last physical sheet.

**Comment by Fahrenheit92** [comment]
Error seems to be occuring with documents containing more than 10 pages and page order remains as stated above

**Comment by sbs20** [comment]
I just looked at this more closely... I think it's because of text sorting... which I suspect is because of the output format `tmp-%d.jpg` which should probably be `tmp-%04d.jpg` - try replacing with code below.

```javascript
  config.pipelines.push({
    extension: 'pdf',
    description: 'ocrmypdf (JPG | @:pipeline.high-quality)',
    get commands() {
      return [
        'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg',
        'convert @- pdf:-',
        `ocrmypdf -l ${config.ocrLanguage} --deskew --rotate-pages - scan_0000.pdf`,
        'ls scan_*.*'
      ];
    }
  });
```

**Comment by Fahrenheit92** [comment]
Awesome I'll give it a try with the document I had issues with (if i haven't shredded it already 🙈 )

**Comment by Fahrenheit92** [comment]
> Awesome I'll give it a try with the document I had issues with (if i haven't shredded it already 🙈 )

Unfortunately couldn't find the original document I had issues with anymore but tried with another 6-pager and worked perfectly this time 👍

**Comment by sbs20** [comment]
If I'm correct, I think you need to scan 10 or more pages to see the issue. With any luck you won't see it now.

**Comment by Fahrenheit92** [comment]
> If I'm correct, I think you need to scan 10 or more pages to see the issue. With any luck you won't see it now.

Oh I see, I did a run with 6 Pages Duplex, so 12 in Total ;)
