### ISSUE TITLE
Config Variable for Default Output Directory

### ISSUE THREAD

**Issue by Fahrenheit92** [sbs20/scanservjs#305]
Would be great if the output directory could be set via a variable in the config.local.js

**Comment by sbs20** [comment]
You should be able to set it. Just override this value https://github.com/sbs20/scanservjs/blob/8081f02b4e5772f7b5cdac32a856ceacd0fb1312/packages/server/src/config.js#L45 but in the local file.

You may need to allow unsafe paths too but I haven't tested this area extensively.

**Comment by Fahrenheit92** [comment]
So adding
`config.allowUnsafePaths = true;`
`config.outputDirectory = '*desiredPath*';`
into config.local.js into the "afterConfig" brackets works like a charm, permissions for the scanservjs User/Group have to be checked.

I would suggest to have this reflected in the documentation or even in the provided default file being "//"-out.

**Comment by sbs20** [comment]
Very good. Am updating the docs
