### ISSUE TITLE
hook with dockerhub

### ISSUE THREAD

**Issue by mathieuruellan** [sbs20/scanservjs#31]
Hi,

Could you add hook to the github repository with dockerhub to have a update-to-date docker images ?
The last docker image on the repo is 2years old.

Kind regards,

**Comment by sbs20** [comment]
I'm happy to - but I have no idea how, sorry! Can you point me at some starter docs and I'll try and figure it out

**Comment by mathieuruellan** [comment]
Sure! Here is the official doc: https://docs.docker.com/docker-hub/builds/link-source/

**Comment by sbs20** [comment]
Ok. I've created an automated build and the docker hub repo is [here](https://hub.docker.com/repository/docker/sbs20/scanservjs)

Is this what you meant? (Sorry, don't really use Docker)

**Comment by spacemud** [comment]
Thanks for the Docker hub repo, although I think that's a private link. I can access it [here](https://hub.docker.com/r/sbs20/scanservjs) though. Was just looking for it today...

On a slight tangent, but I do wonder whether it's wise including a SANE install in the Docker image? This seems at odds with [Docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#decouple-applications) and the stated minimalist goals of the project. The frustration for me is that I'd like to roll my own SANE container based on a minimal Alpine image without using the SANE daemon baked into scanservjs.

I do appreciate that simplicity of getting up and running might be of greater concern though. Perhaps separating the SANE and scanservjs installs and providing a docker-compose file to manage them might be the solution.

**Comment by mathieuruellan** [comment]
@spacemud the frontend seems to call scanimage which depends on libsane and not on sane. So no technical problem for that.
But, i guess many users want a simple/easy configuration. In that case, the best is the enemy of the good.
Sane package size is only 300KB and if you don't want to use it for security, userns & no priviliged mode is fine.

**Comment by mathieuruellan** [comment]
@sbs20 Thank you! Feel free to ask me if you have docker questions or tasks in the future!

**Comment by sbs20** [comment]
@mathieuruellan No problem. Do I now need to update the readme to point at the docker repo?

@spacemud I am certainly not against following the best practices - but I must confess that, while I get Docker in principle I just don't use it and so can't really comment on what would be most useful for people. If there's an easy to split things in a way that satisfies everyone's use case then I'm very open to suggestions. Perhaps we move it to a new issue?
