### ISSUE TITLE
Failure in accepting default webpage port number

### ISSUE THREAD

**Issue by BrandNew2000** [sbs20/scanservjs#311]
**Describe the bug**
The program does not accept the default port number (80). 

*To Reproduce**
1. Create config.local.js
2. Set port number to 80

**Expected behavior**
The webpage should load.

**Client (please complete the following information):**
 - Chrome

**Server (please complete the following information):**
 - OS:  RaspberryPi OS

**Comment by sbs20** [comment]
Hi. Ports under 1024 are not allowed for non root users. There are workarounds but it's best either to use the default or use a proxy such as Apache or nginx. See https://unix.stackexchange.com/questions/10735/allowing-a-user-to-let-listen-to-a-port-below-1024 for a general discussion.

**Comment by sbs20** [comment]
Assuming closed. Please reopen or comment if I've misunderstood the problem.
