### ISSUE TITLE
Move reset to Settings  #253 : inconvenient

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#312]
Hi,

This request is related to #253 .
With my scanner and my raspberry, Each time I start my scanner, I have to use "Reset" button.

Then this is very inconvenient, I have to do a lot of clicks before using this function "Reset".

==> Is that possible to:
1/ put this button "DEVICE" like in the attachment (in red in the picture),
2/ OR is that possible to make a "Reset" when we refresh the web page (F5).

![image](https://user-images.githubusercontent.com/49592541/124361835-7f2b8980-dc31-11eb-9dff-268db8c63f9a.png)

**Comment by sbs20** [comment]
Yeah, that's fair. I'm working on it.
