### ISSUE TITLE
Build fails with nodejs > 16 because of 'fiber' dependency of the client

### ISSUE THREAD

**Issue by dadosch** [sbs20/scanservjs#315]
**Describe the bug**
When building with nodejs, it fails because of the 'fiber' dependency of the client, which is incompatible with nodejs 16: https://github.com/laverdet/node-fibers

**Expected behavior**
The Build should succeed

**Server**
 - OS: Arch
 - Node version 16.4.2
 - NPM version 7.17.0

**Logs**
<code>Building for production...node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.</code>
 

**Additional context**
The build succeeds if you remove the fiber dependency, but I'm not sure if it breaks something else :)

**Comment by sbs20** [comment]
I've putting off trying it with node 16!

That said, I'm pretty sure it's possible to just remove `fibers` as it was only there to speed up the `sass` processing - and I never really noticed the improvement anyway (I shouldn't have put it in there).

I'll remove it. Thanks for reporting!

**Comment by sbs20** [comment]
this instead https://github.com/sbs20/scanservjs/commit/de0ce3a1c7bff400bdb8d2b6036ac5e3c3833eb9

**Comment by dadosch** [comment]
> this instead [de0ce3a](https://github.com/sbs20/scanservjs/commit/de0ce3a1c7bff400bdb8d2b6036ac5e3c3833eb9)
> 
> It turns out that the latest packages don't all play well together and nodes 10 to 16. So this takes a more targeted approach.

Quickly tested it on my RPI, and it seems to work fine 👍 _(I have one issue with the parsed result of scanimage when there is a read-only parameter, but this isn't related to node 16 or #316 in any way; I'm going to open a new separate issue shortly, if it's OK)_

**Comment by dadosch** [comment]
Just a quick FYI: I've created a PKGBUILD script in Arch's AUR which allows Arch-distro-based users to quickly install and update scanservjs with any AUR helper, for example yay: `yay -S scanservjs` 
https://aur.archlinux.org/packages/scanservjs/

**Comment by sbs20** [comment]
This is great! I will update the docs to link to it.

**Comment by sbs20** [comment]
> Just a quick FYI: I've created a PKGBUILD script in Arch's AUR which allows Arch-distro-based users to quickly install and update scanservjs with any AUR helper, for example yay: `yay -S scanservjs` https://aur.archlinux.org/packages/scanservjs/

Hi @dadosch - you're not technically a contributor to this project so I can't `@` you anywhere except here, but I've created #660 and thought you may have some thoughts. I have limited experience as a package maintainer so any insight / thoughts / recommendations you have would be greatly appreciated.
