### ISSUE TITLE
Read-only parameters are parsed wrongly

### ISSUE THREAD

**Issue by dadosch** [sbs20/scanservjs#317]
**Describe the bug**
If the scanner has some parameters, which are reported as **read-only**, scanservjs parses "read-only" as the default, also it doesn't make any sense to set read-only parameters, as they are, well, read-only, and this then fails :)

**Actual behaviour**
In the example below, the output ` --source Document Table [Document Table] [read-only]` get's interpreted as that `read-only` is the default setting for the source flag, but that isn't the case. scanservjs tries to pass `--source` to scanimage but that fails, since it is a read-only parameter.

**Expected behavior**
Read-only parameters should be treated like non-existant parameters, since they can't be set anyway in scanimage and lead to scanimage deny service. 

<details>
<summary>
parsed json
</summary>
<pre>
{
  "context": {
    "devices": [
      {
        "id": "utsushi:esci:usb:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.2/1-1.2:1.0",
        "features": {
          "--source": {
            "default": "read-only",
            "parameters": "Document Table [Document Table]",
            "options": [
              "Document Table [Document Table]"
            ]
          },
          "--resolution": {
            "default": 75,
            "parameters": "50..1200dpi",
            "options": [
              50,
              75,
              150,
              300,
              600,
              1200
            ]
          },
          "--resolution-bind": {
            "default": "yes",
            "parameters": "[=(yes|no)]"
          },
          "--x-resolution": {
            "default": "read-only",
            "parameters": "50..1200dpi [75]"
          },
          "--y-resolution": {
            "default": "read-only",
            "parameters": "50..1200dpi [75]"
          },
          "--scan-area": {
            "default": "Manual",
            "parameters": "Executive/Portrait|ISO/A4/Portrait|ISO/A5/Portrait|ISO/A5/Landscape|ISO/A6/Portrait|ISO/A6/Landscape|JIS/B5/Portrait|JIS/B6/Portrait|JIS/B6/Landscape|Letter/Portrait|Manual|Maximum"
          },
          "--mode": {
            "default": "Color",
            "parameters": "Monochrome|Grayscale|Color",
            "options": [
              "Monochrome",
              "Grayscale",
              "Color"
            ]
          },
          "-x": {
            "default": 215.9,
            "parameters": "0..215.9mm",
            "limits": [
              0,
              215.9
            ],
            "interval": 1
          },
          "-y": {
            "default": 297.1,
            "parameters": "0..297.18mm",
            "limits": [
              0,
              297.1
            ],
            "interval": 1
          },
          "-l": {
            "default": 0,
            "parameters": "0..215.9mm",
            "limits": [
              0,
              215.9
            ],
            "interval": 1
          },
          "-t": {
            "default": 0,
            "parameters": "0..297.18mm",
            "limits": [
              0,
              297.1
            ],
            "interval": 1
          },
          "--rotate": {
            "default": "0 degrees",
            "parameters": "0 degrees|90 degrees|180 degrees|270 degrees|Auto"
          },
          "--blank-threshold": {
            "default": "0",
            "parameters": "0..100"
          },
          "--brightness": {
            "default": 0,
            "parameters": "-100..100",
            "limits": [
              -100,
              100
            ],
            "interval": 1
          },
          "--contrast": {
            "default": 0,
            "parameters": "-100..100",
            "limits": [
              -100,
              100
            ],
            "interval": 1
          },
          "--threshold": {
            "default": "128",
            "parameters": "0..255"
          },
          "--gamma": {
            "default": "1.8",
            "parameters": "1.0|1.8"
          },
          "--jpeg-quality": {
            "default": "90",
            "parameters": "1..100"
          },
          "--transfer-format": {
            "default": "RAW",
            "parameters": "JPEG|RAW"
          },
          "--transfer-size": {
            "default": "1048576",
            "parameters": "1..268435455"
          }
        },
        "name": "utsushi:esci:usb:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.2/1-1.2:1.0"
      }
    ],
    "version": "2.16.1",
    "diagnostics": [
      {
        "success": true,
        "message": "Found /usr/bin/scanimage"
      },
      {
        "success": true,
        "message": "Found /usr/bin/convert"
      }
    ],
    "pipelines": [
      {
        "extension": "jpg",
        "description": "JPG | @:pipeline.high-quality",
        "commands": [
          "convert @- -quality 92 scan-%04d.jpg",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "jpg",
        "description": "JPG | @:pipeline.medium-quality",
        "commands": [
          "convert @- -quality 75 scan-%04d.jpg",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "jpg",
        "description": "JPG | @:pipeline.low-quality",
        "commands": [
          "convert @- -quality 50 scan-%04d.jpg",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "png",
        "description": "PNG",
        "commands": [
          "convert @- -quality 75 scan-%04d.png",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "tif",
        "description": "TIF | @:pipeline.uncompressed",
        "commands": [
          "convert @- scan-0000.tif",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "tif",
        "description": "TIF | @:pipeline.lzw-compressed",
        "commands": [
          "convert @- -compress lzw scan-0000.tif",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "pdf",
        "description": "PDF (TIF | @:pipeline.uncompressed)",
        "commands": [
          "convert @- scan-0000.pdf",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "pdf",
        "description": "PDF (TIF | @:pipeline.lzw-compressed)",
        "commands": [
          "convert @- -compress lzw tmp-%04d.tif && ls tmp-*.tif",
          "convert @- scan-0000.pdf",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "pdf",
        "description": "PDF (JPG | @:pipeline.high-quality)",
        "commands": [
          "convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg",
          "convert @- scan-0000.pdf",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "pdf",
        "description": "PDF (JPG | @:pipeline.medium-quality)",
        "commands": [
          "convert @- -quality 75 tmp-%04d.jpg && ls tmp-*.jpg",
          "convert @- scan-0000.pdf",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "pdf",
        "description": "PDF (JPG | @:pipeline.low-quality)",
        "commands": [
          "convert @- -quality 50 tmp-%04d.jpg && ls tmp-*.jpg",
          "convert @- scan-0000.pdf",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "pdf",
        "description": "@:pipeline.ocr | PDF (JPG | @:pipeline.high-quality)",
        "commands": [
          "convert @- -quality 92 tmp-%d.jpg && ls tmp-*.jpg",
          "/usr/bin/tesseract -l eng -c stream_filelist=true - - pdf > scan-0001.pdf",
          "ls scan-*.*"
        ]
      },
      {
        "extension": "txt",
        "description": "@:pipeline.ocr | @:pipeline.text-file",
        "commands": [
          "/usr/bin/tesseract -l eng -c stream_filelist=true - - txt > scan-0001.txt",
          "ls scan-*.*"
        ]
      }
    ],
    "filters": [
      {
        "description": "filter.auto-level",
        "params": "-auto-level"
      },
      {
        "description": "filter.threshold",
        "params": "-channel RGB -threshold 80%"
      },
      {
        "description": "filter.blur",
        "params": "-blur 1"
      }
    ],
    "paperSizes": [
      {
        "name": "A3",
        "dimensions": {
          "x": 297,
          "y": 420
        }
      },
      {
        "name": "A4",
        "dimensions": {
          "x": 210,
          "y": 297
        }
      },
      {
        "name": "A5",
        "dimensions": {
          "x": 148,
          "y": 210
        }
      },
      {
        "name": "A6",
        "dimensions": {
          "x": 105,
          "y": 148
        }
      },
      {
        "name": "B3",
        "dimensions": {
          "x": 353,
          "y": 500
        }
      },
      {
        "name": "B4",
        "dimensions": {
          "x": 250,
          "y": 353
        }
      },
      {
        "name": "B5",
        "dimensions": {
          "x": 176,
          "y": 250
        }
      },
      {
        "name": "B6",
        "dimensions": {
          "x": 125,
          "y": 176
        }
      },
      {
        "name": "DIN D3",
        "dimensions": {
          "x": 272,
          "y": 385
        }
      },
      {
        "name": "DIN D4",
        "dimensions": {
          "x": 192,
          "y": 272
        }
      },
      {
        "name": "DIN D5",
        "dimensions": {
          "x": 136,
          "y": 192
        }
      },
      {
        "name": "DIN D6",
        "dimensions": {
          "x": 96,
          "y": 136
        }
      },
      {
        "name": "Letter",
        "dimensions": {
          "x": 216,
          "y": 279
        }
      },
      {
        "name": "Legal",
        "dimensions": {
          "x": 216,
          "y": 356
        }
      },
      {
        "name": "Tabloid",
        "dimensions": {
          "x": 279,
          "y": 432
        }
      },
      {
        "name": "Ledger",
        "dimensions": {
          "x": 432,
          "y": 279
        }
      },
      {
        "name": "Junior legal",
        "dimensions": {
          "x": 127,
          "y": 203
        }
      },
      {
        "name": "Half letter",
        "dimensions": {
          "x": 140,
          "y": 216
        }
      }
    ],
    "batchModes": [
      "none",
      "manual",
      "auto",
      "auto-collate-standard"
    ]
  },
  "params": {
    "deviceId": "utsushi:esci:usb:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.2/1-1.2:1.0",
    "top": 0,
    "left": 0,
    "width": 215.9,
    "height": 297.1,
    "resolution": 100,
    "format": "tiff",
    "mode": "Monochrome",
    "source": "Document Table [Document Table]",
    "brightness": 0,
    "contrast": 0
  },
  "filters": [],
  "pipeline": null,
  "batch": "none",
  "index": 1
}
</pre>
</details>

<details>
<summary>
Output of scanimage -d … -A
</summary>
<pre>
All options specific to device `utsushi:esci:usb:/sys/devices/platform/soc/20980000.usb/usb1/1-1/1-1.2/1-1.2:1.0':
  General:
    --source Document Table [Document Table] [read-only]
        Document Source
    --enable-resampling[=(yes|no)] [inactive]
        This option provides the user with a wider range of supported
        resolutions.  Resolutions not supported by the hardware will be
        achieved through image processing methods.
    --resolution 50..1200dpi [75]
        Resolution
    --resolution-bind[=(yes|no)] [yes]
        Bind X and Y resolutions
    --x-resolution 50..1200dpi [75] [read-only]
        X Resolution
    --y-resolution 50..1200dpi [75] [read-only]
        Y Resolution
    --scan-area Executive/Portrait|ISO/A4/Portrait|ISO/A5/Portrait|ISO/A5/Landscape|ISO/A6/Portrait|ISO/A6/Landscape|JIS/B5/Portrait|JIS/B6/Portrait|JIS/B6/Landscape|Letter/Portrait|Manual|Maximum [Manual]
        Scan Area
    --mode Monochrome|Grayscale|Color [Color]
        Image Type
  Geometry:
    -x 0..215.9mm [215.9]
        Width of scan-area.
    -y 0..297.18mm [297.18]
        Height of scan-area.
    -l 0..215.9mm [0]
        Top Left X
    -t 0..297.18mm [0]
        Top Left Y
  Enhancement:
    --rotate 0 degrees|90 degrees|180 degrees|270 degrees|Auto [0 degrees]
        Rotate
    --blank-threshold 0..100 [0]
        Skip Blank Pages Settings
    --brightness -100..100 [0]
        Change brightness of the acquired image.
    --contrast -100..100 [0]
        Change contrast of the acquired image.
    --threshold 0..255 [128]
        Threshold
  Other:
    --gamma 1.0|1.8 [1.8]
        Gamma
    --jpeg-quality 1..100 [90]
        JPEG Quality
    --transfer-format JPEG|RAW [RAW]
        Selecting a compressed format such as JPEG normally results in faster
        device side processing.
    --transfer-size 1..268435455 [1048576]
        Transfer Size
</pre>
</details>

**Comment by sbs20** [comment]
Agree! Not seen this before. Good news is it's an easy fix. Thanks for sharing the scanimage output.
