### ISSUE TITLE
There are listed some batch scan option not supported by my scanner

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#332]
Hi,

there is a very good and useful way to scanning multiple pages (batch scan). Thanks very much for this feature! But I have a little problem with this feature. My scanner is very basic and it haven't any auto feeder functionality, although there are listed a few options that works with this scanner functionality when the scanner supports them. When I try to use them (I select one of them and run scanning), it throws an error of course.

The error:
```
{"message":"/usr/bin/scanimage -d 'hpaio:/usb/Ink_Tank_Wireless_410_series?serial=CN04H5M08Z06PF' --mode 'Color' --source 'Flatbed' --resolution 300 -l 0 -t 0 -x 210 -y 297 --format 'tiff' --brightness 1000 --contrast 1000 --batch=data/temp/~tmp-scan-1-%04d.tif exited with code: 4, stderr: Scanning infinity pages, incrementing by 1, numbering from 1\nScanning page 1\nScanned page 1. (scanner status = 5)\nScanning page 2\nscanimage: sane_start: Invalid argument\nBatch terminated, 1 page scanned\n","code":-1}
```

Listed options:

- None
- Manual (with prompt)
- Auto (Document feeder)
- Auto (Collate ...)

Right list:

- None
- Manual (with prompt)

**Comment by sbs20** [comment]
Hi. You are correct. The problem (and reason it's like this) is that scanners report their options according to the different drivers (I believe) - and each can be different. For example one scanner might report `Document Feeder` and another might report `ADF` - in other words, it's just string values.

It may be that there's enough scanner coverage now that we know all the possible values (I take this approach with translation [here](https://github.com/sbs20/scanservjs/blob/199efeaa7156d415a6a9424385d22b2f1acc238d/packages/client/src/locales/en.json#L93)). If there's a missing key then the only downside is a missing translation. But if we do it to control batch scanning, then the consequence would be missing functionality.

The downside of **not** doing it are that you have a weird error.

Until now I have considered the current downside to be less bad than the alternative.

What do you think?

**Comment by ceskyDJ** [comment]
So, there is no standard for propagating printer/scanner's features to the sane? It's just all about some strings crated by vendors? In this case one solution could be here. The printer/scanner know what it can do and what can't and eventually throws an error. What about checking what feature (of the "bonus" features like ADF) is supported and what none? This could be done while looking for printers and scanners process, I think. What's your opinion?

**Comment by sbs20** [comment]
It's possible to check if a document feeder is supported by parsing the results of `scanimage -A` - which is what already happens. The scanner returns something which a human can understand but we can only program for it by looking for known string values like `Automatic Document Feeder (left aligned)` or `Auto` or `ADF`. If we don't know all possible string values then we might miss one. It's possible this is an acceptable solution if we have 99% coverage.

If I understand your suggestion correctly, I think you are saying "just try and scan in batch mode and see if it fails" - which is a nice idea, except that

1. You need to select the correct `--source` first (e.g. `ADF`), which we don't know
2. The error takes ages (maybe 20 seconds) to happen which would make the initial startup even slower

Perhaps a better option is just to allow a manual override in config to restrict the possible options.

**Comment by ceskyDJ** [comment]
Yes, you completely understand. You're right, it would be to much time inefficient. The problem with --source is probably a little harder to understand but I don't need it, time consuming problem is enough to make a decision.

**Comment by ceskyDJ** [comment]
One more question... How can I disable some of the options? Is there some steps for it in docs? I looked for it and unfortunately I found nothing. Could you help me, please?

**Comment by sbs20** [comment]
Good question. It's not documented - but you can set:

```javascript
config.batchModes = ['none', 'manual'];
```

Warning: I have not tested this - but it should work just fine. You'd need to do it in `afterConfig`

**Comment by ceskyDJ** [comment]
Ok, I'll try it. Thanks for your help.

**Comment by ceskyDJ** [comment]
It works perfect! Thanks a lot.
