### ISSUE TITLE
Improved i18n

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#337]
Hi, @sbs20,

thanks for releasing version 2.17.0! I looked at it and found a few things that could be done in a better way. It's only details all of the things, so you needn't to hurry up with the fix.

First is the info message box "Deleted file-name.pdf" (message:deleted). I don't know how this message sounds in English but Czech equivalent isn't too good. I need to write some words after file name like "Soubor file-name.pdf byl odstraněn" (File file-name.pdf has been deleted). "Odstraněno file-name.pdf" is bad for me. There is another way how to solve the problem - I can use "Odstraněný soubor: file-name.pdf" (Deleted file: file-name.pdf). This is a little strange sentence.

The next is problem with paper sizes. You have specified sizes like "'A4 Portrait" and I don't know it's a good solution. I thought about using brackets - "A4 (portrait)", it's better for me. What do you think? The best way how to do this is dividing portrait and landscape formats into two buttons or groups (something like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup). This is worse in the Czech, too :D. If you don't want to change it, I'll at least edit the translation to the "brackets form".

You have some of the texts untranslatable. In the new file browser at the bottom is pagination. There are text "Rows per page:" ("Počet řádků na stránku:" in Czech) as a label before select input and "All" ("Vše" in Czech) inside it. I looked after them in locale file but I found nothing.

Thanks for reading. I'll try to answer all your questions in a short time.

**Comment by ceskyDJ** [comment]
I thought about paper sizes in one more way. You have combined two approaches - ISO 216 standard and american sizes. Some sources says the usage is individual in countries over the world - https://web.archive.org/web/20180620043901/http://www.unicode.org/cldr/charts/latest/supplemental/territory_information.html or nice map on Wiki: https://www.wikiwand.com/en/Paper_size. There aren't too many countires where both ISO and american sizes are used. So, what about adding a config item for this? It could be something like two checkboxes:

- [ ] ISO 216 (A4, B1, ...)
- [ ] American paper sizes (Letter, Legal, ...)

**Comment by sbs20** [comment]
Thanks for reporting - hopefully resolved (in dev) now.

**Comment by ceskyDJ** [comment]
Ok, I'll look at it today.

**Comment by sbs20** [comment]
No hurry. I'll hold any PR back a while. There's usually a few translations flow in.

**Comment by ceskyDJ** [comment]
Czech translations are updated.

**Comment by ceskyDJ** [comment]
> The next is problem with paper sizes. You have specified sizes like "'A4 Portrait" and I don't know it's a good solution. I thought about using brackets - "A4 (portrait)", it's better for me. What do you think? The best way how to do this is dividing portrait and landscape formats into two buttons or groups (something like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup). This is worse in the Czech, too :D. If you don't want to change it, I'll at least edit the translation to the "brackets form".

What about that? Is that already resolved, too? I tried to run development version of scanservjs but it doesn't work for me (see #344).

**Comment by ceskyDJ** [comment]
> > The next is problem with paper sizes. You have specified sizes like "'A4 Portrait" and I don't know it's a good solution. I thought about using brackets - "A4 (portrait)", it's better for me. What do you think? The best way how to do this is dividing portrait and landscape formats into two buttons or groups (something like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_optgroup). This is worse in the Czech, too :D. If you don't want to change it, I'll at least edit the translation to the "brackets form".
> 
> What about that? Is that already resolved, too? I tried to run development version of scanservjs but it doesn't work for me (see #344).

Ok, I see it now. For "brackets version" I need to change Czech translation.

One more thing. When you set up "Files per page" label for translation, you forgot to append double dot. So, it should be "Files per page:" instead.

**Comment by ceskyDJ** [comment]
![Screenshot_20210822_023132](https://user-images.githubusercontent.com/48548230/130338149-3c6893fb-baca-44be-8162-84ce543386c3.png)
Are these alerts also translatable?

**Comment by ceskyDJ** [comment]
And one detail that drives me crazy everytime I see it :D.

![Screenshot_20210822_025140](https://user-images.githubusercontent.com/48548230/130338439-5e056a50-3f1f-42a5-841b-8817c40760e6.png)
In the Czech translation the menu of batch scanning looks like this. Could you do it more responsive to get a better look for even Czech or other language with longer words used there?

**Comment by ceskyDJ** [comment]
Hope I personally use English version, where it's OK. But my parents for example are use Czech one, so they have it like in the screenshot.

**Comment by sbs20** [comment]
> One more thing. When you set up "Files per page" label for translation, you forgot to append double dot. So, it should be "Files per page:" instead.

I am ok with this

> Please enter a valid value. The two nearest valid values

This is a bug - there should not be an error message. I am updating it.

> BatchDialog: *And one detail that drives me crazy everytime I see it*

I'm open to suggestions - but I'm not sure there's all that much can be done here.  I accept it's a bit ugly. Is there any way of using a more terse translation for "Rescan"?

**Comment by sbs20** [comment]
(PS - thank you for all your testing and suggestions, this is all making the software better!)

**Comment by ceskyDJ** [comment]
We have no simple word for "Rescan", maybe "Přeskenovat", which isn't the best translation, I think. Dictionary provides this translation but I don't know...

**Comment by ceskyDJ** [comment]
I'll try it and look at it how it's fitting.

**Comment by ceskyDJ** [comment]
Hmm, It doesn't solve the problem.
![Screenshot_20210822_112449](https://user-images.githubusercontent.com/48548230/130349854-c3dd661b-7950-4ba4-947b-35483f08f354.png)

**Comment by ceskyDJ** [comment]
I tried something but the batch preview isn't too responsive - I think due to padding hack on image. The best option could be set maximum height to 90% only and have max-width counted automatically (or better implicitly). What do you think?

**Comment by sbs20** [comment]
The problem with using height is that heights can be very short on some monitors - users of browsers very often adopt a wide-screen window which is not maximised. This results in a tiny dialog which is even worse.

The dialog is responsive in that it responds to different view ports and remains usable but I agree it's less attractive.

I remain open to suggestions, but so far I think this remains the best compromise across all view ports and languages.

**Comment by ceskyDJ** [comment]
> The problem with using height is that heights can be very short on some monitors - users of browsers very often adopt a wide-screen window which is not maximised. This results in a tiny dialog which is even worse.

Ah, ok. I agree.

So, I don't know what to do with that.

**Comment by ceskyDJ** [comment]
German translation looks even worse.
![Screenshot_20210822_122220](https://user-images.githubusercontent.com/48548230/130351740-d71c9851-1e21-43d7-b0b2-e50ca8f93ffd.png)

**Comment by sbs20** [comment]
I have an idea - keep `Next` and `Finish` and put the remaining options in an overflow menu. I'll experiment. But probably not today know.

**Comment by ceskyDJ** [comment]
Ok, it seems like good idea.

**Comment by sbs20** [comment]
I played with it a bit and didn't like putting the two remaining buttons in an overflow menu because it demoted them to second class functions - and "rescan" is important. That left only "cancel" which didn't make much difference.

I have opted to reduce the button sizes and increase the width of the dialog. It's sufficient even for German. Very worst case, the buttons will wrap 🤷

**Comment by ceskyDJ** [comment]
Ok, great! German translation has too descriptive sentences in this place, I think. Maybe @Muehli25 (German translator) could resolve it.

"Seite erneut scannen" --> "Scan page again"
"Nächste Seite scannen" --> "Scan next page"

**Comment by sbs20** [comment]
I suppose, but it fits now right? At least it did in my quick test.

**Comment by ceskyDJ** [comment]
I'm sorry, I didn't test it. I'll try it in a few hours.

**Comment by ceskyDJ** [comment]
So, I've tested it. I think it's ok, good job! But there is one thing - colors. Could you revert old color schema for buttons? Users are used to have old ones.

**Comment by sbs20** [comment]
I swapped the colours because `cancel` should be a warning as it's destructive. It was incorrect before.

**Comment by ceskyDJ** [comment]
Ok, that makes sense.

**Comment by Muehli25** [comment]
> Ok, great! German translation has too descriptive sentences in this place, I think. Maybe @Muehli25 (German translator) could resolve it.
> 
> It could be something like this in English:
> "Seite erneut scannen" --> "Scan page again"
> "Nächste Seite scannen" --> "Scan next page"
> 
> I don't know but maybe only "Erneut scannen" and "Nächste Seite" is enough. What do you think, @Muehli25?

 "Erneut scannen" und "Nächste Seite" is enough!

**Comment by ceskyDJ** [comment]
> > Ok, great! German translation has too descriptive sentences in this place, I think. Maybe @Muehli25 (German translator) could resolve it.
> > It could be something like this in English:
> > "Seite erneut scannen" --> "Scan page again"
> > "Nächste Seite scannen" --> "Scan next page"
> > I don't know but maybe only "Erneut scannen" and "Nächste Seite" is enough. What do you think, @Muehli25?
> 
> "Erneut scannen" und "Nächste Seite" is enough!

Thanks a lot! Could you look at new items for translation (in German localization file) and translate it, please? It's only a few short words/sentences.
