### ISSUE TITLE
Optional paper sizes (ISO or american)

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#338]
I thought about paper sizes in one more way. You have combined two approaches - ISO 216 standard and american sizes. Some sources says the usage is individual in countries over the world - https://web.archive.org/web/20180620043901/http://www.unicode.org/cldr/charts/latest/supplemental/territory_information.html or nice map on Wiki: https://www.wikiwand.com/en/Paper_size (or here: https://images.app.goo.gl/1ESqnpCE4bGfuVd37). There aren't too many countires where both ISO and american sizes are used. So, what about adding a config item for this? It could be something like two checkboxes:

- [x] ISO 216 (A4, B1, ...)
- [x] American paper sizes (Letter, Legal, ...)

**Comment by sbs20** [comment]
Hi. Thanks for the thoughts. Since this is already in configuration, it's possible to override everything in `config.local.js`. I will add a recipe for it. The below will only show paper sizes A|B{number}.

```javascript
module.exports = {
  afterConfig(config) {
    config.paperSizes = config.paperSizes.filter(p => /[AB]\d/.test(p.name));
  }
}
```

**Comment by ceskyDJ** [comment]
Ok, thanks for your solution. I think it's a good idea to add it to the docs, isn't it?

**Comment by sbs20** [comment]
Done in dev

**Comment by ceskyDJ** [comment]
Ok, thanks.
