### ISSUE TITLE
`Invalid argument` on preview (PIXMA busy)

### ISSUE THREAD

**Issue by MarkusLange** [sbs20/scanservjs#339]
**Describe the bug**

**To Reproduce**
just hit preview

**Expected behavior**
{"message":"/usr/bin/scanimage -d 'pixma:MX870_637974000000' --mode 'Color' --source 'Flatbed' --resolution 100 -l 0 -t 0 -x 216 -y 355.6 --format 'tiff' > data/temp/~tmp-scan-0-0001.tif > data/preview/preview.tif exited with code: 4, stderr: scanimage: rounded value of resolution from 100 to 75\nscanimage: rounded value of br-y from 355.6 to 355.6\nscanimage: sane_read: Invalid argument\n","code":-1}

**Screenshots**

**Client (please complete the following information):**
 - Browser [Firefox]
 - Version [91]

**Server (please complete the following information):**
 - OS: [Raspbian]

**Logs**
 - Please include application logs (see commands below)

**Comment by sbs20** [comment]
Hi. This is most likely a permission or driver issue with SANE. Have you tried any of the steps [here](https://github.com/sbs20/scanservjs/blob/master/docs/sane.md#validate-sane-is-working)?

**Comment by MarkusLange** [comment]
Both working:

scanimage -L
device `pixma:MX870_637974000000' is a CANON Canon PIXMA MX870 multi-function peripheral

sudo sane-find-scanner -q
found USB scanner (vendor=0x04a9 [Canon], product=0x1743 [MX870 series]) at libusb:001:004
found USB scanner (vendor=0x0424, product=0x7800) at libusb:001:005

**Comment by sbs20** [comment]
Ok good. And [this](https://github.com/sbs20/scanservjs/blob/master/docs/install.md#troubleshooting)?

**Comment by MarkusLange** [comment]
Works also.
This failure appears not allways looks like an double-use of the interface.

If "click" 3 or 4 times CLEAR on the Interface I can scan again

**Comment by sbs20** [comment]
Ah ok, so it sometimes works? So it would be useful to try a few things.

Does a scan work? i.e. is it just preview? Does preview sometimes work? Amy other information that might help diagnose?

**Comment by MarkusLange** [comment]
> 
> 
> Ah ok, so it sometimes works? So it would be useful to try a few things.
> 
> Does a scan work? i.e. is it just preview? Does preview sometimes work? Amy other information that might help diagnose?

Scan works, also Preview. Strange thing is that if I put an spezific quare on an part of the paper the scan is out of position

Adjusted scan quare
----------------------------
|                                       |
|          -------------          |
|          |                 |          |
|          |                 |          |
|          -------------          |
|                                       |
|                                       |
|                                       |
----------------------------

actually scanned quare
----------------------------
|                                       |
|                                       |
|          -------------          |
|          |                 |          |
|          |                 |          |
|          -------------          |
|                                       |
|                                       |
----------------------------

And if I go back to the Scan page the quare is larger.

**Comment by MarkusLange** [comment]
For the 2nd Problem I found the [this](https://github.com/sbs20/scanservjs/issues/103) but when I add in the config.default.js this

```
    devices
      const device = devices.filter(d => d.id.startsWith('pixma'))[0];
      if (device) {
        device.features['-l'].limits = [0, 216];
        device.features['-t'].limits = [0, 302];
        device.features['-x'].default = 216;
        device.features['-x'].limits = [0, 216];
        device.features['-y'].default = 302;
        device.features['-y'].limits = [0, 302];
      }
```
It does not help but editing the devices.json does the job

**Comment by sbs20** [comment]
So am I right in saying that the first problem is not a problem now?

Re: the second problem - you need to apply the changes to `config.local.js` (not `config.default.js`) and then restart the service (`sudo systemctl restart scanservjs`) for the changes to take effect. Editing devices.json will work until the file is recreated at which point your changes will be list.

**Comment by MarkusLange** [comment]
> 
> 
> So am I right in saying that the first problem is not a problem now?
> 
> Re: the second problem - you need to apply the changes to `config.local.js` (not `config.default.js`) and then restart the service (`sudo systemctl restart scanservjs`) for the changes to take effect. Editing devices.json will work until the file is recreated at which point your changes will be list.

I'm not sure atm, there is something strange with the MX870 or with the scan or scan-aborting routine within sane, if I click preview to often the MX870 says he is scanning (on the Display) but does nothing at all and only works after an reset with power on/off.

Yeah missread it and now created the config.local.js

**Comment by sbs20** [comment]
I'll leave this open a short while in case there's anything else we can do to fix - if not, I'll close.

**Comment by sbs20** [comment]
Closing for now. If you run into more problems / need help, please re-open or create a new issue.
