### ISSUE TITLE
Not working steps of the Run for development section in docs/development.md

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#344]
Hi, @sbs20,

I tried to run develoment version of your project by instructions in the [Run for development](https://github.com/sbs20/scanservjs/blob/master/docs/development.md#run-for-development) section of docs/development.md file but it's not working.

Here is terminal output:

```
npm run serve

> scanservjs@2.17.1 serve
> cd packages/client && npm run serve


> scanservjs@2.17.1 serve
> nodemon --exec 'vue-cli-service serve'

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): ../server/src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `vue-cli-service serve`
sh: line 1: vue-cli-service: command not found
[nodemon] failed to start process, "vue-cli-service serve" exec not found
[nodemon] Error
    at Bus.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:406:35)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nodemon/lib/monitor/run.js:186:11)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
```

**Comment by ceskyDJ** [comment]
Previously it ended with this error:

```
npm run serve

> scanservjs@2.17.1 serve
> nodemon --exec 'vue-cli-service serve'

sh: line 1: nodemon: command not found
```

I installed `nodemon` with `npm install -g nodemon` and it still not works (see above).

**Comment by Guldoman** [comment]
Did you run
```
sudo npm install -g @vue/cli @vue/cli-service-global gulp-cli
npm run install
```

**Comment by ceskyDJ** [comment]
Thanks! It needed `@vue/cli-service-global` :).

Another error occurred:
```
npm run serve

> scanservjs@2.17.1 serve
> cd packages/client && npm run serve


> scanservjs@2.17.1 serve
> nodemon --exec 'vue-cli-service serve'

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): ../server/src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `vue-cli-service serve`
[nodemon] Internal watch failed: ENOSPC: System limit for number of file watchers reached, watch '/.../scanservjs/packages/server/src'
```

**Comment by Guldoman** [comment]
This is probably because your system has a low inotify limit.
You can check it with `sysctl fs.inotify.max_user_watches`. On my system it is `524288`.
You can try to temporarily raise it with `sudo sysctl fs.inotify.max_user_watches=524288`, then try `npm run serve` again.
If you want to raise it permanently you'll have to search for a guide for your distro.

**Comment by ceskyDJ** [comment]
Yes, you're right. Thank you very much.

**Comment by ceskyDJ** [comment]
One more thing... When I run `npm run serve` and try to load webpage with scanservjs app, it loads only white-background page with text "Invalid host header". [This workaround](https://stackoverflow.com/questions/43619644/i-am-getting-an-invalid-host-header-message-when-connecting-to-webpack-dev-ser) works for me but I don't know it's really a good solution.

In project files it's change of file `packages/client/vue.config.js`:
```js
devServer: {
  before: app => {
    configure(app, '../server/');
  },
  disableHostCheck: true // Add this
},
```

**Comment by Guldoman** [comment]
It shouldn't be a problem if you don't expose the server to the internet.
I don't have that error, and I believe it shouldn't appear if you're running the server locally.

**Comment by ceskyDJ** [comment]
I run it locally, of course. The problem could be with the address - it use hostname (`my-pc:8080`) instead of classic local IP address (`127.0.0.1`).

**Comment by Guldoman** [comment]
Yes, that might be it.
I think that replacing `disableHostCheck: true` with `allowedHosts: ['my-pc']` might also solve your problem.
Or you could just visit the page via `localhost:8080`.

**Comment by ceskyDJ** [comment]
I tried `localhost:8080` and `127.0.0.1` before but it doesn't work. Maybe it use another local IP. Thanks for your advice, btw.

**Comment by sbs20** [comment]
I'm happy with `disableHostCheck` - it's development only, and in fact is useful for me too!
