### ISSUE TITLE
[Feature] Upload to paperless-ng

### ISSUE THREAD

**Issue by Celedhrim** [sbs20/scanservjs#351]
First , thx for this excellent software !

I use it mainly to scan document to feed my [paperless-ng](https://github.com/jonaswinkler/paperless-ng) instance.

For this , I first scan , then download the file and upload it to paperless.
Maybe , if possible of course , a good addition could be a button to upload to a paperless instance.

Paperless has an api (https://paperless-ng.readthedocs.io/en/latest/api.html) 

I think about 2 field in settings : 
* paperless instance url
* token

Then a button next to download in files section to directly send file to paperless instance.

**Comment by Celedhrim** [comment]
Hi.

Yeah I'm ok that is a but out of scope for scanservjs , that's why I opened this issue.
I think I will end up with inotify + file name prefix.

* I scan normally
* If I want to upload to paperless , juste rename the file **pl_document_name.ext** then the script will submit document to paperless and remove it from scanservjs file directory.

I think it's a good way to have less manual action ( wife friendly method ! :D ) with the choice to submit to paperless or not.
And your software keep the philosophy : "each program do one thing well" :)

**Comment by sbs20** [comment]
Ok cool - I'd be very interested in whatever you come up with though. If you're happy to share something, then put it in this issue and I'll add it to the docs. Also - thanks for your kind words 😄

**Comment by Celedhrim** [comment]
@sbs20 , here is what I've done : https://github.com/Celedhrim/scantopl
It's not quality software but it works for me ! :)

I first look at incron , but it seems deprecated.
So i decided to start a all in one program.

Why I choose golang ? the single simple binary and the easy it's to make it go in docker.
And it's a good reason to try to golang

**Comment by sbs20** [comment]
Thanks for this - and nice work!

I have updated the [documentation](https://github.com/sbs20/scanservjs/commit/6ff120a7ec6592f9a2cf4360142602f8a9f0f3e0) and linked to your code.

**Comment by Celedhrim** [comment]
Thx ! :)
