### ISSUE TITLE
Suggestion: multiple saving locations

### ISSUE THREAD

**Issue by rourke** [sbs20/scanservjs#357]
I'm not sure where to make suggestions, but I would very much like a feature where I can set different save locations. For me specifically this will be useful so that I can select either:

- Location 1: a folder which is also a network share accessible by the family at home. This would be the default location and allows easy picking up single scan files.
- Location 2: a [paperless-ng](https://github.com/jonaswinkler/paperless-ng) consumption directory which allows me to easily digitize paper documents.

I think it can be useful for many use-cases. A suggestion on how to implement it would be:

- Have an extra card in the settings menu where the user can define:
  - Name of the location
  - Directory
  - Checkbox to select location as default location
  - Sort order (not necessary I would say, but can make it cleaner)
- On the scan page have a drop-down menu to select the location
- On the files page have a drop-down menu to select the location

Unfortunately I don't have the skillset to make a pull request out of this, but I just want to put the idea out there.

**Comment by sbs20** [comment]
Thanks for the suggestion and taking the time to share it. There have been similar requests before, and I'm sympathetic but ultimately want to keep this app lean. For integrations, see this issue: https://github.com/sbs20/scanservjs/issues/351 and the associated commit (which is only in development branch so far)

**Comment by rourke** [comment]
I got you. Even though my personal example involves paperless-ng, I can see this being useful for other use-cases as well. That being said I can definitely see how this is out of scope for scanservjs. I respect you want to keep the app lean.

I would prefer an option that requires less manual actions, but scantopl is already a great step forward for me. Thanks for sharing and consideration!
