### ISSUE TITLE
Suggestion: Recipe for Scan2Mail

### ISSUE THREAD

**Issue by Procuria** [sbs20/scanservjs#360]
First, I would like to thank you very much, @sbs20 for the work that has been put into this awesome project. 
Thanks to it, we can now equip old printers for our self-support group with Scan2Mail without having to sacrifice the hardware or data protection because of using “strange” cloud services (yeah Brother, I'm looking at you).
This is also where the idea for this recipe came from.
If this suggestion is unnecessary or inappropriate, I ask for your indulgence. 

### Recipe for **Scan2Mail** 

1. Setup and configure **[msmtp](https://wiki.debian.org/msmtp)** and **msmtp-mta** as described [here](https://decatec.de/linux/linux-einfach-e-mails-versenden-mit-msmtp/)
2. Install the MIME packer [**mpack**](https://linux.die.net/man/1/mpack) with `sudo apt install mpack` to send the scanned files 
3. Setup [OCRmyPDF](https://github.com/jbarlow83/OCRmyPDF) as described [here](https://ocrmypdf.readthedocs.io/en/latest/installation.html)

Now create the following pipeline in your `config/config.local.js`
```javascript
config.pipelines.push({
       extension: 'pdf',
       description: 'ocrmypdf (Scan2Mail email@address.tld)',
       get commands() {
         return [
           'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg',
           'convert @- pdf:-',
           `file="scan_$(date +"%d_%m_%Y-%H_%M").pdf" && ocrmypdf -l ${config.ocrLanguage} --deskew --rotate-pages --force-ocr - "$file" && mpack -s "Document from Scanner@Office" "$file" email@address.tld`,
           'ls scan_*.*'
         ];
       }
     });
   },
```` 

The important "Scan2Mail"-line is here :  
``file="scan_$(date +"%d_%m_%Y-%H_%M").pdf" && ocrmypdf -l ${config.ocrLanguage} --deskew --rotate-pages --force-ocr - "$file" && mpack -s "Document from Scanner@Office" "$file" email@address.tld`` 

We set first a time-based filename (better than just scan_000x), then OCR the hell out of it and finally send this file to email@address.tld 

Thank you again, and please stay healthy!

**Comment by sbs20** [comment]
Thanks for this! I will add.
