### ISSUE TITLE
Manual Install error on command

### ISSUE THREAD

**Issue by zmp2000** [sbs20/scanservjs#37]
Hi, the follow command listend on install.md returns an error:
`wget -O ~/scanservjs.tar.gz $(curl -s https://api.github.com/repos/sbs20/scanservjs/releases/latest | grep browser_download_url | cut -d '"' -f 4)`

Throws wget: missing URL

**Comment by JnCrMx** [comment]
There is no build attached to the current release. @sbs20 

I think you can work around this by cloning the repository and then using ``npm install`` and ``npm run build`` inside your working copy (which requires Node.js and NPM to be installed).

Then simply change into ``build/`` and continue with running ``sudo ./scanservjs/install.sh``.

**Comment by sbs20** [comment]
Sorry. Should be resolved now. Brain fail.
