### ISSUE TITLE
Docker | devices.json contains no devices

### ISSUE THREAD

**Issue by kodlz** [sbs20/scanservjs#374]
**Describe the bug**
Hi,
I'm using your app for more than year, but after upgrading my Raspberry_pi4 to new Raspberry_OS 11 it stop working.
So I decide to try Docker version of your app.  But I needs to use arm64 version from  [balves42/scanservjs](https://github.com/balves42/scanservjs). 
I browsed other issues, but I didn't find any working solution for my issue.

After long loading I receiving "found no devices" issue in browser.
In Docker log it looks like scanner is recognized but is not able connect to device.

```
root@831103b7c3be:/app# scanimage -L
device `hpaio:/usb/HP_LaserJet_Professional_M1132_MFP?serial=000000000QH61M53PR1a' is a Hewlett-Packard HP_LaserJet_Professional_M1132_MFP all-in-one
root@831103b7c3be:/app# scanimage -T
scanimage: open of device hpaio:/usb/HP_LaserJet_Professional_M1132_MFP?serial=000000000QH61M53PR1a failed: Error during device I/O
```

- I have same issue with and also without _--privileged_ option.
- udev permission rule was applied.
- Outside of container is scanimage and hp-scan working correctly:
```
pi@raspberrypi:~ $ scanimage -T
Output format is not set, using pnm as a default.
scanimage: scanning image of size 632x1125 pixels at 1 bits/pixel
scanimage: acquiring gray frame, 1 bits/sample
scanimage: reading one scanline, 79 bytes...    PASS
scanimage: reading one byte...          PASS
scanimage: stepped read, 2 bytes...     PASS
```

**To Reproduce**
1. Go to the web interface (remotely via LAN)
2. See error "found no devices"

**Expected behavior**

**Screenshots**
![obrázok](https://user-images.githubusercontent.com/10450352/143787274-396d57c2-3652-4f46-918a-62a0ee7a08ca.png)

**Client (please complete the following information):**
 - Browser Firefox
 - Version 94.0.2

**Server (please complete the following information):**
 - OS: Debian 11
 - Node version v14.18.1
 - NPM version 7.11.2
 - Docker version 20.10.11, build dea9396

**Logs**
 /var/log/messages:
```
Nov 28 20:19:14 raspberrypi python3: io/hpmud/musb.c 2189: [334] hpmud_make_usb_uri() bus=001 dev=003
Nov 28 20:19:14 raspberrypi python3: io/hpmud/musb.c 2287: hpmud_make_usb_uri() uri=hp:/usb/HP_LaserJet_Professional_M1132_MFP?serial=000000000QH61M53PR1a bytes_read=70
Nov 28 20:19:14 raspberrypi kernel: [    7.728898] WARNING! power/level is deprecated; use power/control instead
Nov 28 20:19:15 raspberrypi colord[538]: CdMain: failed to emit DeviceAdded: failed to register object: An object is already exported for the interface org.freedesktop.ColorManager.Device at /org/freedesktop/ColorManager/devices/sysfs_Hewlett_Packard_HP_LaserJet_Professional_M1132_MFP
Nov 28 20:19:15 raspberrypi kernel: [    7.920009] usblp 1-1.4:1.0: usblp0: USB Bidirectional printer dev 3 if 0 alt 0 proto 2 vid 0x03F0 pid 0x042A
Nov 28 20:19:15 raspberrypi kernel: [    7.920492] usbcore: registered new interface driver usblp

```

**Logs if in docker**
[scanservjs.log.docker.txt](https://github.com/sbs20/scanservjs/files/7614417/scanservjs.log.docker.txt)

**Additional context**
hp-scan inside container: 

```
root@831103b7c3be:/app# hp-scan -g
warning: hp-scan should not be run as root/superuser.

HP Linux Imaging and Printing System (ver. 3.18.12)
Scan Utility ver. 2.2

Copyright (c) 2001-15 HP Development Company, LP
This software comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to distribute it
under certain conditions. See COPYING file for more details.

hp-scan[87]: debug: getDeviceUri(None, None, ['hpaio'], {'scan-type': (<built-in function gt>, 0)}, , True)
hp-scan[87]: debug: Mode=0
warning: No destinations specified. Adding 'file' destination by default.
Using device hpaio:/usb/HP_LaserJet_Professional_M1132_MFP?serial=000000000QH61M53PR1a
Opening connection to device...
error: SANE: Error during device I/O (code=9)
```

.

**Comment by sbs20** [comment]
Hi. I'm not able to support Docker on rpi at this time.

> but after upgrading my Raspberry_pi4 to new Raspberry_OS 11 it stop working

What I can help with is getting it working using the plain install. I just did a quick install and check on a Raspberry Pi with RPIOS11 and it all seemed fine. Aare you able to share what the problem was? Do you have any log files?

**Comment by kodlz** [comment]
unfortunately I don't have the logs.
OK I'll try plain install again. and let you know

**Comment by kodlz** [comment]
one line installer is working for me.
