### ISSUE TITLE
Feature request:  copy (print) option

### ISSUE THREAD

**Issue by avandeputte** [sbs20/scanservjs#375]
most all-in-one printers with scanner have a "copy" button that essentially does the scan then prints what was scanned (similar to a photocopy/xerox machine).

The requested feature would perform the same function.   Perhaps add a "copy" button next to the "scan" button that would automatically scan then print the scan to a local printer.

**Comment by sbs20** [comment]
Hi. Thanks for the suggestion. Unfortunately, it's not quite so simple to achieve as the printing part would require integrating with CUPS, configuring the printer, and an associated user interface. I've always intended that the scope of this app always be limited to scanning alone.

That said, others have created custom pipelines to achieve this. There's an example here:

https://github.com/sbs20/scanservjs/blob/master/docs/config.md#example-file

I hope that helps.

**Comment by avandeputte** [comment]
I think it would be reasonable expectation that a user would need to configure cups with their printer independently from this app (just like they have to configure saned independently as well).   All that would be needed is to call  lp from this app,  with perhaps a setting for the printer name.

The custom pipeline might be good enough for me,  not sure it passes the 'wife test'.  If I were to fork your code and develop this,  would you have any interest in incorporating it in your app if I were to submit pull requests with that stuff?

**Comment by sbs20** [comment]
>  If I were to fork your code and develop this, would you have any interest in incorporating it in your app if I were to submit pull requests with that stuff?

Perhaps. I've historically been reluctant to get into new features as it tends to increase the burden of testing and maintenance. Keep me posted!
