### ISSUE TITLE
Running under Windows and macOS

### ISSUE THREAD

**Issue by xulihang** [sbs20/scanservjs#376]
Since docker under Windows and macOS uses virtual machine, I wonder if it is possible to run this under Windows and macOS.

**Comment by xulihang** [comment]
Sorry that I didn't go through the docs carefully.

```
Linux host (or VM with necessary pass-through e.g. USB)
```

But if Windows and macOS are supported, I think it is better to write them out.

**Comment by sbs20** [comment]
Hello! I have not specifically tested this, and "supported" does not have much meaning in this context.

If you find yourself having worked out how to do this, then documentation pull requests will be gratefully received! 😄
