### ISSUE TITLE
Error while scanning a document

### ISSUE THREAD

**Issue by BrandNew2000** [sbs20/scanservjs#383]
**Describe the bug**
Attempting to scan or preview the scan causes the below error.

**To Reproduce**
Access website and click on scan/preview

**Expected behavior**
An error appears:
{"message":"/usr/bin/scanimage -d 'hpaio:/usb/Deskjet_F300_series?serial=CN6CEGK2B904KH' --mode 'Color' --source 'Flatbed' --resolution 100 -l 0 -t 0 -x 215.9 -y 296.9 --format 'tiff' --brightness 0 --contrast 0 > data/temp/~tmp-scan-0-0001.tif > data/preview/preview.tif exited with code: 1, stderr: scanimage: open of device hpaio:/usb/Deskjet_F300_series?serial=CN6CEGK2B904KH failed: Invalid argument\n","code":-1}

**Client (please complete the following information):**
- Chrome - 96.0.4664.45

**Server (please complete the following information):**
 - OS: Raspberry Pi OS (Debian release: Buster)
 - Node version: v17.3.0
 - npm version: v8.3.0

**Logs**
[scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/7797595/scanservjs.log.installed.txt.gz)

**Comment by sbs20** [comment]
This is probably a missing driver for your scanner. You'll probably get the same results running scanimage directly from the CLI.

**Comment by BrandNew2000** [comment]
Thanks. Issue fixed
