### ISSUE TITLE
Swagger REST API documentation

### ISSUE THREAD

**Issue by peterhajas** [sbs20/scanservjs#388]
I use scanservjs on my network in a podman container to make scanning much easier, and I dig it!

One feature that would be awesome would be a REST API for querying information about the SANE devices, switching between settings, and triggering a scan. This API could be used by the web front end, and also to integrate scanservjs with other software. For example, I’d like to trigger scans with my scanner’s ADF using Home Assistant.

It’s likely that the current API between the Vue web app and the server backend would be sufficient (it has most of this already). If so, maybe this issue could be recast as a documentation request to document that API.

**Comment by sbs20** [comment]
Hi! Indeed, the current API should have everything needed.

I like the idea and will keep the issue open. I'm not sure when I'll get to it though!

If you have specific questions in the mean time, I'm happy to answer them. I also use HA and think an integration would be cool.

**Comment by torwag** [comment]
I would like to add, being a HA user too, an API which includes, control of scan parameters would enable #465 for HA user in many color full ways.
