### ISSUE TITLE
Make available buttons and sliders depending on scanner

### ISSUE THREAD

**Issue by apfeiffe** [sbs20/scanservjs#4]
Sam,

may I ask you to make the available buttons and sliders dependend on the output of `scanimage -A`?
For example:

`[scanservjs@scanprint ~]$ /usr/bin/scanimage -A`

`All options specific to device epson2:libusb:001:006:`
`  Scan Mode:`
`    --mode Lineart|Gray|Color [Lineart]`
`        Selects the scan mode (e.g., lineart, monochrome, or color).`

`[...]`

`    --brightness 0..0 [inactive]`
`        Selects the brightness.`
`    --sharpness -2..2 [inactive]`

Otherwise the command will fail with something like:

`scanimage: attempted to set inactive option brightness`

Thanks,
Andy

**Comment by sbs20** [comment]
Hey Andy,

That's a good idea! I will look into it and make it happen

Sam

**Comment by sbs20** [comment]
I've added a new feature with device detection using `scanimage -A` as per your suggestion. Scanservjs now checks to see if a feature is allowed before using it. Currently implemented for brightness, contrast and  depth. What is *not* yet implemented is anything in the user interface to stop users wasting their time with it.
