### ISSUE TITLE
Feature Request: Combine (PDF) & Preview grid

### ISSUE THREAD

**Issue by CyrosX** [sbs20/scanservjs#403]
I'm very impressed with the functionality of scanservJS :-).
Nevertheless I want to request 2 very handy features:
1. The possibility to combine (separate) multiple pages into one file.
2. A file grid, which shows small previews of the scanned files. (1. could be integrated here as 2 buttons and via the checkboxes)

**Comment by sbs20** [comment]
Thanks for your suggestions!

1. Brings some challenges with it in that it requires a fair amount (relative to my available time) of work in terms of UX. The complexity comes in establishing order. There is already a feature to allow for batch scanning (either manual or with ADF) which combines pages together for you. I appreciate there are times where this may not be sufficient, though. In those instances there are various existing alternatives (Windows print to PDF being one, or Linux CLI being another). My philosphy has always been to keep this solution as focussed on scanning as possible. Sorry!

2. This is relatively a much lighter piece of work - assuming I understand you correctly. I would decribe it as file thumbnails which will show the scan (or at least its first page). I am working on this in #407
