### ISSUE TITLE
Batch scan with many pages crashed while saving

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#414]
**Describe the bug**
I use this app for a long time but now some bad error occurred. I used manual batch scanning mode and scanned 33 A4 pages. Everything went well until the app started saving (exporting to single PDF) scanned pages. Some very long error messages showed up (unfortunately I haven't that message) and dialog closed. I thought everything is lost but I found scanned pages in /var/www/scanservjs/data/temp folder. I'll try to get the needed output from these data (*.tif and *.jpg files). I hope it will work, I spent half an hour scanning these papers :(.

**To Reproduce**
1. Set "Resolution" to "300"
2. Set "Mode" to "Colour"
3. Set the "Batch" option to "Manual (with prompt)"
4. Let the "Filters" options group empty
5. Set "Format" to "PDF (JPG | Medium quality)"
6. Choose "A4 (portrait)" in the PAPER SIZE menu
7. Click on "SCAN"
8. Scan 33 pages (or different count but many)
9. Click on "Finish"
10. Error occurs

**Expected behavior**
Pages are composed into a single PDF file and the "Files" section is displayed.

**Screenshots**
I'm sorry, I didn't catch the error message.

**Client (please complete the following information):**
 - Browser: Google Chrome
 - Version: 99.0.4844.51

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Node version: v14.19.0
 - NPM version: 8.3.0
 - Docker version: -not used via Docker-

**Logs**
 - [scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/8310347/scanservjs.log.installed.txt.gz)

**Comment by ceskyDJ** [comment]
@sbs20, I'll try to help with resolving this problem but I haven't so much time in these days. You can tag me if you will need my assistance and I won't react.

**Comment by ceskyDJ** [comment]
Thanks to `tiff2pdf` and `pdftk` I finally did it - I have a single PDF with all scanned pages and without scanning again! But the error is still here, so look at it, please. I lost so much time with the manual solution.

**Comment by sbs20** [comment]
Hey, thanks for reporting. It looks the same as #356

I need to check if the manual install makes this change or if it's just docker.

**Comment by sbs20** [comment]
Ok. Here is the important part of your logs:

<details>
  <summary>Error log</summary>

```
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: [2022-03-19T23:37:25.030Z] DEBUG (Process): convert @- -quality 75 tmp-%04d.jpg && ls tmp-*.jpg,  ~tmp-scan-0-0001.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0002.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0003.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0004.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0005.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0006.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0007.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0008.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0009.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0010.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0011.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0012.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0013.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0014.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0015.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0016.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0017.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0018.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0019.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0020.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0021.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0022.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0023.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0024.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0025.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0026.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0027.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0028.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0029.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0030.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0031.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0032.tif
Mar 20 00:37:25 DJsPi-Flat server.js[587677]: ~tmp-scan-0-0033.tif , {"encoding":"binary","shell":true,"maxBuffer":16384,"ignoreErrors":false,"cwd":"data/temp"}
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: [2022-03-19T23:38:17.137Z] ERROR (Http): Error: convert @- -quality 75 tmp-%04d.jpg && ls tmp-*.jpg exited with code: 1, stderr: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0019.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0020.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0021.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0022.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0023.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0024.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0025.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0026.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0027.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0028.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0029.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0030.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0031.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0032.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]: convert-im6.q16: cache resources exhausted `~tmp-scan-0-0033.tif' @ error/cache.c/OpenPixelCache/4083.
Mar 20 00:38:17 DJsPi-Flat server.js[587677]:     at ChildProcess.<anonymous> (/var/www/scanservjs/server/process.js:54:18)
Mar 20 00:38:17 DJsPi-Flat server.js[587677]:     at ChildProcess.emit (events.js:400:28)
Mar 20 00:38:17 DJsPi-Flat server.js[587677]:     at maybeClose (internal/child_process.js:1058:16)
Mar 20 00:38:17 DJsPi-Flat server.js[587677]:     at Socket.<anonymous> (internal/child_process.js:443:11)
Mar 20 00:38:17 DJsPi-Flat server.js[587677]:     at Socket.emit (events.js:400:28)
Mar 20 00:38:17 DJsPi-Flat server.js[587677]:     at Pipe.<anonymous> (net.js:686:12)```
</details>

This corresponds exactly to: https://github.com/ImageMagick/ImageMagick/issues/396 which was also referenced in #356 and #97.

The fix in #356 was only applied to docker. I'm guessing that if you run:

```sh
grep 'policy domain="resource" name="disk"' /etc/ImageMagick-6/policy.xml
```

... you'll get a result of 1GiB. If you still have the source tifs then you might be able to attempt a quick test:

```sh
# Apply fix (will require sudo or su)
sed -i 's/policy domain="resource" name="disk" value="1GiB"/policy domain="resource" name="disk" value="8GiB"'/ /etc/ImageMagick-6/policy.xml

# Retest
ls /var/www/scanservjs/data/temp \
  | convert @- -quality 75 tmp-%04d.jpg && ls tmp-*.jpg \
  | convert @- scan-0000.pdf
```

**Comment by ceskyDJ** [comment]
Thank you for the super quick fix, @sbs20!

**Comment by sbs20** [comment]
Hope it works!

**Comment by ceskyDJ** [comment]
I haven't tested it yet. I'll try it, I promise.

**Comment by ceskyDJ** [comment]
Do you know how many pages do I need to scan to cause the error?

**Comment by ceskyDJ** [comment]
I tested 33 pages (just 33 times scanned white area). Another error occurred. This is an error message (shown in the red at the bottom right corner):
> Type error: failed to fetch.

It opened the "Files" section with this error at the end of the processing. Unfortunately scanned file is missing from the list.

Here are updated logs: [scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/8328329/scanservjs.log.installed.txt.gz)

**Comment by ceskyDJ** [comment]
Update: the scanned file showed up after some time.

**Comment by sbs20** [comment]
Interesting. I'm willing to guess that the conversion and concatenation of the scans was sufficiently expensive (CPU / RAM / disk) that the UI (technically node express) timed out (fetch error), but it eventually finished.

The good news is that it ultimately worked. Although not a great UX.

I suspect that reducing the resolution would help - I vaguely recall you were scanning at 300dpi - dropping to 200 would still likely be good enough but be half the impact. Not a satisfying answer though.

I'll have a play when I get some time and see if increasing the UI timeout helps.

**Comment by ceskyDJ** [comment]
This is an extreme case - I don't scan 33 pages each day :D. But, it's not good if UI says about the error, and actually, it doesn't tell the truth. If there must be a timer (I get the reason), it's hard to solve that problem anyway. Maybe a longer timer will be the solution but it will only solve some more pages, a definite solution to this problem simply doesn't exist. At least it looks like that, doesn't it?
