### ISSUE TITLE
Request for example device.conf files

### ISSUE THREAD

**Issue by sbs20** [sbs20/scanservjs#42]
In order to improve the automatic parsing of device features and options (partly covered by #6) we need example device.conf files

Some options are represented by ranges `(0..100)` others by delimited lists `(0|25|50|75|100)`. Some contain units `(dpi|mm|bit)` others don't etc. Getting a variety of examples would help. 

Here's mine [device.conf.txt](https://github.com/sbs20/scanservjs/files/4840387/device.conf.txt)

**Comment by JnCrMx** [comment]
Mine looks like [this](https://github.com/sbs20/scanservjs/files/4840507/device.conf.txt).

But there seems to be only a limited number of possible formats you can get from ``scanimage -A`` which can be found [here](https://gitlab.com/sane-project/backends/-/blob/master/frontend/scanimage.c#L420) in its source code.

Therefore it seems like implementing a method to parse these formats (and to remove units).

But I agree that it would be nice to have more examples to make sure that they won't be unexpected exceptions or differences.

**Comment by JnCrMx** [comment]
Parsing additional information like ``(in steps of %d)`` (see https://gitlab.com/sane-project/backends/-/blob/master/frontend/scanimage.c#L467) would also be nice.

**Comment by sbs20** [comment]
It didn't occur to me to look at the source of `scanimage`. Good thinking. As you can see I've already had a go at knocking something up in the `development` branch. As it stands, the changes don't impact the working of the UI so maybe have a play with the decorate function for now. Sorry, I'm slow at responding - time is extremely limited right now!

**Comment by JnCrMx** [comment]
That code in ``development`` looks pretty good. I'll test it a bit and try to add code for parsing ``(in steps of %d)``.

And don't worry about being slow at responding, that's totally fine.
