### ISSUE TITLE
npm does not support Node.js v10.24.0

### ISSUE THREAD

**Issue by ebretteville** [sbs20/scanservjs#422]
**Describe the bug**
Can't install

**To Reproduce**

`
npm update
npm does not support Node.js v10.24.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
`

**Expected behavior**
full functionnal install

**Server (please complete the following information):**
`pi@scan-sane:~/scanservjs $ neofetch
  `.::///+:/-.        --///+//-:``    pi@scan-sane 
 `+oooooooooooo:   `+oooooooooooo:    ------------ 
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv6l 
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi Zero W Rev 1.1 
   `:oooooooo+``    `.oooooooo+-      Kernel: 5.10.63+ 
     `:++ooo/.        :+ooo+/.`       Uptime: 47 days, 22 hours, 54 mins 
        ...`  `.----.` ``..           Packages: 948 (dpkg) 
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3 
    -:::-`   .:::::::-`  `-:::-       Terminal: /dev/pts/0 
   `::.  `.--.`  `` `.---.``.::`      CPU: BCM2835 (1) @ 1.000GHz 
       .::::::::`  -::::::::` `       Memory: 43MiB / 477MiB 
 .::` .:::::::::- `::::::::::``::.
-:::` ::::::::::.  ::::::::::.`:::-                           
::::  -::::::::.   `-::::::::  ::::
-::-   .-:::-.``....``.-::-.   -::-
 .. ``       .::::::::.     `..`..
   -:::-`   -::::::::::`  .:::::`
   :::::::` -::::::::::` :::::::.
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`

`

# Node version
echo "node: $(node -v)"
`
pi@scan-sane:~/scanservjs $ echo "node: $(node -v)"
node: v10.24.0
`

# NPM version
echo "npm: $(npm -v)"
`pi@scan-sane:~/scanservjs $ echo "npm: $(npm -v)"
npm does not support Node.js v10.24.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/
/usr/local/lib/node_modules/npm/lib/npm.js:32
  #unloaded = false
  ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:22:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm: 
`

# OS version
cat /etc/*release | sed ':a;N;$!ba;s/\n/; /g'
`pi@scan-sane:~/scanservjs $ cat /etc/*release | sed ':a;N;$!ba;s/\n/; /g'
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"; NAME="Raspbian GNU/Linux"; VERSION_ID="10"; VERSION="10 (buster)"; VERSION_CODENAME=buster; ID=raspbian; ID_LIKE=debian; HOME_URL="http://www.raspbian.org/"; SUPPORT_URL="http://www.raspbian.org/RaspbianForums"; BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

**Comment by sbs20** [comment]
How did you try to install? From the one line script?

**Comment by ebretteville** [comment]
To be honest, firstly I tried to update an existing one that was working. And maybe I screwed up but then I tried the step by step, tried the one line command and also the compiled one...

**Comment by Schw3n** [comment]
Hi sbs20 and ebretteville,
I do habe the same/similar issue.

_```
_nodejs is already the newest version (19.0.1-deb-1nodesource1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nodejs : Conflicts: npm
 npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

changed 14 packages, and audited 215 packages in 10s

10 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
Backing up existing files
Restoring files
'/tmp/scanservjs.bkp/config/config.default.js' -> '/var/www/scanservjs/config/config.default.js'
'/tmp/scanservjs.bkp/data/preview/default.jpg' -> '/var/www/scanservjs/data/preview/default.jpg'
'/tmp/scanservjs.bkp/data/output' -> '/var/www/scanservjs/data/output'
'/tmp/scanservjs.bkp/data/temp' -> '/var/www/scanservjs/data/temp'
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 

added 75 packages, and audited 76 packages in 2m

1 package is looking for funding
  run `npm fund` for details

2 vulnerabilities (1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.

scanservjs installed and running
  http://127.0.0.1:8080

If you encounter problems when running, try
  sudo journalctl -e -u scanservjs
```_
pi@raspberrypi:~ $ node -v
v19.0.1
pi@raspberrypi:~ $ nodejs -v
bash: nodejs: command not found
pi@raspberrypi:~ $ npm -v
8.3.0


As I'm a total newbie, I'm totally lost.

**Comment by wjaros** [comment]
Hi! I had similar issue, switching to Debian Bullseye solved the problem.

**Comment by sbs20** [comment]
This appears to be a debian distro issue. Lots of similar reports [here](https://github.com/nodejs/help/issues/1877)

[This comment](https://github.com/nodejs/help/issues/1877#issuecomment-530152567) suggests the following:

```
curl https://www.npmjs.com/install.sh | sudo sh
```

I'm inclined not to workaround this since Buster node 10 are old now.
