### ISSUE TITLE
scanimage: open of device failed: Invalid argument

### ISSUE THREAD

**Issue by pojlFDlxCOvZ4Kg8y1l4** [sbs20/scanservjs#425]
**Describe the bug**
Red error message bottom right corner with following text when clicking on preview or scan: 
`{"message":"/usr/bin/scanimage -d 'airscan:w1:Samsung SCX-3400 Series (SEC001599B11EE2)' --mode 'Gray' --source 'Flatbed' --resolution 100 -l 0 -t 0 -x 216 -y 297 --format 'tiff' --brightness 0 --contrast 0 > data/temp/~tmp-scan-0-0001.tif > data/preview/preview.tif exited with code: 1, stderr: scanimage: open of device airscan:w1:Samsung SCX-3400 Series (SEC001599B11EE2) failed: Invalid argument\n","code":-1}`
This happens every time after a reboot or printer start, however, it will also happen if the printer hasn't scanned for a while.
After the message it will work fine.

**To Reproduce**
Use "Preview" or "scan" function after a few minutes idling

**Expected behavior**
Every single time a working scan or preview, no error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/42654642/162640700-81e8afcc-b1bc-4b6e-ac71-3699ffaf8669.png)

**Client (please complete the following information):**
 - Browser Firefox 99.0 (64-bit)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Node version v10.19.0
 - NPM version 8.3.0
 - Docker version N/A

**Logs**
 - Please include application logs (see commands below)
 
This may be useful
```sh
# Node version
echo "node: $(node -v)"
node: v12.22.12

# NPM version
echo "npm: $(npm -v)"
npm: 8.3.0

# Docker version
echo "docker: $(docker -v)"
N/A

# OS version
cat /etc/*release | sed ':a;N;$!ba;s/\n/; /g'
DISTRIB_ID=Ubuntu; DISTRIB_RELEASE=20.04; DISTRIB_CODENAME=focal; DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"; NAME="Ubuntu"; VERSION="20.04.4 LTS (Focal Fossa)"; ID=ubuntu; ID_LIKE=debian; PRETTY_NAME="Ubuntu 20.04.4 LTS"; VERSION_ID="20.04"; HOME_URL="https://www.ubuntu.com/"; SUPPORT_URL="https://help.ubuntu.com/"; BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"; PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"; VERSION_CODENAME=focal; UBUNTU_CODENAME=focal
```
# Logs if installed manually
sudo journalctl -u scanservjs | gzip > scanservjs.log.installed.txt.gz
[scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/8460052/scanservjs.log.installed.txt.gz)

# Logs if in docker
docker logs scanservjs-container > scanservjs.log.docker.txt
N/A

# system information
{
  "os": {
    "arch": "x64",
    "freemem": 1573,
    "platform": "linux",
    "release": "5.4.0-107-generic",
    "type": "Linux",
    "version": "#121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022"
  },
  "node": "v12.22.12",
  "npm": "8.3.0",
  "docker": false
}
```
**Additional context**
Add any other context about the problem here.
Seems to be related to issue 417

Running the commands from command line show the same results as in the web UI. First time after idling "invalid argument", then right after it works.

/usr/bin/scanimage -d 'airscan:w1:Samsung SCX-3400 Series (SEC001599B11EE2)' --mode 'Gray' --source 'Flatbed' --resolution 100 -l 0 -t 0 -x 216 -y 297 --format 'tiff' --brightness 0 --contrast 0 > data/temp/~tmp-scan-0-0001.tif
scanimage: open of device airscan:w1:Samsung SCX-3400 Series (SEC001599B11EE2) failed: Invalid argument 
^first time
/usr/bin/scanimage -d 'airscan:w1:Samsung SCX-3400 Series (SEC001599B11EE2)' --mode 'Gray' --source 'Flatbed' --resolution 100 -l 0 -t 0 -x 216 -y 297 --format 'tiff' --brightness 0 --contrast 0 > data/temp/~tmp-scan-0-0001.tif
^second time, no error, file output is fine.
```

Printer is a Samsung SCX-3405W over Wi-Fi. 
Printing with CUPS is done from the same machine that hosts scanserv-js does not experience the same issue.
CUPS version 2.3.1.

Printer firmware overview:
![image](https://user-images.githubusercontent.com/42654642/162642662-b5529001-fa3c-4f3d-bdae-6f50223efcb5.png)

**Comment by sbs20** [comment]
I've experienced this too. It is most unsatisfactory.

My difficulty is:

> Running the commands from command line show the same results as in the web UI. First time after idling "invalid argument", then right after it works.

I'll see if I can reliably reproduce it - I may have to adopt a brute force strategy of making a second attempt if we see that error message.

**Comment by sbs20** [comment]
As noted in #501, it seems the problem here is that `Invalid argument` is just a generic error message. Automatically retrying would result in automatically retrying even with other errors, which would end up being really annoying.

I always attempt to workaround external issues, but sometimes there's no simple way.

I'm going to close this.
