### ISSUE TITLE
Endpoint for deleting files works for files outside the data/ directory

### ISSUE THREAD

**Issue by JnCrMx** [sbs20/scanservjs#43]
It is possible to send a (custom) ``DELETE`` request for a file outside the ``data/`` directory:

![test](https://user-images.githubusercontent.com/34038939/85928596-69f97d80-b8ae-11ea-96f7-a9b39787fd58.png)

Since the server is usually running as an extra user that shouldn't be too much of an issue on a "normal" system (there are hardly any files which can be deleted just by being in ``users``), but if the system is configurated badly this might cause some harm.

**Comment by sbs20** [comment]
I've implemented a partial fix for this - it can still delete outside the data directory, but it can't go outside of the app directory.
