### ISSUE TITLE
Feature?: Allow setting a default batch mode and format

### ISSUE THREAD

**Issue by LeoKlaus** [sbs20/scanservjs#434]
Using config.local.js, it's possible to change the defaults for most (all?) device settings but batch mode and format

Is it possible to set a default batch mode and format (globally or per scanner)?

**Comment by tefracky** [comment]
Did you find a solution? I think, this is also valid for the filters, since I didn't figured out how to set default filters.

**Comment by LeoKlaus** [comment]
> Did you find a solution? I think, this is also valid for the filters, since I didn't figured out how to set default filters.

I quickly glanced over parts of the code yesterday and I don't think there's a way to change the defaults as it is right now.

My understanding is that at least parts of the batch scanning and all of the filters are implemented through scanservjs and are not native parts of SANE. 
The device features are determined by the output of
scanimage -A
so at least for filters, there's no way for them to appear in there (please correct me if I'm wrong).

So the default way of setting defaults (through the devices part of config.local.js) can't be used to set defaults for filters or batch scanning.

There may be a way to set defaults for scanservjs itself that enable changing these, but they're not documented.

**Comment by sbs20** [comment]
Hi. Neither batch nor filters support defined defaults at present - although previous choices should be stored in local browser storage.

I've had a quick look at the code and it wouldn't be too hard to implement (though quite when I'd get around to it is another matter).

I think the question is: is this a global setting or per device?

I can see a case where your default batch mode is per device - one might be a flatbed, the other a sheet feeder. Filters could go either way. Do either of you have any thoughts on a preference?

**Comment by LeoKlaus** [comment]
> Hi. Neither batch nor filters support defined defaults at present - although previous choices should be stored in local browser storage.
> 
> I've had a quick look at the code and it wouldn't be too hard to implement (though quite when I'd get around to it is another matter).
> 
> I think the question is: is this a global setting or per device?
> 
> I can see a case where your default batch mode is per device - one might be a flatbed, the other a sheet feeder. Filters could go either way. Do either of you have any thoughts on a preference?

I think batch mode should definitely be per device, as different devices support different modes.

For filters I also think a per device setting would be more appropriate, same goes for format.

My use case for example includes two scanners, one low end one with an ADF I use for documents and a higher end flatbed one for negatives and photos. 

It wouldn't make sense to apply the threshold filter to photos and save them as OCRd PDFs, whereas those would be sensible defaults for the document scanner.

I think most people won't have enough scanners to make setting defaults for each a hassle.

**Comment by sbs20** [comment]
I am inclined to agree. Further, having all this information in one place simplifies the implementation.

I'll add it to the list.

Thanks for raising the issue!

**Comment by LeoKlaus** [comment]
Great! Thanks for developing quality free, open source software!
