### ISSUE TITLE
Tesseract: support all localised languages

### ISSUE THREAD

**Issue by LeoKlaus** [sbs20/scanservjs#435]
**Describe the bug**
Using any environment value but 'eng' for OCR_LANG will result in all OCR scans failing when using the Docker image.

**To Reproduce**
1. Pull and start the container with the environment variable "OCR_LANG" set to any language from the supported languages list (i.e. 'deu'). 
2. Try scanning a file with any of the OCR format presets

**Expected behavior**
OCR should work with the language selected.

**Server (please complete the following information):**
Docker image sbs20/scanservjs 

**Additional context**
This should be pretty easy to fix.
Adding something like
`tesseract-ocr-$OCR_LANG \`
to the apt-get install part of the DOCKERFILE (if this is how it works, not a Docker pro) should suffice.

**Comment by sbs20** [comment]
Good point. I am keen to support this kind of thing. I'm not sure of the best solution, though - the `apt-get` runs at build time rather than run time so it may require adding all languages. I wonder if it's possible to link an outside (host) OCR definition / config to the container through a volume. Any thoughts / research welcome!

**Comment by LeoKlaus** [comment]
> the `apt-get` runs at build time rather than run time

That's what I thought.
 
Paperless-ng(x) for example comes with the biggest languages preinstalled (Englisch, German, French, Spanish and Italian), that's one way to cover a big chunk of users with very little effort (the language data itself seems to be about 1.5MB per language).

Including all languages is possible, but would likely increase both build time and image size considerably.

A tesseract language is stored in a single file called `[language].traineddata` I've just tested mounting that file in the container from my host machine and that works. In my case I just downloaded the .deb from https://packages.debian.org/de/sid/tesseract-ocr-deu
and mounted 'deu.traineddata' at `/usr/share/tesseract-ocr/4.00/tessdata/deu.traineddata`

It's not super elegant, as that would require the user to obtain the file for their preferred language themselves and store it on the host machine. It could also introduce issues with tesseract if a version mismatch occurs (I don't know how tesseract would handle that).

Maybe a mix of both would be a good solution? I.e. pre installing the 5-10 most spoken languages and expanding the documentation to explain how to install other languages?

**Comment by sbs20** [comment]
How about doing [these languages](https://github.com/sbs20/scanservjs/tree/master/packages/client/src/locales) and putting them below [this line](https://github.com/sbs20/scanservjs/blob/49b8a3383511afb7ecf07b792ee83b6f1f7cb8ad/Dockerfile#L30). That would likely cover the majority of users of the software.

If you're up doing a PR, I'll happily merge it in.

Sorry for the almost laughably slow response.
