### ISSUE TITLE
jpg conversion fails for large count due to memory constraint

### ISSUE THREAD

**Issue by phiresky** [sbs20/scanservjs#437]
**Describe the bug**
If I scan ~3 pages, it works fine. If i scan 6+ pages, it failes because the `convert` process is killed by the OOM killer. It seems like `convert @~` tries to load all TIF files into memory at once? My raspberry PI only has 1GB of ram.

**To Reproduce**
1. Use a memory constrained system (raspberry pi)
2. scan many pages at once

**Comment by sbs20** [comment]
Is this related to #414?

Does the memory seeing need to be reduced further?

**Comment by phiresky** [comment]
I don't think it's related to an imagemagick policy, it's the kernel killing it:

![image](https://user-images.githubusercontent.com/2303841/172054825-c6825836-019c-4698-9b9f-396482a1669c.png)

**Comment by phiresky** [comment]
Not sure why imagemagick loads all files to memory first. Maybe the script could be replaced with `for f in *.tif; do convert $f .....; done`?

**Comment by sbs20** [comment]
Doesn't the policy dictate how much RAM is used before using virtual memory though? Is it worth giving it a quick try? 

You can change the script yourself if you want - add your own pipeline

**Comment by phiresky** [comment]
I'm not 100% sure, but checking /etc/Imagemagick*/policy.xml and using `identify -limit memory 8000MiB -list resource` seems like I don't have a memory limit configured anyways (Arch Linux, not using the docker container)

**Comment by sbs20** [comment]
Try setting it to 512mb or something low. I just googled `imagemagick oom killer` and it turned up lots of possible options.

I wonder if the arch install is out of date - there should be a limit.

**Comment by phiresky** [comment]
> I wonder if the arch install is out of date - there should be a limit.

I just checked it and actually archlinux just uses the upstream files exactly without modification. Other distros like debian intentionally set their own limits (different from upstream) https://wiki.debian.org/imagemagick/security

**Comment by sbs20** [comment]
Sorry, I mean the install of scanservis - it should modify the imagemagick policy.

**Comment by phiresky** [comment]
Ah. I'm using the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=scanservjs) which probably completely ignores your installer. I should probably have mentioned that at the top, sorry.

**Comment by sbs20** [comment]
😄 

Please try the fix in the issue mentioned.

**Comment by phiresky** [comment]
I set it to 256MB and now imagemagick segfaulted without a message ಠ_ಠ

**Comment by sbs20** [comment]
The commit that fixed this was here: https://github.com/sbs20/scanservjs/commit/ef149cf4e9af26a7479c705860040bb0979d5fbd

Try this one liner:

```sh
sed -i 's/policy domain="resource" name="disk" value="1GiB"/policy domain="resource" name="disk" value="8GiB"'/ /etc/ImageMagick-6/policy.xml
```

I'm going to close this in the mean time since time has passed. If you still have a problem with it, just add a comment and I'll gladly reopen.
