### ISSUE TITLE
lineart & scanimage: attempted to set inactive option contrast

### ISSUE THREAD

**Issue by wainy54** [sbs20/scanservjs#439]
Similar issue to #61 
device `plustek:libusb:005:002' is a Canon CanoScan N1240U/LiDE30 flatbed scanner

When attempting to perform a scan in 'Lineart' mode, the following error is received.
`{"message":"/usr/bin/scanimage -d 'plustek:libusb:005:002' --mode 'Lineart' --resolution 50 -l 0 -t 0 -x 103 -y 76.2 --format 'tiff' --brightness 0 --contrast 0 > data/temp/~tmp-scan-0-0001.tif exited with code: 1, stderr: scanimage: attempted to set inactive option contrast\n","code":-1}`

The issue isn't replicated in 'Color' or 'Gray' modes.

Running 'scanimage -d 'plustek:libusb:005:002' -A' doesn't show contrast as inactive, but I'm guessing that it is just specifically for lineart.

If I run the following command (without the contrast option), it scans as expected:
`scanimage -d 'plustek:libusb:005:002' --mode 'Lineart' --resolution 50 -l 0 -t 0 -x 103 -y 76.2 --format 'tiff' --brightness 0 > data/temp/~tmp-scan-0-0001.tif`

I attempted to override the contrast setting, but this seems to be global rather than by mode (gray/color/lineart).

**Comment by sbs20** [comment]
I have a very similar scanner - and yet I never tested this. What an annoying "feature"!

The fix is a bit hacky since the modes are not fixed, but backend dependent. But I've fixed it for similar Canon scanners.

Thanks for raising.
