### ISSUE TITLE
Switch between Duplex and Simplex 

### ISSUE THREAD

**Issue by fastlane086** [sbs20/scanservjs#440]
**Describe the bug**
I added following code to my config.local.js [Add custom scanimage command line options](https://github.com/sbs20/scanservjs/blob/master/docs/config.md#add-custom-scanimage-command-line-options), because with the dropdown field "batch" my printer/scanner does not react on the entries, so he does not do an automatical duplex scan only simplex. I have an Epson WF-3520. 
Now it's the problem, if i want to scan a document simplex (because it has only one-sided print) he makes everytime a duplex scan.

**Expected behavior**
I thought with the dropdown-field batch i can overwrite the batch in the config, but it does not work.

**Client:**
 - Browser Firefox
 - Version 101.0.1

**Server:**
 - OS: DSM 7.1-42661 update 2
 - Node version 12.22.7-2029
 - NPM version 6.14.15
 - Docker version 20.10.3-1306

**Additional context**
I thought about a few options to solve the problem.

1. Add a custom batch field where you can enter your own custom settings for each scan. Maybe add the custom batch in the config file and you can choose it in a dropdown field. Maybe in some profiles with own names so you can choose if you want to scan a single page or a 2-sided page.

2. This option makes in my head sense, the batch can read out the printer name (example on my printer is it epson2) and declarate behind the printer names the custom scanimage command line and the batch (dropdown-field) from autofeed takes the right one for the printer.

**Comment by sbs20** [comment]
Sorry for such a slow reply. This feature is already there - at least as I understand the issue you've raised. I'm going to close this, but if I have misunderstood then please feel free to comment.

### Duplex

Select `Batch: Auto (Collate...)`

This will ask you to scan all the odd pages first. When the document feeder reaches the end, you will be prompted to turn the documents over and then you scan all the even pages. The pages are then interleaved and joined together.

### Simplex

Just choose `Batch: Auto (Document feeder)`
