### ISSUE TITLE
cutsom outputDirectory for pipeline

### ISSUE THREAD

**Issue by Raabi91** [sbs20/scanservjs#441]
is it possible to use a cutsom outputDirectory for pipeline. 

so in the sense of e.g. jpg into the folder jpg and pdf then into the pdf folder. 

only that you can specify the folder in the pipline

**Comment by sbs20** [comment]
No. This isn't possible within the normal flow - there is one (configurable) output directory.

You could experiment with the pipelines (they're just shell scripts) but I'm not really inclined to add this as a feature.
