### ISSUE TITLE
convert: Read error on strip 390; got 0 bytes, expected 7632.

### ISSUE THREAD

**Issue by SydneyOwl** [sbs20/scanservjs#445]
I got this when trying to scan in colour mode. Color image can still be displayed after I refreshed the page although there's an error. When working in gray mode, it does not have any problem.
Scanner: M1136 MFP
Platform: Raspberry pi Zero W, armv6l, Debian 11
Error message:
```json
{"message":"/usr/bin/convert 'data/temp/~tmp-scan-0-0001.tif' -scale 868 -background '#808080' -extent '868x1532-0-0' 'data/preview/preview.tif' exited with code: 1, stderr: convert: Bogus \"StripByteCounts\" field, ignoring and calculating from imagelength. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/985.\nconvert: Read error on strip 390; got 0 bytes, expected 7632. `TIFFFillStrip' @ error/tiff.c/TIFFErrors/606.\n","code":-1}
```
Detail in journalctl:
```
Aug 04 14:52:19 raspberrypi server.js[694]: [2022-08-04T06:52:19.557Z] DEBUG (Scan): Post processing: PDF (JPG | @:pipeline.high-quality)
Aug 04 14:52:19 raspberrypi server.js[694]: [2022-08-04T06:52:19.577Z] DEBUG (Process): /usr/bin/convert 'data/temp/~tmp-scan-0-0001.tif' -s>
Aug 04 14:52:23 raspberrypi server.js[694]: [2022-08-04T06:52:23.397Z] ERROR (Http): Error: /usr/bin/convert 'data/temp/~tmp-scan-0-0001.tif>
Aug 04 14:52:23 raspberrypi server.js[694]: convert: Read error on strip 390; got 0 bytes, expected 7632. `TIFFFillStrip' @ error/tiff.c/TIF>
Aug 04 14:52:23 raspberrypi server.js[694]:     at ChildProcess.<anonymous> (/var/www/scanservjs/server/process.js:54:18)
Aug 04 14:52:23 raspberrypi server.js[694]:     at ChildProcess.emit (events.js:314:20)
Aug 04 14:52:23 raspberrypi server.js[694]:     at maybeClose (internal/child_process.js:1022:16)
Aug 04 14:52:23 raspberrypi server.js[694]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by SydneyOwl** [comment]
I just discovered #406 is exactly the same issue, which is solved by using a python script. It is a good solution, but I wonder if there's another way to deal with it without python environment installed?

**Comment by AcademicDog** [comment]
same problem
M1136
Raspberry pi 4B

![2](https://user-images.githubusercontent.com/21212008/184076567-b9c42045-8f32-413b-90d9-87a99838615c.png)

**Comment by AcademicDog** [comment]
1: new HP-MARVELL-SCAN channel=21 clientCnt=1 channelCnt=1
7: Found interface conf=0, iface=2, altset=0, index=7
9: Active kernel driver on interface=2 ret=0
5: claimed ff/ff/ff interface
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a
 unable to read  data size=519120 hp:/usb/HP_LaserJet_Professional_M1136_MFP?serial=000000000QHBLEGVPR1a

**Comment by SydneyOwl** [comment]
well....I think this problem occurs only on specified scanners.
After trying installing scanservjs to multiple platforms and linux distributions like armbian and ubuntu, the result is still the same. I even tried pulling images from dockerhub but it does not work as well, which proves it is not related to host devices or platform we are using.
All in all, this project is great. Thank you for sharing this with us!
