### ISSUE TITLE
Add save folder selection under setting

### ISSUE THREAD

**Issue by MX10-AC2N** [sbs20/scanservjs#447]
Hi @sbs20 
First of all I would like to thank you very much for this great tool!
Now I open a topic, just to see if it is easily possible to change the location of the "output" folder
I would like to be able to choose it directly from the web interface and thus choose where I save the file and name it.

My problem is that once installed Scanservjs saves the scanned file in `/var/www/scanservjs/data/output/` but I would prefer to have the scans directly on my hard drive, my system runs on zimaboard on a 32G Emmc so I prefer to move the "output" folder, for the moment I haven't succeeded in doing what I wanted to do, so if you have a solution I'm interested. But a small update with the selection of the backup folder in the settings of scanservjs would be welcome too. ;-)
Thanks again.

Translated with www.DeepL.com/Translator (free version)

**Comment by sbs20** [comment]
Hi. You can change the output folder but not in the UI. You need to add a local config: https://github.com/sbs20/scanservjs/blob/master/docs/config.md

Then override the following two variables:

```javascript
config.allowUnsafePaths = true;
config.outputDirectory = '/path/to/dir';
```

Please note that allowing unsafe paths does compromise security somewhat.

Also, you will need to grant write permissions for the `scanservjs` user on your chosen directory.

**Comment by Basti600** [comment]
Unfortunately, the two links no longer work. Where can I change the output directory?
