### ISSUE TITLE
Scan fails on multi-page jobs

### ISSUE THREAD

**Issue by Samuelellis** [sbs20/scanservjs#452]
**Describe the bug**
Good afternoon

I have a strange bug that someone can help with. it is setup and it works fine for scans that are one or two pages long and will scan fine until it gets to over 6 pages and then randomly fail. 

The scanner in question is a HP Officejet 7510 AIO and this is installed on a Fresh version of Ubuntu 22.04

**To Reproduce** - Flatbed
Steps to reproduce the behaviour:
1. Go to 'Main landing page
2. Click on Source, select flatbed
3. Set resolution to 100 or 200
4. Click on Mode, select colour
5. Click patch select manual with prompt
6. Select any format
7. Ser paper size to A4
9. This fails and the error is in the log line 994 - please see the attached .gz file for the log

**Expected behaviour**

**Client (please complete the following information):**
 - Firefox
 - Version 103.0.1

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Node version12.22.9
 - NPM version 8.3.0
 - Docker version Not applicable

[scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/9746653/scanservjs.log.installed.txt.gz)

**Comment by Samuelellis** [comment]
Hi, just to add more information to this I attempted a multi-page scan using the Auto document feeder as well

I can see in the log file when it got to the late page (page 12 in this instance) it came up with the error 


Oct 11 15:50:55 scanner server.js[902]: cannot rename data/temp/~tmp-scan-1-0012.tif.part to data/temp/~tmp-scan-1-0012.tif
Oct 11 15:50:55 scanner server.js[902]:     at ChildProcess.<anonymous> (/var/www/scanservjs/server/process.js:54:18)
Oct 11 15:50:55 scanner server.js[902]:     at ChildProcess.emit (events.js:314:20)
Oct 11 15:50:55 scanner server.js[902]:     at maybeClose (internal/child_process.js:1022:16)
Oct 11 15:50:55 scanner server.js[902]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
Oct 11 15:51:01 scanner server.js[902]: [2022-10-11T14:51:01.187Z] DEBUG (Http): request:  { method: 'GET', path: '/files' }



I was watching the system while it was doing this as my first thought was disk space but it did not fill the disk and was not using a lot of CPU/RAM resource when doing this. it also seemed to be able to rename all the files before this one correctly

**Comment by sbs20** [comment]
Hi. I've had a quick look at the logs and the error is essentially:

```
Oct 07 11:56:31 scanner server.js[930]: [2022-10-07T10:56:31.626Z] ERROR (Http): Error: /usr/bin/scanimage -d 'airscan:e0:HP OfficeJet 7510 series [596445] (USB)' --mode 'Color' --source 'Flatbed' --resolution 200 -l 0 -t 0 -x 210 -y 297 --format 'tiff' --brightness 0 --contrast 0 > data/temp/~tmp-scan-0-0010.tif exited with code: 1, stderr: scanimage: open of device airscan:e0:HP OfficeJet 7510 series [596445] (USB) failed: Invalid argument
```

or the important bit

```
exited with code: 1, stderr: scanimage: open of device airscan:e0:HP OfficeJet 7510 series [596445] (USB) failed: Invalid argument
```

My guess is that there is something flaky about the driver - which is a very unsatisfactory answer.

There's not really anything the scanservjs can do - it's asking `scanimage` to do a scan, which it attempts and then fails. Searching `scanimage open of device failed invalid argument` isn't massively helpful but that's where I would dig.

I think it's an intermittent "scanner" (driver) issue which you're more likely to see on a multipage scan because it's being used more.

**Comment by sbs20** [comment]
I'm closing this because I think it's a sane issue.
