### ISSUE TITLE
[Feature Request] Single page from multiple scans

### ISSUE THREAD

**Issue by lewisbolaton** [sbs20/scanservjs#453]
**Use case:** There are some instances when the area of a scanner, specifically a flatbed, is not enough for a certain paper size. For example, I have a scanner which could accommodate papers of sizes A4 and US Letter. Thus, the overall height and width of my scanner is 216mm (width of US Letter) and 297mm (height of A4) respectively. However, I also usually encounter documents of sizes US Legal (8.5x14in) and Government Legal (8.5x13in).

What I currently do now to scan these longer than usual documents is to first scan the top part of the page then the bottom part afterwards. From there, I merge these two scans using GIMP then export it as usual. So for example, if I have a paper of size 8.5x13 in, would first set the scan size to 8.5x6.5in then scan the top part. Thereafter, I'll rotate my document so that the bottom-right corner of my page is placed on the top-right corner of my scanner. These two 8.5x6.5in documents are merged together in GIMP to form the whole 8.5x13in document. Note that the second scan is flipped both horizontally and vertically since it was scanned upside-down.

Is it maybe possible to integrate this feature here? Maybe we could add another option on Batch for this.

**Comment by sbs20** [comment]
Hi thanks for suggesting the feature.

I think the complexity of attempting to merge two images together reliably is beyond the scope of this project. It will be best done in GIMP or your editor of choice.
