### ISSUE TITLE
Allow in settings not redirect to files page after each scan 

### ISSUE THREAD

**Issue by shady2k** [sbs20/scanservjs#470]
**Describe the bug**
After scan page switches to files automatically.

**To Reproduce**
1. Scan page
2. After scan page changes to files automatically

**Expected behavior**
Option 1: do not redirect to files page automatically after scan
Option 2: add to settings page flag to not redirect to file page after scan

**Additional context**
I scan multiple documents in a row, and I don't want to switch page to scan each time, it is very annoying.

**Comment by shady2k** [comment]
Thank you for a great application!

**Comment by sbs20** [comment]
Yeah, fair point. I sometimes find it annoying too.
