### ISSUE TITLE
How to set a basic http auth?

### ISSUE THREAD

**Issue by Stewie3112** [sbs20/scanservjs#471]
Hi, as per title, I'd like to have at least a basic auth, I don't care about the scanner itself, but without this function all the scanned files inside the shared folder are available network-wide.
Is there something already built in or I should go the reverse proxy way?

In case nr 2 do you have any guide to set it up?

Thanks for this great project!

**Comment by sbs20** [comment]
No, but I've just added it. Not yet released.

It will be possible to do it with a proxy too. Implementation will depend on which proxy. [nginx example](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)

**Comment by Stewie3112** [comment]
Oh great, I'll try in the meantime the ngix way, please update this issue when the new version is released!
