### ISSUE TITLE
Integration: docs question / remark 

### ISSUE THREAD

**Issue by torwag** [sbs20/scanservjs#478]
Reading the integration part and the idea of using rclone for sync the given example is:
```
config.pipelines.push({
  extension: 'pdf',
  description: 'PDF | Scan2Cloud ⇒ Your_Configured_Provider_or_Remote' ,
  get commands() {
    return [
      'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg',
      'convert @- pdf:-',
      `rclone copy *.pdf YOUR_PROVIDER:/path/to/folder`,
      'ls scan_*.*'
    ];
  }
});
```
I believe I understood the pipeline system via the shell piping.  However I don't get the very last command. 
At no point files with a prefix `scan_` seems to be generated.  So if this is the last pipeline,  what actually gets saved? Other examples,  which describes the pipeline system create a file with that prefix at one point and as I understood, the line  `ls scan_*.*` at the end reads like. "Push that particular files to the next routine, or if there is no routine anymore, keep that files saved (move them to the output folder?) ,  but delete all raw and intermediate files in tmp". 

In addtition from the docs related to the pipeline system,  it is hard for me to understand how to arrange a certain order for multiple routines. 
I also have trouble to understand if there are standard routines at the beginning or the end of the pipeline and if so, how to modify and rearrange them. E.g. Copy the final files from tmp to the output folder,  is always done, if a filelist is provided at the end?

**Comment by torwag** [comment]
Ok, reading and testing more,  I get more and more confused ;)

So I implemented the above example to provide a sync to an external SFTP folder.
I noticed that I have now the possibility to select PDF | Scan2Cloud under "Format" on the Frontend.
However, does that mean that the above code is only executed if this format is selected?
Are all other Formats "hardcoded" or could they be adjusted in the same manner?
Does that mean there is only one pipeline per format? Then I do not get the pipeline idea of the manual.
Are there ways of branching and merging command blocks? 
I still missing somehow how do I compile different command blocks into a pipeline.

E.g. I define 4 blocks
1. Post-processing and create PDF
2. Send to Server A via rclone 
3. Send to Server B via API call
4. Store PDF locally as Backup

Now I want to have two "Formats"
1. Scan2ServerA
2. Scan2ServerB

whereas:
Scan2ServerA should execute the pipeline 1->2->4
Scan2ServerB should execute the pipeline 1->3->4

I don't yet see how to do this. According to the docs, I have only one place (the config) to manage the pipeline and there seems to be no way to arrange the order or the way command blocks are arranged in the pipeline order, nor how I assign them to a particular format.

**Comment by sbs20** [comment]
The stdin for the pipeline is a list of filenames. The stdout of the last pipeline entry must also be a list of files.

For PDFs and multipage TIFs there's one element in the output. For others there's a list of, say, JPGs.

The inner parts of the app take care of moving the file out of the temp folder and into the output folder.

As you'll have seen on #479 using pipelines for this is... suboptimal.

Yes, there's one pipeline per format.

**Comment by torwag** [comment]
@sbs20 thanks for helping me. 
I still can't see how the code example from the docs makes use of this.
There are no files called scan_* in the process and yet, the last command, as you said is there to make sure that this files get copied over from tmp to output.
In my understanding, as there are no files called scan_* nothing gets copied finally?!

As for the pipeline, do I get it right, that a pipeline is basically like a function, using stdin as input parameter and expecting to provide a return value via stdout?
So there is no stacking of pipelines or anything like this. Each format gets a single pipeline. Within that different tasks can be called on the scan files and intermediate files (if generated within the pipeline). At the end the file list parsed to stdout is what gets copied over to output, whereas all the rest gets deleted.

**Comment by sbs20** [comment]
I think you're right and you've found a bug in the docs.

The filenames that are generated during the scan all start with this constant:
https://github.com/sbs20/scanservjs/blob/80c5a88614c0f67a1c6570e097f1085da6ac3e22/packages/server/src/constants.js#L7

It's used in a few places such as here:
https://github.com/sbs20/scanservjs/blob/80c5a88614c0f67a1c6570e097f1085da6ac3e22/packages/server/src/scanimage.js#L94

So what gets passed to the pipeline is the list of files starting with that constant.

Annotating the pipeline:

```javascript
    return [
      // list of files coming in...
      // they all get converted (`@-` means read the filenames from stdin) to JPGs.
      // and the converted files are named `tmp-0001.jpg`, `tmp-0002.mpg` and so on.
      // since the next command in the pipeline needs a list of files, this now lists those files, hence `ls tmp-*.jpg` 
      'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg',
      // This now reads all those tmp files and turns it into a PDF, but I think rather than save to a file, it's pushing to stdout
      'convert @- pdf:-',
      // So this line won't work
      `rclone copy *.pdf YOUR_PROVIDER:/path/to/folder`,
      // And this line doesn't make sense.
      'ls scan_*.*'
    ];
```

I have a feeling it was copied and pasted from here:
https://github.com/sbs20/scanservjs/blob/80c5a88614c0f67a1c6570e097f1085da6ac3e22/docs/config.md?plain=1#L56

My guess, is it should be something more like this:
```javascript
    return [
      'convert @- -quality 92 tmp-%04d.jpg && ls tmp-*.jpg',
      'convert @- scan-0000.pdf',
      `rclone copy scan-0000.pdf YOUR_PROVIDER:/path/to/folder`,
      'ls scan-*.*'
    ];
```

**Comment by sbs20** [comment]
Also see #483 - this is a better place to do your SFTP sync
