### ISSUE TITLE
Muliple Page PDF scan

### ISSUE THREAD

**Issue by MrksHfmn** [sbs20/scanservjs#48]
I would like to scan several pages and merge them into one PDF

**Comment by JnCrMx** [comment]
I've started working on this at https://github.com/JnCrMx/scanservjs/tree/multiple-pages and https://github.com/JnCrMx/scanservjs/tree/tesseract-ocr (for OCR with Tesseract).

The current solution isn't perfect (ONLY USE IT FOR PRIVATE SYSTEMS; there is a bug that could allow read access to any file accessable for the process), but you might consider having a look at it.

I'd appreciate any tests, bug reports, suggestions or pull requests a lot. :)

**Comment by sbs20** [comment]
Closed. See new references.
