### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by MX10-AC2N** [sbs20/scanservjs#489]
Hi @sbs20 
I use scanservjs and it's a great tool for me. Thank a lot for this...
I use it with the normal install but now I prefer to use the docker version so I need to uninstall but I can't find how do this.
There is a one line code for uninstall ?
Thank again...

**Comment by sbs20** [comment]
Hello!

Yes. Just run `sudo ./INSTALL_DIR/installer.sh -u`.

* You need to run with root privileges - hence `sudo`.
* When you run with no arguments, it will just [print the help](https://github.com/sbs20/scanservjs/blob/e4ce5f0de13a23c3050ddd7e58dedb790c9fa4d4/packages/server/installer.sh#L188).
* You can read the script to see what it does.
* There are actually two uninstall options `-u` (safe and fine) and `--force-uninstall`, which will also remove dependencies, which is a bit more risky. Again, see the script source to decide for yourself.

Hope that helps.

**Comment by MX10-AC2N** [comment]
I was thinking of making an app request for your docker install in CasaOs do you agree ? https://github.com/IceWhaleTech/CasaOS
It also would be nice to add an icon for the app ScanServJS...
Thank again and have a nice day.

**Comment by MX10-AC2N** [comment]
@sbs20 
Thanks, I was able to switch to a docker install.
I had to install the Brother proprietary driver in the docker, so the next time I update I'll lose this driver. How can I make sure that during an update there is also the installation of the Brother driver that is also done.
I can't use dockerfile with CasaOS but only docker-compose. Could you give me an example, thanks in advance.

**Comment by sbs20** [comment]
> @sbs20 Thanks, I was able to switch to a docker install. I had to install the Brother proprietary driver in the docker, so the next time I update I'll lose this driver. How can I make sure that during an update there is also the installation of the Brother driver that is also done. I can't use dockerfile with CasaOS but only docker-compose. Could you give me an example, thanks in advance.

Your two options are:

* Create your own docker image. There is an example how [here](https://github.com/sbs20/scanservjs/blob/f7b0d75f8c5361be9b55c7a1c8f042cf24c01e10/Dockerfile#L116)
* You install the backend drivers on a host somewhere and use SANE over the network instead.

**Comment by sbs20** [comment]
> I was thinking of making an app request for your docker install in CasaOs do you agree ? https://github.com/IceWhaleTech/CasaOS It also would be nice to add an icon for the app ScanServJS... Thank again @sbs20 and have a nice day.

You can. I'm afraid I won't be able to support it in any way, though. I already struggle to keep up!

**Comment by ebretteville** [comment]
As uninstalling, what about a documentation on how to safely update when there's a release? Anyway, thanks for the work you're doing and sharing.

**Comment by MX10-AC2N** [comment]
@sbs20 
App request on casaos => https://github.com/IceWhaleTech/CasaOS/issues/754 
Thank again.
