### ISSUE TITLE
No duplex scanning option available (Epson Workforce WF-7620)

### ISSUE THREAD

**Issue by torwag** [sbs20/scanservjs#494]
**Describe the bug**
Installed scanservjs on a Rpi and connected the S1500 via USB. I can scan simplex but do not see any options to scan duplex.

**Client (please complete the following information):**
 - Firefox, Chromium

**Server (please complete the following information):**
 - Rasbian with manual install of scanservjs

I write all this out of my head, as I have no access to the device right now. But maybe we can figure out an solution or tell me what I need to provide.

**Comment by torwag** [comment]
I am sorry I mixed up the scanners. It seems it works for the SnapScan S1500 but not for the Epson Workforce 

Entr of the Epson Printer/Scanner in devices.json

` "\nAll options specific to device `epson2:net:192.168.1.141':\n  Scan Mode:\n    --mode Lineart|Gray|Color [Lineart]\n        Selects the scan mode (e.g., lineart, monochrome, or color).\n    --depth 8bit [inactive]\n        Number of bits per sample, typical values are 1 for \"line-art\" and 8\n        for multibit scans.\n    --halftoning None|Halftone A (Hard Tone)|Halftone B (Soft Tone)|Halftone C (Net Screen)|Dither A (4x4 Bayer)|Dither B (4x4 Spiral)|Dither C (4x4 Net Screen)|Dither D (8x4 Net Screen)|Text Enhanced Technology|Download pattern A|Download pattern B [inactive]\n        Selects the halftone.\n    --dropout None|Red|Green|Blue [None]\n        Selects the dropout.\n    --brightness 0..0 [inactive]\n        Selects the brightness.\n    --sharpness -2..2 [inactive]\n        \n    --gamma-correction User defined (Gamma=1.0)|User defined (Gamma=1.8) [User defined (Gamma=1.8)]\n        Selects the gamma correction value from a list of pre-defined devices\n        or the user defined table, which can be downloaded to the scanner\n    --color-correction None|Built in CCT profile|User defined CCT profile [inactive]\n        Sets the color correction table for the selected output device.\n    --resolution 75|100|150|300|600|1200dpi [75]\n        Sets the resolution of the scanned image.\n    --threshold 0..255 [128]\n        Select minimum-brightness to get a white point\n  Advanced:\n    --mirror[=(yes|no)] [inactive]\n        Mirror the image.\n    --auto-area-segmentation[=(yes|no)] [inactive]\n        Enables different dithering modes in image and text areas\n    --red-gamma-table 0..255,...\n        Gamma-correction table for the red band.\n    --green-gamma-table 0..255,...\n        Gamma-correction table for the green band.\n    --blue-gamma-table 0..255,...\n        Gamma-correction table for the blue band.\n    --wait-for-button[=(yes|no)] [no]\n        After sending the scan command, wait until the button on the scanner\n        is pressed to actually start the scan process.\n  Color correction:\n    --cct-type Automatic|Reflective|Colour negatives|Monochrome negatives|Colour positives [inactive]\n        Color correction profile type\n    --cct-profile -2..2,...\n        Color correction profile data\n  Preview:\n    --preview[=(yes|no)] [no]\n        Request a preview-quality scan.\n  Geometry:\n    -l 0..297.18mm [0]\n        Top-left x position of scan area.\n    -t 0..431.8mm [0]\n        Top-left y position of scan area.\n    -x 0..297.18mm [297.18]\n        Width of scan-area.\n    -y 0..431.8mm [431.8]\n        Height of scan-area.\n  Optional equipment:\n    --source Flatbed|Automatic Document Feeder [Flatbed]\n        Selects the scan source (such as a document-feeder).\n    --auto-eject[=(yes|no)] [no]\n        Eject document after scanning\n    --film-type Positive Film|Negative Film|Positive Slide|Negative Slide [inactive]\n        \n    --focus-position Focus on glass|Focus 2.5mm above glass [inactive]\n        Sets the focus position to either the glass or 2.5mm above the glass\n    --bay 1|2|3|4|5|6 [inactive]\n        Select bay to scan\n    --eject []\n        Eject the sheet in the ADF\n    --adf-mode Simplex|Duplex [Simplex]\n        Selects the ADF mode (simplex/duplex)\n\n"`

Pretty much the last line says there should be something like duplex/simplex, but it is not available in the web interface. Selecting that scanner, I can only select ADF or flatbed in the source settings. Whereas, I can select Simplex and Duplex in the source setting for the Snapscan.

**Comment by torwag** [comment]
It seems the trouble comes form the fact that the SnapScan provides `ADF Simplex` and `Duplex` via the `--source` flag, whereas the Epson offers  `flatbed` and `ADF` for `--source` and uses `--adf-mode` to distinguish between `Simplex` and `Duplex`.
However, the `--adf-mode` is not part of the web-gui settings.

**Comment by torwag** [comment]
So I looked a bit further, but it seems there is no way yet to let users add a parameter to the Web-GUI, right? I could possibly configure the standard value but not make it selectable via the interface.

**Comment by sbs20** [comment]
Yeah, there's often so much junk in the scanimage response that it's took risky to autowire everything.

I've had a go at adding `--adf-mode` in the [iss494](https://github.com/sbs20/scanservjs/tree/iss494) branch. Is this something you're able to checkout locally, build and test?

If not, I'll give it a bit more of a scrub and see about doing a release. My fear with it is that the scanner is fussy about the argument if the source is not `ADF`

**Comment by torwag** [comment]
Hi, 
first feeback, the new parameter is selectable for the Epson and does not appear for the Fujitsu, which is desired.
A bit undesired might be that the parameter is available for both sources ADF and flatbed, where it only makes sense for the ADF unit. I believe this is an easy part for the logic to prove in addition whether ADF was selected and to skip the parameter otherwise.

In addition, the second page is turned upside down in the resulting PDF. The scanner does not really do full duplex, but passes the paper twice through the ADF unit, turning it over once. I assume that it scans on the forward path one side and on the backward path the second side.

Finally, if I get this right, I would have known to 
Select ADF or source
Select Duplex for duplex scan of the scanner
Select Document Feeder under Batch (as otherwise I only get the first page).

Do you think it makes sense somehow to simplify this? E.g. If I scan duplex, I am almost sure that it should always be document feeder under batch.
Thanks for looking into this. It is really appreciated.

**Comment by sbs20** [comment]
> A bit undesired might be that the parameter is available for both sources ADF and flatbed, where it only makes sense for the ADF unit. I believe this is an easy part for the logic to prove in addition whether ADF was selected and to skip the parameter otherwise.

It is easy except that the values returned by sane devices are completely at the whim of their developers - what might be `ADF` for one vendor might be `Automatic Document Feeder` for another. So we end up accounting for all sorts of possibilities.

> In addition, the second page is turned upside down in the resulting PDF. The scanner does not really do full duplex, but passes the paper twice through the ADF unit, turning it over once. I assume that it scans on the forward path one side and on the backward path the second side.

Alas this is, in my view, a device bug - another scanner may do this the right way round. There's no way to know except to delegate to the user who already has to navigate too many options

> Do you think it makes sense somehow to simplify this? E.g. If I scan duplex, I am almost sure that it should always be document feeder under batch.

I'd love to. The problem is that this software needs to handle all the other scanners - and this is the first time I've encountered these options in 7 years. It would be been easier had the developers of the Epsom driver offered three sources `Flatbed | ADF Simplex | ADF Duplex (with right way up pages)` - though I appreciate they did not!

What happens if (for the Epsom) you:
* Source: `ADF`
* Batch: `Auto (Collate...)`
* Manually turn the pages over half way through

Does that work? If so, that may be the best option. Alternatively, I can merge the changes in as tested - but that seems... undesirable.

> Thanks for looking into this. It is really appreciated.

You're welcome 😄

**Comment by torwag** [comment]
Hi, thanks for looking again into it.
I can understand that it is tricky to get it right for all and every scanner. I can feel your pain, that you do not want to maintain a never ending, never up-to-date list of scanner configs for all kind of exotic constellations.
For me, merging it would be fine.   The --adf-mode might also work for other scanners. As for the turned pages, I will check again if there is a option to be set.

As for the more simplified GUI, I would again suggest considering #465. My and maybe many others uses case is to provide an as easy as possible user interface to (partially non-tech safe) family members. I would love to get a set of buttons, which I can configure with the desired scanning profile and a text (icon colour) via the config file.

That could be an additional menu "Shortcuts" or "Presets". Triggering one of those would perform the underlying action. Single press... single action.

So people can define buttons labelled 
"Duplex Scan PDF to XXXX" or "Front Scan PDF|OCR"
This feature is pretty much what many scanners offer nowadays with tiny displays and touch screens (but fail short in communication protocols etc.) 
I believe that this preset menu would be a very welcomed feature taken, that you could bold an old tablet on the wall to control the scanner by a single press.

**Comment by sbs20** [comment]
I will merge this as is then.

I am still considering #465. I will write more in that issue instead of this.
