### ISSUE TITLE
invalid option -- 'o'

### ISSUE THREAD

**Issue by vbambuch** [sbs20/scanservjs#495]
**Describe the bug**
I installed the latest version to my RPI3 and scanning failed for: `/usr/bin/scanimage: invalid option -- 'o'`

**To Reproduce**
1. Install the latest version
2. Try scanning 
3. See the error

**Expected behavior**
Not sure where exactly is the problem but installing v2.21.0 fixed the issue

**Client (please complete the following information):**
 - Browser: Chrome
 - Version: 108.0.5359.98

**Server (please complete the following information):**
 - OS: Debian 10
 - Node version: 16.13
 - NPM version: 8.1

**Logs**
```
Dec 18 11:50:33 rpi3 server.js[14205]: [2022-12-18T11:50:33.565Z] ERROR (Http): Error: /usr/bin/scanimage -d 'epson2:libusb:001:011' --mode 'Lineart' --resolution 100 -l 0 -t 0 -x 215.9 -y 297.1 --format 'tiff' -o data/preview/preview.tif exited with code: 1, stderr: scanimage: rounded value of resolution from 100 to 75
Dec 18 11:50:33 rpi3 server.js[14205]: /usr/bin/scanimage: invalid option -- 'o'
```

**Additional context**
```
scanimage -L
device `epson2:libusb:001:004' is a Epson PID 0851 flatbed scanner
```

**Comment by sbs20** [comment]
Most likely this is an old version of scanimage because it's running buster. I will attempt to look into this when I get a chance - I'm always keen to support older systems. But it's also likely resolved if you upgrade to bullseye.

**Comment by ceskyDJ** [comment]
Hi, I have the same problem. I isolated it to running `sudo /usr/bin/scanimage -d 'hpaio:/usb/...' --mode 'Color' --source 'Flatbed' --resolution 300 -l 0 -t 0 -x 210 -y 297 --format 'tiff' --brightness 1000 --contrast 1000 -o data/temp/~tmp-scan-0-0001.tif` in terminal, which ends with error:
> /usr/bin/scanimage: invalid option -- 'o'

I have older Raspberry OS on this Raspberry Pi. It works well on the second Raspberry Pi with Debian 11. So, could you look at it and possibly add support for older OSes? I though this problem started with the last update.

**Comment by sbs20** [comment]
Yeah, I'm working on it. It was [this PR](https://github.com/sbs20/scanservjs/pull/418)

The thing is, that PR fixes other issues... I'm working on it.

Please use an older release for now.

**Comment by ceskyDJ** [comment]
Thanks for your work. Don't hurry up, it's not too critical.

**Comment by sbs20** [comment]
For reference, it was added in [1.0.28](https://gitlab.com/sane-project/backends/-/releases/1.0.28) which was after the version used by buster.

**Comment by sbs20** [comment]
Ok. It's not released yet, but the code is on `master` - would be great if you could give it a go on both buster and debian. I've tested as much as I can but the real world is often different.

**Comment by ceskyDJ** [comment]
Ok, I'll try it and let you know.

**Comment by ceskyDJ** [comment]
@sbs20, I tried to run code from the `master` branch (using similar steps as in https://github.com/sbs20/scanservjs/blob/master/docs/install.md#manual-download-and-install) but I failed. Installation of official release "works" (with the error of this thread).  Could you send me any hint, please?

**Comment by ceskyDJ** [comment]
Ok, I tried more and finally I got it. On older RaspberryPi OS it works well (the place, where it doesn't work before). The second Raspberry Pi I have is in a different place, so I could test the pre-release after 27th December, if it is ok.

**Comment by sbs20** [comment]
Oh nice one! Yeah, no hurry 🎅

**Comment by zjph602xtc** [comment]
I have the same problem. Waiting for the new release.

**Comment by ceskyDJ** [comment]
> I have the same problem. Waiting for the new release. 

Could you try pre-release version in `master` branch?

**Comment by zjph602xtc** [comment]
> > I have the same problem. Waiting for the new release.
> 
> Could you try pre-release version in `master` branch?

Thanks for you quick reply. 

I tried this: I downloaded the master branch and unzipped it, then
```
cd /home/pi/Downloads/scanservjs-master/packages
sudo chmod -R 777 server
sudo ./server/installer.sh -i
sudo journalctl -e -u scanservjs
```
the log shows 
```
Dec 26 05:04:27 raspberrypi systemd[1]: Started scanservjs.
Dec 26 05:04:41 raspberrypi server.js[431]: [2022-12-26T10:04:41.206Z] INFO (server): Started
Dec 26 16:05:33 raspberrypi systemd[1]: Stopping scanservjs...
Dec 26 16:05:33 raspberrypi systemd[1]: scanservjs.service: Main process exited, code=killed, status=15/TERM
Dec 26 16:05:33 raspberrypi systemd[1]: scanservjs.service: Succeeded.
Dec 26 16:05:33 raspberrypi systemd[1]: Stopped scanservjs.
Dec 26 16:18:11 raspberrypi systemd[1]: Started scanservjs.
Dec 26 16:18:11 raspberrypi systemd[13419]: scanservjs.service: Failed to execute command: No such file or directory
Dec 26 16:18:11 raspberrypi systemd[13419]: scanservjs.service: Failed at step EXEC spawning /var/www/scanservjs/server/server.js: No such file or directory
Dec 26 16:18:11 raspberrypi systemd[1]: scanservjs.service: Main process exited, code=exited, status=203/EXEC
Dec 26 16:18:11 raspberrypi systemd[1]: scanservjs.service: Failed with result 'exit-code'.
Dec 26 16:18:11 raspberrypi systemd[1]: scanservjs.service: Service RestartSec=100ms expired, scheduling restart.
Dec 26 16:18:11 raspberrypi systemd[1]: scanservjs.service: Scheduled restart job, restart counter is at 1.
Dec 26 16:18:11 raspberrypi systemd[1]: Stopped scanservjs.
```

In var/www/scanservjs, there is no server folder, but only the scr folder. I know I did something wrong, but cannot figure out how to do it.

**Comment by ceskyDJ** [comment]
Oh, I'm so sorry... I completely forgot about this. The newest release works ok on newer Raspberry Pi with Debian 11, so it should be ok.

**Comment by sbs20** [comment]
> Oh, I'm so sorry... I completely forgot about this. The newest release works ok on newer Raspberry Pi with Debian 11, so it should be ok.

Ha, don't worry - and certainly no need to apologise!
