### ISSUE TITLE
Fails to run

### ISSUE THREAD

**Issue by Anemone0** [sbs20/scanservjs#5]
I build it and browse the URL like 'http://192.168.200.200:8080/'.However, the page shows "scanserv.js
Command line testing » exec". It seems I don't have file named 'assets/js/app.js' and 'assets/css/app.css'. Please tell me what should I do?

![tim 20171003001900](https://user-images.githubusercontent.com/4996660/31087669-7db6f0ba-a7d0-11e7-934d-79655a8557a6.png)

**Comment by sbs20** [comment]
Hi! How did you build?

You can just follow the instructions [here](https://github.com/sbs20/scanservjs/blob/master/install.md) and download the latest release which will have those files. If you want to build yourself then just running `gulp` should automatically generate those files for you.

**Comment by Anemone0** [comment]
Oh, I'm sorry. I just cloned this repository and run install.sh. Now it works. Thanks a lot!

**Comment by sbs20** [comment]
No problem at all - I'm glad it all works!!
