### ISSUE TITLE
Feature request: Customize error messages

### ISSUE THREAD

**Issue by torwag** [sbs20/scanservjs#501]
I noticed that the error messages (red pop-ups) are basically the error messages of the underlying scanimage command, which itself is just reporting the scanners response.
As there is no uniform way of scanner responses, that could be anything from very technical to complete useless.
E.g.
`  {"message":"/usr/bin/scanimage -d 'fujitsu:ScanSnap S1500:104286' --mode 'Gray' --source 'ADF Duplex' --resolution 150 -l 0 -t 0 -x 215.8 -y 279.3 --format 'tiff' --brightness 0 --contrast 0 --batch=data/temp/~tmp-scan-1-%04d.tif exited with code: 1, stderr: scanimage: open of device fujitsu:ScanSnap S1500:104286 failed: Invalid argument\n","code":-1}`

Is the error message if the SnapScan runs of of paper for the ADF unit. 

What would be nice if we could define replacements for those rather technical error messages e.g. by regex
`
{errors:
    {
     replace: "104286 failed.*:-1",
     msg:   "ADF is out of paper"
   }
} 
`

**Comment by sbs20** [comment]
It's a nice idea - and my immediate thought was - yes, I'll do that. But `/open of device.*Invalid argument.*-1/` gets returned for pretty much all errors - so `ADF is out of paper` would get reported even when it's not. See #425 for example. So I don't really think it's worth the effort. I'm going to close this for now, but happy to re-open if I'm wrong!

**Comment by torwag** [comment]
Yes this was an example. There are other error messages, which are more specific. The trouble is that there is no standard and it would be to the users to figure out how to translate them somehow.

**Comment by sbs20** [comment]
I can't tell if you're agreeing with me or want me to reopen 😄 . If it's the latter, can you provide  examples of other error messages?
