### ISSUE TITLE
Add custom file actions

### ISSUE THREAD

**Issue by sbs20** [sbs20/scanservjs#504]
* Add the ability to add custom, user-defined file actions
* A file action will have a name and some code
* The code will take a single parameter, which is the file itself
* Add code to the UI which will run the file action for selected files

See [this PR comment](https://github.com/sbs20/scanservjs/pull/479#issuecomment-1330451274) for background

**Comment by torwag** [comment]
I don't know exactly how this would be integrated in the UI. But as it is right now it would be applied to all files, right?

It would be great if users could select which file actions are applied directly after the scan. Very much like you select filters or file format.
