### ISSUE TITLE
User scanservjs

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#507]
Hi! Is it necessary to have own home directory for user `scanservjs` automatically created by installation script? I think it isn't, so removing switch parameter `-m` clould be some kind of little improvement :).

**Comment by torwag** [comment]
I use that home folder, e.g. to configure rclone and set-up ssh to push scans to another service.

**Comment by ceskyDJ** [comment]
> I use that home folder, e.g. to configure rclone and set-up ssh to push scans to another service.

I think, that is a good idea to use the home folder for storing configuration files, when you use that user for something else like sending scanned file via rclone or different tool. Otherwise I think there isn't many people doing these additional tasks with scanned data. So, I suggest adding switch to scanservjs's install script allowing creation of the home folder. What do you think about it?

**Comment by sbs20** [comment]
I sympathise with the desire to keep things minimal - and I am not averse to removing it in principle. But given some users use that directory, it's already created and the impact of creating the home directory is minimal I am inclined to keep it as is.
