### ISSUE TITLE
Restart of scanservjs often results in no devices found

### ISSUE THREAD

**Issue by torwag** [sbs20/scanservjs#520]
**Describe the bug*
Creating my own pipeline, I had to restart multiple times scanservjs. I  did so by calling systemctl restart scanservjs.service.
After that, scanservjs couldn't find any scanner devices. I had to either replug the scanner (USB) or restart the RPi.

**To Reproduce**
1. Restart scanservjs via systemd
2. Click button to find scanner devices 
3. See message No devices found

**Expected behavior**
After restart, the devices should be found. Sometimes it does, I can directly scan, sometimes not

**Server (please complete the following information):**
 RaspianOS on a RPi4

**Comment by sbs20** [comment]
When it happens, what happens if you run `scanimage -L` at the console?

**Comment by torwag** [comment]
scanimage -L does not provide any devices. Thus it might be a problem with the underlying scanimage and sane system.
lsusb shows the scanner, so on that side, it seems to be recognized.
As I just restart scanservjs, it puzzles me that it affects the recognition under scanimage. Maybe some sort of hold-and-release problem? Have no idea about saned devices and client management.  
If there is anything else I could test, please let me know.

**Comment by sbs20** [comment]
I guess you could check to see if there are any stray scanservjs processes lingering - `ps ax | grep node` will give you a starting point. Even so - scanimage runs and exits and the app has no hold over sane so I am skeptical of this.

I guess the other speculation I would have is - is it definitely to do with the restart? Is it just happening anyway and you notice it on the restart? e.g. is the scanner going into power save mode? Also - if `scanimage -L` is returning nothing, does it still work if you specify the correct (old, cached) device? Are you deleting the device config on restart?

Does the device id change - assigning to a different USB device?

How is scanimage connecting to the backend? Is it in a container or on the host? Could it be related to #505? Is it using SANE over the network, in which case could you `systemctl restart saned.socket`

Lots and lots of questions - in all cases, see what `scanimage` reports - my guess, though I am willing to be proved wrong, is that it's nothing to do with the app.

**Comment by torwag** [comment]
Thanks for the guidance. To be more clear. With restart, I only refer to a restart of scanservjs via systemd. 
A reboot of the Rpi, will always work, however a bit of a clunky solution.
Unfortunately, it will not work with the "old" setting. That is the reason I spotted that problem. I changed some configs, restarted scanservjs and wanted to do a test scan only to get an error message from the scanner, a rescan of available devices reports then, that no devices are found. I will check again about a possible sleep mode, but I would be surprised it if is this. I had the scanner stay on standby for larger times and triggered a scan via scanservjs without problems. However, even after a successful scan a minute ago, after a restart the device is not found any more.

Workarounds right now are only....
1. Restart of the System
2. Replug in the Scanner USB connection

I will check about dangling processes. 
To further narrow it down, I will send you the device.xml files before, during and after that happens. Maybe something is visible from a diff. I can also check about possible debug options of scanimage itself.

**Comment by sbs20** [comment]
The way it should work:

* Things you configure are in `config/conflg.local.js`
* You refresh devices in the UI and `config/devices.json` stores the output of `scanimage -A` for each device
* You change the config and restart, but devices.json remains and caches the results

If you are getting "No devices found" then it means that devices.json has disappeared and it's forcing a reload.

Your issue still remains, but it's not clear to me what you're doing.

Can you report step by step what you are doing and what the app is saying with screenshots / log extracts?

**Comment by torwag** [comment]
Ok, I come to realize that this might indeed have nothing to do with scanservjs but it is a much deeper problem of saned, rpi and the particular scanner. 
Internet is full of stories that scanners suddenly are not recognized by scan image -L but still be found by sane-find-scanner. 
Unfortunately, not many solutions are provided and none helped in my case.

**Comment by tyriis** [comment]
I am running it in kubernetes and need to re-start dbus each time it restarts to get the airscan device found. Have overwritten the run for it.

```yaml
args: [-c, service dbus start && /run.sh]
```

https://github.com/tyriis/flux.k3s.cluster/blob/main/cluster/apps/hardware/scanservjs/helm-release.yaml#L35

**Comment by sbs20** [comment]
I'm going to close this as it seems to be nothing to do with the app.
