### ISSUE TITLE
Scanservjs creates zip files after adding my own pipeline

### ISSUE THREAD

**Issue by torwag** [sbs20/scanservjs#521]
I went to add my own pipeline to create a PDF version of the scan and push this via rclone over an sftp connection to paperless.
The entire pipeline took me an evening, even just being a few lines, but it resulted in #519.
I was completely puzzled why the entire chain of commands worked perfectly fine simulated from my shell but didn't worked called as pipeline by scanservjs.

My pipeline looks now like:

```
 config.pipelines.push({
        extension: 'pdf',
        description: 'PDF | Scan2Paperless',
        get commands() {
          return [
            'convert @- -quality 92 tmp-%04d.jpg',
            'send2paperless.sh',
            'ls tmp-*.*'
          ];
        }
    });
```

Whereas send2paperless.sh is just a simple script which relies on a variable (thus the script).

```
#! /bin/bash

fname=scan_$(date +"%d_%M_%y-%H_%M_%S").pdf
convert tmp-*.jpg pdf:${fname}            
cp ${fname} ../output/paperless_export #just for backup
rclone copy ${fname} paperless:paperless_consume
```

This works fine and gives me the ability to modify fname in a way that it helps paperless to get some infos for that file. Unfortunately, rclone seems to dislike certain characters in filenames, I need to check on this separately.

My main problem now, scanservjs creates now a Zip file instead of a PDF as final file of the pipeline and adds this to the file list.
I have no idea how or why it does this. 

Just to let you know why I did not yet use the new file action approach. That would run, as I understand, for each and every scan. 
I like the idea that I can select PDF|Send2Paperless as output format and only then it gets transmitted to paperless. 
There was the suggestion of creating an additional button in the file view to send documents, but honestly, I want to click and do as little as possible during scanning a batch of documents for paperless. Just preset and starting scanning, knowing it will end up in paperless, is the best way for me.

**Comment by sbs20** [comment]
> I have no idea how or why it does this.

This is expected behaviour. See:

* <https://github.com/sbs20/scanservjs/blob/3cec787719fbd3e8e6f708336b0ebf4af17d44b1/packages/server/config/config.default.js#L38>
* <https://github.com/sbs20/scanservjs/blob/3cec787719fbd3e8e6f708336b0ebf4af17d44b1/packages/server/src/scan-controller.js#L99>

You should be able to fix it by changing the last line of the pipeline to `ls *.pdf`

> Just to let you know why I did not yet use the new file action approach. That would run, as I understand, for each and every scan.

Thanks for letting me know. Makes sense.

**Comment by torwag** [comment]
Ahhh ok,
I thought that at the end of the pipeline, scanservjs expect a list of images to combine it to a PDF by itself.
Yeah, makes no sense, know that I am thinking about it. Guess I was triggered by the first example where `ls scan*.*` was used. Will test your advices and if it works this here can be closed.

**Comment by torwag** [comment]
Ok that can be closed. It was a misunderstanding of what scanservjs expects as a final pipeline output.
