### ISSUE TITLE
Feature Request: Asynchronous document processing

### ISSUE THREAD

**Issue by torwag** [sbs20/scanservjs#524]
Creating my own pipeline on a RPi 4, I noticed that depending on my settings, it could easily take 20-30 seconds to process a scan of a few pages. 

I am in the mid of testing how to speed this up (any help welcome, seems like `convert -compress fax` really takes its time).

However, I wonder if it would be possible to decouple the scanning process from the post-processing process of the scanned files. As soon as the files are available, another process could take over to work on those files (as long as it takes), but the next scan could be started already. 
For this, within the temp-folder one would need to create individual subfolders, to contain the raw-scan files and scanservjs would have to spawn a new process of post-processing on each of that folders. 
That would massively decrease the delay time in the UI and hence speed up the workflow of scanning a batch of different documents. 

(@sbs20 Sorry for all the feature requests, I am in the mid of getting my paper-free office  working based on scanservjs + paperless-ngx).

**Comment by sbs20** [comment]
It's an interesting thought, but probably falls into the "too much effort, not enough gain" bucket. I do appreciate your requests - so please don't be sorry - and I love that this is proving genuinely useful, but I'm going to close this one.
