### ISSUE TITLE
Feature Request: Scanner buttons support

### ISSUE THREAD

**Issue by nekromant** [sbs20/scanservjs#526]
Thanks for the awesome app!

The idea is simple: bind scanner buttons to specific formats via config.local.js. The scanner buttons can be polled via a simple call to `scanimage -A` when there is no scanning in progress, so it should be more or less easy to implement.

**Comment by sbs20** [comment]
Hi, thanks for posting. I have no plans to do this in this project but you may find [this](https://github.com/sbs20/scanservjs/blob/master/docs/integration.md#insaned) works for you - it integrates with scanservjs

**Comment by nekromant** [comment]
@sbs20 Thanks a lot! That would do the trick for me!

**Comment by sbs20** [comment]
Cool, no worries 👍
