### ISSUE TITLE
Docker Tags are not semver compatible

### ISSUE THREAD

**Issue by tyriis** [sbs20/scanservjs#529]
First of all, thanks a lot for your great work <3

I would not name it a bug, it is more a change request/improvement. Currently docker builds are tagged with release-{semver} this is not compatible with tools like renovate out of the box.

It would be great and really helpful for self-host enthusiasts to get automated pull request via renovate for your docker images.

Suggestion: to not break with existing pattern, it is possible to multi tag images, like this it is possible to make images semver compatible without changing existing behaviours.

Let me know if this is fine, I could make a PR with the required changes.

**Comment by sbs20** [comment]
This is a very good point - I would be very happy to accept a PR which adds additional tags. Thank you!

**Comment by tyriis** [comment]
I have not added semver range tags as I am not of the opinion that they are a good approach.

**Comment by tyriis** [comment]
closing as it is merged thanks for your quick reply, this is solving my auto-update problem :)

**Comment by tyriis** [comment]
@sbs20 any chance to get a release or pre-release soon?

**Comment by sbs20** [comment]
Released
