### ISSUE TITLE
Chance to auto-reload hardware on startup

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [sbs20/scanservjs#543]
I create a UDEV rule on my docker host to restart my scanservjs container when my canon scanner is on.

Each time my scanner get a new sub-id.
E.g. /dev/bus/usb/001/001 -> /dev/bus/usb/001/002
I need to hit reload device each time.

Is there a chance to auto-reload device on each startup?

**Comment by sbs20** [comment]
Hello!

I think you have a few broad options here:

1. Alter your udev rule to create a fixed id a bit like [this](https://www.emanuelepapa.dev/assign-static-device-name-using-udev-rules/). I'm not sure how well it will work with SANE but at least if you get a fixed id then you won't need to take further action. Something along these lines is probably the cleanest way.
2. Delete `devices.json` which caches the device info - known as `context` to the UI.
   1. Manually delete the devices.json file but that requires shelling inside the container and deleting the file (I think it's in `/app/config/devices.json` - not so good, but marginally less bad if not using a container.
   2. Execute the REST API to delete the context e.g.
      ```sh
      curl -X 'DELETE' 'http://localhost:8080/context' -H 'accept: application/json'
      ```
   The next time the app does anything it will force a reload of the devices.
