### ISSUE TITLE
Create files in final folder only when the scan is finished

### ISSUE THREAD

**Issue by whysthatso** [sbs20/scanservjs#55]
heya,
i'm using scanservjs as an input scanner for my edms papermerge.

scanservjs's output folder is papermerge's input folder.

unfortunately, as soon as scanservjs creates the empty file to be filled with data upon commencement of a scan, papermerge's worker can already grab the file and move it out of the folder. 

would it be possible to finish the file in a temporary location and move it into the output folder thereafter? maybe that can be configurable, or system-tmp.

**Comment by JnCrMx** [comment]
I did a quick (and rather dirty) solution. To be honest I'm not sure if it's worth merging into ``master``.

But for you it might be quite useful.

**Comment by whysthatso** [comment]
thanks all for the good work :+1:
