### ISSUE TITLE
Problem with Nginx proxy

### ISSUE THREAD

**Issue by setaur** [sbs20/scanservjs#561]
Thank you for this great app!

I'm having trouble setting up a redirect to scanservjs site using nginx reverse proxy. I installed this great webapp on my home debian server and I can access it through http://192.168.2.127:8080. But I want to access it using url http://192.168.2.127/scanner. So as advised by doc [here](https://github.com/sbs20/scanservjs/blob/master/docs/proxy.md) I putted this file into /etc/nginx/sites-enabled/scanner.conf :
```
server {
    listen       80;

    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;

    location /scanner/ {
             proxy_set_header   X-Real-IP $remote_addr;
             proxy_pass         http://127.0.0.1:8080/;
  }
}
```
But after command `nginx -s reload` and trying to access http://192.168.2.127/scanner I get a blank page. Page code inspection shows:
```
<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="[favicon.ico](view-source:http://192.168.2.127/scanner/favicon.ico)"><title>scanserv-js</title><link href="[css/chunk-vendors.915cd3b3.css](view-source:http://192.168.2.127/scanner/css/chunk-vendors.915cd3b3.css)" rel="preload" as="style"><link href="[css/index.ac7d0a75.css](view-source:http://192.168.2.127/scanner/css/index.ac7d0a75.css)" rel="preload" as="style"><link href="[js/chunk-vendors.ccdda7ef.js](view-source:http://192.168.2.127/scanner/js/chunk-vendors.ccdda7ef.js)" rel="preload" as="script"><link href="[js/index.b744358c.js](view-source:http://192.168.2.127/scanner/js/index.b744358c.js)" rel="preload" as="script"><link rel="shortcut icon" href="[favicon.ico](view-source:http://192.168.2.127/scanner/favicon.ico)"><link href="[css/chunk-vendors.915cd3b3.css](view-source:http://192.168.2.127/scanner/css/chunk-vendors.915cd3b3.css)" rel="stylesheet"><link href="[css/index.ac7d0a75.css](view-source:http://192.168.2.127/scanner/css/index.ac7d0a75.css)" rel="stylesheet"></head><body role="document"><noscript><strong>We're sorry but scanserv-js doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="[js/chunk-vendors.ccdda7ef.js](view-source:http://192.168.2.127/scanner/js/chunk-vendors.ccdda7ef.js)"></script><script src="[js/index.b744358c.js](view-source:http://192.168.2.127/scanner/js/index.b744358c.js)"></script></body></html>
```
Firefox console brings only (translated):
Load failed for "script" element with source  „http://192.168.2.127/scanner/js/chunk-vendors.ccdda7ef.js”.

Is this a problem with nginx configuration or with scanservjs?

**Comment by sbs20** [comment]
Hmm. You know, I haven't tried it for a long time. What version of Debian are you running,? I'll have to give it a try and see.

I don't know is the short version!

**Comment by setaur** [comment]
Thanks for quick reply. It's Debian 10 buster, nginx version: nginx/1.14.2

**Comment by sbs20** [comment]
Let me spin up a VM and I'll see what I can do. It won't be for a little while though, sorry.

**Comment by sbs20** [comment]
Ok, I tried it on a fresh buster install. I followed what you did and had some problems.

Then I re-read the instructions (which say to put the settings in `/etc/nginx/sites-available/default`) and decided to just delete that symlink (the `-> default` one). I restarted nginx with `sudo systemctl restart nginx` and it all worked.

I can't say what you need to do to fix it, but to answer your question, I think it's an nginx config issue.

I would suggest (assuming you have symlinks from `sites-enabled` to `sites-available`) deleting the other enabled sites and start from a simple set up just to confirm. If you can't do that, perhaps just switch to a different port at least to confirm it works.

I hope that helps.

**Comment by setaur** [comment]
Thanks for your reply. I don't have any other symlinks in `/etc/nginx/enabled-sites`. I tried many combinations, i.e. just copying `/etc/nginx/sites-available/default` into sites-enabled/skaner2.conf and dummy paste there section from scanservjs docs, which produces file `/etc/nginx/sites-enabled/skaner2.conf` :
```
# grep -v -E '^\s*#' skaner2.conf 

server {
        listen 80 default_server;
        listen [::]:80 default_server;


        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;

        location /scanner/ {
                 proxy_set_header   X-Real-IP $remote_addr;
                 proxy_pass         http://127.0.0.1:9333/;
        }


}
``` 
After successful `systemctl restart nginx` accessing 192.168.2.127/scanner leads to "Cannot GET /scanner/" page.

Port is changed, because 8080 conflicted with Kodi remote port - I changed it in `/var/www/scanservjs/config.local.js` and accessing http://192.168.2.127:9333 works fine. Is that what you mean by switching to another port? I have unblocked port 80 in firewall ufw and also disabled it entirely for tests, but it didn't make any difference. 

TBH I don't have much experience with nginx, maybe I just keep doing some stupid mistake. Could you please provide your full working nginx config from sites-enabled so I could try it?

**Comment by sbs20** [comment]
Sorry for the slow reply... here's mine

```
root@buster:/etc/nginx/sites-enabled# cat scanner.conf 
server {
    listen       80;

    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;

    location /scanner/ {
             proxy_set_header   X-Real-IP $remote_addr;
             proxy_pass         http://10.0.7.30:8080/;
  }
}
```

> Is that what you mean by switching to another port? 

No - I meant changing the port of the `server` in nginx (you can have many servers listening on different interfaces or ports or whatever). So maybe change this port:

```
server {
    listen       80; # Change this to 9000 or something
```

I'm not suggesting changing the port as a fix so much as a means of ensuring that the configuration doesn't overlap with anything else you've got configured.

**Comment by setaur** [comment]
Thank you for answer. That config didn't worked neither, but I figured it out. It was apparmor blocking nginx:
```
# journalctl
...
kernel: audit: type=1400 audit(1677316890.585:9411): apparmor="DENIED" operation="mkdir" profile="/usr/sbin/nginx" name="/var/lib/nginx/proxy/3/" pid=27794 comm="nginx" requested_mask="c"  denied_mask="c" fsuid=33 ouid=33
```
Disabling apparmor for nginx solved this problem finally. It looks like standard Debian apparmor profile for nginx is too restrictive. Thanks for your time.
