### ISSUE TITLE
Support for "Scan to PC" button on Brother printer

### ISSUE THREAD

**Issue by piter-pit** [sbs20/scanservjs#570]
I have a scanservjs running on Raspberry Pi OS and Brother printer/scanner nicely supported in scanservjs.
Is it possible to configure scanservjs in a way to process "scan to PC" button directly from the printer?
Currently I can trigger scanning from via scanservjs webpage, but when I press scan button on the printer it starts scanning app on PC. I would like to redirect it to scanservjs.
From PC registration is possible by https://support.brother.com/g/b/faqend.aspx?c=us&lang=en&prod=dcpj140w_all&faqid=faq00002785_000

**Comment by sbs20** [comment]
Hi! Thanks for asking. #526 may help.

**Comment by piter-pit** [comment]
It might be more tricky than I thought https://www.mcbsys.com/blog/2014/11/register-pc-on-brother-scanner/ "Brother support said that the scanner looks for available PCs when you press the Scan to button, and advised me to confirm firewall exceptions as outlined in [this article](http://www.brother-usa.com/FAQs/Solution.aspx?FAQID=200000014918#.VF0fW8lVDFZ). The default exception (UDP 54925) was in fact out of date—it was created on the Private profile but the computer had since joined the domain. I added a group policy to create exceptions on UDP 137, 54925, and 54926:

**Comment by piter-pit** [comment]
> Hi! Thanks for asking. #526 may help.

Hi, Thanks for the link. I need to investigate it since I'd like to keep it in docker container as scanservjs is

**Comment by piter-pit** [comment]
I was able to install, service is running but the printer says "No PC found" also "instaned -L" command list my printer but after the colon there is no info about button

**Comment by sbs20** [comment]
I'm afraid I can't support insaned - please raise an issue in that repo. I wish you good luck with it.

**Comment by piter-pit** [comment]
I think it might be different case -> different mechanism than using insaned and what my printer do. I do not have one button to scan, but only select from menu "scan to PC" so as mentioned in the link that I provided, scanner has to have IP already provided.
I also visited original project https://github.com/abusenius/insaned and description sounds little bit off what what is above
