### ISSUE TITLE
`--mode` ignored if before `--source` (Grayscale scan results in color)

### ISSUE THREAD

**Issue by stephenpapierski** [sbs20/scanservjs#573]
Despite multiple grayscale options being detected on my scanner, all of the options result in color scans.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/5900005/222520152-9850306f-663d-4bcf-869f-f24514d7f659.png">

Any tips on where to start digging?

**Comment by sbs20** [comment]
It would help if you could fill in a bug report so I can see version and logs.

**Comment by stephenpapierski** [comment]
Thanks, I'll fill one out. Just didn't want to go through the effort if it was an obvious oversight on my part. I'll dig in to provide the necessary details for the full bug report.

**Comment by stephenpapierski** [comment]
**Describe the bug**
Despite multiple greyscale options appearing [Grey, 16 bits gray] for mode, the still produce color scans.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'SCAN'
2. Click on 'Mode'
3. Select 'Grey' or '16 bits gray'
4. Click 'PREVIEW'
5. See that preview produces color scan
6. Click 'SCAN'
7. See that document is scanned in color

**Expected behavior**
'Grey' or '16 bits gray' scans should not be in color

**Screenshots**
The following is the result from pressing "PREVIEW" with the on screen settings. The resulting scan contains red.
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/5900005/222527526-55a0261b-69b4-4173-9ed1-9aa7db885877.png">

**Client:**
 - Chrome (same behavior on Windows, Mac, and Android)
 - Version 110

**Server:**
 - OS: Raspian GNU/Linux 11 (bullseye)
 - Node version: v12.22.12
 - NPM version: 8.3.0
 - Docker version: N/A (performed 'one line install' from docs/install.md)

**Logs**
[scanservjs.log.installed.txt.gz](https://github.com/sbs20/scanservjs/files/10875078/scanservjs.log.installed.txt.gz)

**Comment by sbs20** [comment]
Very weird. Log says:

```
Mar 02 12:07:42 scanner server.js[514]:   spawn: '/usr/bin/scanimage -d pixma:04A91901 --mode Gray --source Flatbed --resolution 100 -l 0 -t 0 -x 216 -y 297 --format tiff -o data/preview/preview.tif'
```

Try running that yourself from the command line (maybe adjust your output location) and see what comes out. I don't think the app or you are doing anything wrong. I'm only looking quickly on my phone but my guess is it's the sane backend misbehaving.

**Comment by stephenpapierski** [comment]
Yeah, this is interesting. I did notice in the logs that it seemed to be calling scanimage correctly. It does seem to be an issue at the scanimage level though.

Trying `Gray` mode...
```
/usr/bin/scanimage -vvvvvvv -d pixma:04A91901 --mode Gray --source Flatbed --resolution 100 -l 0 -t 0 -x 216 -y 297 --format tiff -o /home/user1/Downloads/gray.tif
scanimage: value for --resolution is: 100
scanimage: rounded value of resolution from 100 to 75
scanimage: value for --tl-x is: 0
scanimage: value for --tl-y is: 0
scanimage: value for --x is: 216
scanimage: value for --y is: 297
scanimage: scanning image of size 638x877 pixels at 24 bits/pixel
scanimage: acquiring RGB frame
scanimage: min/max graylevel value = 81/255
scanimage: read 1678578 bytes in total
Closing device
Calling sane_exit
scanimage: finished
```
Trying `Color` mode...
```
/usr/bin/scanimage -vvvvvvv -d pixma:04A91901 --mode Color --source Flatbed --resolution 100 -l 0 -t 0 -x 216 -y 297 --format tiff -o /home/user1/Downloads/color.tif
scanimage: value for --resolution is: 100
scanimage: rounded value of resolution from 100 to 75
scanimage: value for --tl-x is: 0
scanimage: value for --tl-y is: 0
scanimage: value for --x is: 216
scanimage: value for --y is: 297
scanimage: scanning image of size 638x877 pixels at 24 bits/pixel
scanimage: acquiring RGB frame
scanimage: min/max graylevel value = 89/255
scanimage: read 1678578 bytes in total
Closing device
Calling sane_exit
scanimage: finished
```
And both files show the red color of the ink and end up the same file size...
```
du -hs ./*.tif
1.6M	./color.tif
1.6M	./gray.tif
```

There are newer versions of sane-utils (v1.2.1 seems to be the latest). The latest available within the raspbian repo is 1.0.31, but it does seem to claim ["Complete"](http://www.sane-project.org/sane-backends-1.0.31.html#:~:text=CanoScan%208800F,up%20to%204800DPI) support for the Canon 8800F. I think my next steps are to update to a newer version of the sane backend, and report a bug if that doesn't help. Feel free to close this issue out though, since it's not this project's problem. Thanks for the help!

**Comment by sbs20** [comment]
No problem! I will close. But... please let me know how it turns out - I want to know now!

**Comment by stephenpapierski** [comment]
I tried plugging my scanner directly into my Ubuntu machine running a newer version of sane-backends (1.1.1). I tried scanning in grayscale via simple-scan, one of the supported sane front ends. It has no problem scanning in grayscale, so I figured it might be the sane-backends version. However, when I issue the grayscale command from above, I still end up with a color image, which starts to suggest to me that the call needs to be somehow different.

**Comment by stephenpapierski** [comment]
Turns out it's a bug in the pixma backend. Bug report has been filed [here](https://gitlab.com/sane-project/backends/-/issues/664).

In short, when the user specifies --source after specifying --mode option, the value selected for --mode is discarded and substituted with the default for that source (in my case Color).

This can be worked around simply by reordering the arguments to scanimage (--source _then_ --mode). Unless a bug exists in the opposite direction for another backend, I don't see this affecting the functionality for devices that currently work. If I worked to make this modification and test it out, would you have any concerns with merging a pull request that swapped the order of the arguments?

**Comment by sbs20** [comment]
I remember something else like this - had to search, but found it [here](https://github.com/sbs20/scanservjs/issues/100#issuecomment-738123973).

I'm going to re-open because it's fixable.

**Comment by sbs20** [comment]
>  If I worked to make this modification and test it out, would you have any concerns with merging a pull request that swapped the order of the arguments?

I'm sorry - I only just saw this bit. No, I would not mind at all. Although I have done #580 now.

**Comment by stephenpapierski** [comment]
No worries, I just figured I would offer some help versus expecting a fix. But thanks for the fix and the crazy quick turnaround. Now that I can do grayscale, I'm loving the flexibility of scanning from any device on my network.
