### ISSUE TITLE
scanimage -L finds the scanner but doesn't appear in scanserv-js webpage

### ISSUE THREAD

**Issue by Leone25** [sbs20/scanservjs#574]
Hello, after a long and convoluted process I finely was able to get `scanimage -L` to list my scanner:
```bash
enrico@raspberrypi:~ $ scanimage -L
device `hpaio:/usb/HP_LaserJet_Pro_MFP_M26nw?serial=CNBKL2L5T4' is a Hewlett-Packard HP_LaserJet_Pro_MFP_M26nw all-in-one
```
But on the web interface I always get no devices found.
Can you give me a hand? I already tried logging in as the `scanservjs` user and running the scanimage command and it still works, so i have no clue at what could be wrong. I've attached logs below.
[scanservjs.log.installed.txt](https://github.com/sbs20/scanservjs/files/10891633/scanservjs.log.installed.txt)

**Server:**
 - OS: Raspbian GNU/Linux 11 (bullseye)
 - Node version v12.22.12
 - NPM version 8.3.0
 - Not using docker

Any help is greatly appreciated,
thank you in advance

Enrico

**Comment by Leone25** [comment]
ah, makes sense, I will check on that, it's weird tho because i actually used `hp-setup` to configure the printer/scanner (that turned out to be the solution after trying 1000+1 other things) so I would assume that missing file would have been created by it.

Anyway, thx for the tip, sadly I won't be able to do anything until next weekend, until then cheers

**Comment by Leone25** [comment]
Thank you for your help, turns out I didn't install hp-lip properly.
I formatted everything and followed [this](https://askubuntu.com/questions/1331362/error-sane-error-during-device-i-o-code-9-hplip) guide and it started to work, the only downside is that the script requires a desktop environment because it has to show a gui when installing and there seem to be no way around it, after that i just ran `hp-setup -i` (which instead can run 100% in the terminal and it picked up everything fine.

I hope this helps someone else

**Comment by sbs20** [comment]
Thank you for sharing!
