### ISSUE TITLE
Default locale configuration

### ISSUE THREAD

**Issue by ceskyDJ** [sbs20/scanservjs#583]
Hi, @sbs20!

I try to setup the most "regular" user (BFU in Czech) instance of Scanservjs for my parents. Everything works fine but there is a little problem with language. I need to set the Czech as default language because they don't speak English at all. So, when they see English app, they are completely lost.

Is there a way to setup default locale in config file?

**Comment by sbs20** [comment]
No. There isn't.

I'll add it to the list, it's a good feature!

**Comment by ceskyDJ** [comment]
Thanks a lot! I hope it will be useful for more users.
