### ISSUE TITLE
Wrong path for chmod in install.sh script

### ISSUE THREAD

**Issue by JnCrMx** [sbs20/scanservjs#60]
The ``install.sh`` script chmods the old location of ``server.js`` (``/var/www/scanservjs/server.js``). It should be ``/var/www/scanservjs/server/Server.js``.

This line https://github.com/sbs20/scanservjs/blob/master/install.sh#L65 should read
``chmod +x $scansrvjs_home/server/Server.js``
instead of
``chmod +x $scansrvjs_home/server.js``

P.S.: That new version looks truly amazing and that pipeline concept will probably make it very easy to include new formats and post-processing.

**Comment by sbs20** [comment]
Thanks. I knew I'd forget to test something!
