### ISSUE TITLE
Options marked as [inactive] should not be set.

### ISSUE THREAD

**Issue by JnCrMx** [sbs20/scanservjs#61]
Some options are marked as ``[inactive]`` in the output of ``scanimage -A``. For my scanner that is for example ``--brightness``.

The SANE API Documentations (http://www.sane-project.org/html/doc011.html#s4.2.9.7) says
> SANE_CAP_INACTIVE | 32 | If set, this capability indicates   that the option is not currently active (e.g., because it's   meaningful only if another option is set to some other value).

but leaves it unclear when an inactive option may be set and when it should not.

``scanimage`` on the other hand seems to fail when an inactive option is set. (See https://gitlab.com/sane-project/backends/-/blob/master/frontend/scanimage.c#L1046)
Therefore I am not sure if there is any way to make it work with an inactive option (by e.g. setting other options first).

In order for it to work on all devices, we need to either read all available options from ``scanimage -A`` and filter out inactive options, give the user a way to disable options, or test if any of the "default" options are inactive (as an addition to testing if they are available which is already done here https://github.com/sbs20/scanservjs/blob/master/client/components/Scanserv.vue#L407).

In my opinion, the first way would be best, as we cannot really assume that there is a set of "default" options.
There are so called "Well-Known Options" (see http://www.sane-project.org/html/doc014.html), but they do not include ``--brightness`` and ``--contrast`` which therefore don't have any fixed meaning we can rely on.

**Comment by JnCrMx** [comment]
The parsing for this is already done implicitly in the ``populate`` function of https://github.com/sbs20/scanservjs/blob/master/server/Device.js.
If an option is inactive, its default value is ``inactive``.

**Comment by JnCrMx** [comment]
Some screenshots that might help to see what I mean by this.

![Unbenannt967](https://user-images.githubusercontent.com/34038939/93028174-5be80d00-f612-11ea-8477-4a37a3ace6bc.PNG)
![Unbenannt4363](https://user-images.githubusercontent.com/34038939/93028177-5db1d080-f612-11ea-9f59-745edb10ff16.PNG)

**Comment by sbs20** [comment]
Could you do me a favour and run `scanimage -A > tmp.txt` and upload it. I am going to create some unit tests for this kind of thing. It's hard to test with just one scanner. The good news is that it should be an easy fix to propagate through the app. I just need to change these lines in `Request.js` to use the existing `isFeatureSupported(feature)` method

```javascript
    if ('--brightness' in device.features === false) {
      delete this.params.brightness;
    }
    if ('--contrast' in device.features === false) {
      delete this.params.contrast;
    }
    if ('--disable-dynamic-lineart' in device.features === false) {
      delete this.params.dynamicLineart;
    }
```

**Comment by sbs20** [comment]
(PS thanks for your testing and help!)

**Comment by JnCrMx** [comment]
``scanimage -A > tmp.txt``
> [tmp.txt](https://github.com/sbs20/scanservjs/files/5215069/tmp.txt)

``/usr/bin/scanimage -d "epson2:libusb:001:029" --mode "Lineart" --resolution 100 -l 0 -t 0 -x 215.9 -y 297.18 --format "tiff" --brightness 0 2> error.txt`` (command executed on preview that causes the error)
> [error.txt](https://github.com/sbs20/scanservjs/files/5215073/error.txt)

**Comment by JnCrMx** [comment]
38b8f6f79cb15fdcd76de20a3f5bae2e21d084ca fixes the issue for my device 👍
