### ISSUE TITLE
child_process "Incorrect value of args option"

### ISSUE THREAD

**Issue by TheRealHypR** [sbs20/scanservjs#68]
Hi,
I just updated my very old scanserv-js (1.0.1) to the newest version.
now I get this error in the gui "Incorrect value of args option".

When I press preview or print in GUI I get the error message.

But I can run the preview command from terminal successfully:
/usr/bin/scanimage -d "epson2:libusb:001:004" --mode "Gray" --resolution 100 -l 0 -t 0 -x 215 -y 297 --format "tiff" --brightness 0 > preview.tif

This is from journalctl:
[2020-09-21T14:07:03.179Z] ERROR (global): TypeError: Incorrect value of args option
Sep 21 16:07:03 scan Server.js[27726]:     at normalizeSpawnArguments (child_process.js:389:11)
Sep 21 16:07:03 scan Server.js[27726]:     at exports.spawn (child_process.js:496:38)
Sep 21 16:07:03 scan Server.js[27726]:     at Promise (/var/www/scanservjs/server/Process.js:23:20)
Sep 21 16:07:03 scan Server.js[27726]:     at new Promise (<anonymous>)
Sep 21 16:07:03 scan Server.js[27726]:     at Object.spawn (/var/www/scanservjs/server/Process.js:20:18)
Sep 21 16:07:03 scan Server.js[27726]:     at Function.createPreview (/var/www/scanservjs/server/Api.js:57:19)
Sep 21 16:07:03 scan Server.js[27726]:     at \<anonymous\>
Sep 21 16:07:03 scan Server.js[27726]:     at process._tickCallback (internal/process/next_tick.js:188:7)

Thanks

**Comment by sbs20** [comment]
Hi. are you able to see any other debug info in the logs? E.g. something like:

```
[2020-09-21T14:59:27.358Z] DEBUG (Process): /usr/bin/scanimage -d "plustek:libusb:001:003" --mode "Color" --resolution 150 -l 0 -t 0 -x 215 -y 297 --format "tiff" --brightness 0 --contrast 0 undefined false
```

Also, what version of node are you running? `node -v`

**Comment by TheRealHypR** [comment]
Thanks for your fast response.
Yes I have a line like this with undefined false at the end.

My node version is 8.16.2

**Comment by sbs20** [comment]
I have a feeling, but don't know, that this is something to do with how node 8 handles commands with arguments. I've been using node 12 and haven't had the chance to go back to using node 8 or 10 for testing.

Are you able to upgrade node easily? Or use the docker image?

If not, I will try and setup an image to test with older node but it might take me a while.

**Comment by sbs20** [comment]
> This is from journalctl:
[2020-09-21T14:07:03.179Z] ERROR (global): TypeError: Incorrect value of args option
Sep 21 16:07:03 scan Server.js[27726]: at normalizeSpawnArguments (child_process.js:389:11)

corresponds to [this in v8](https://github.com/nodejs/node/blob/f85ec19b4621c8d88b2a5d671502d70c3205242a/lib/child_process.js#L395) but no longer happens [in v10+](https://github.com/nodejs/node/blob/d0659608160dbf61e8a85f66afc66c3a6ef085b7/lib/child_process.js#L419)

Fix is to change `null` argument to `[]`
