### ISSUE TITLE
Incorrect device parsing where geometry includes steps

### ISSUE THREAD

**Issue by cyablo** [sbs20/scanservjs#69]
SInce I updated my sbs20/scanservjs:latest docker image to 2.0.2, scanservjs stopped working. Neither preview nor scan works. Error message:

> /usr/bin/scanimage -d "net:192.168.1.4:xerox_mfp:libusb:001:003" --mode "color" --resolution 100 -l nan -t nan -x nan -y nan --format "tiff" > ./data/preview/preview.tif exited with code: 4, stderr: scanimage: rounded value of tl-x from -32768 to -32768 scanimage: rounded value of tl-y from -32768 to -32768 scanimage: rounded value of br-x from -32768 to -32768 scanimage: rounded value of br-y from -32768 to -32768 scanimage: sane_start: invalid argument

Saned is running on an OpenWRT 19.07.3 router, to which my Samsung SCX3200 MFP is connected to.

**Comment by sbs20** [comment]
Hi. Could you run `scanimage -A > tmp.txt` and upload the result please?

**Comment by cyablo** [comment]
Sure:

> All options specific to device `net:192.168.1.4:xerox_mfp:libusb:001:003':
>   Standard:
>     --resolution 75|100|150|200|300|600|1200dpi [150]
>         Sets the resolution of the scanned image.
>     --mode Lineart|Halftone|Gray|Color [Color]
>         Selects the scan mode (e.g., lineart, monochrome, or color).
>     --highlight 30..70% (in steps of 10) [inactive]
>         Select minimum-brightness to get a white point
>     --source Flatbed|ADF|Auto [Flatbed]
>         Selects the scan source (such as a document-feeder).
>   Geometry:
>     -l 0..215.9mm (in steps of 1) [0]
>         Top-left x position of scan area.
>     -t 0..297.18mm (in steps of 1) [0]
>         Top-left y position of scan area.
>     -x 0..215.9mm (in steps of 1) [215.9]
>         Width of scan-area.
>     -y 0..297.18mm (in steps of 1) [297.18]
>         Height of scan-area.

**Comment by sbs20** [comment]
Thank you. I don't suppose you could upload it as a file could you? I just want to preserve all the formatting. I'll investigate and get a fix in ASAP.

**Comment by cyablo** [comment]
absolutely no problem:

[out.txt](https://github.com/sbs20/scanservjs/files/5257856/out.txt)

**Comment by sbs20** [comment]
Perfect. I've reproduced the problem, thank you.

**Comment by sbs20** [comment]
This should be resolved in `sbs20/scanservjs:staging`

**Comment by cyablo** [comment]
I'm not at home but preview and scan seems to work now (there is nothing inside the scanner so preview and scan is white). Will try later...

**Comment by cyablo** [comment]
Sorry for the late reply: works now, THX!
