### ISSUE TITLE
Apache2 Reverse Proxy no longer working - 404 when accessing /Assets

### ISSUE THREAD

**Issue by skooj** [sbs20/scanservjs#690]
**Describe the bug**
I am, and have been, using an Apache2 reverse proxy to access this, following the configuration in the documentation. This worked fine prior to updating to 3.0.2, but now I'm getting a white screen. The app loads as expected when connecting to the port directly.

In dev tools, I am getting the errors: 
```
GET http://XXX.XXX/assets/index-133c69ed.js net::ERR_ABORTED 404 (Not Found)
GET http://XXX.XXX/assets/index-3117738e.css net::ERR_ABORTED 404 (Not Found)
```

This indicates that /assets/ is not being put behind /scanner/assets as expected. I believe this is a similar issue to #250 which looks  like it was maybe fixed with #266 

**To Reproduce**
1. install scanservJs (via docker, in my case).
2. setup apache2 reverse proxy following directions [here](https://github.com/sbs20/scanservjs/blob/master/docs/13-proxy.md).
3. access ScanservJs from <host>/scanner/
4. open dev tools and refresh
5. check console for errors

**Expected behavior**
/assets/ would be proxied like everything else.

**Client (please complete the following information):**
 - Chrome

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Docker version 24.0.6

**Logs**
```
GET http://XXX.XXX/assets/index-133c69ed.js net::ERR_ABORTED 404 (Not Found)
GET http://XXX.XXX/assets/index-3117738e.css net::ERR_ABORTED 404 (Not Found)
```
 

**Additional context**
**My apache config:**
```
<Location /scanner/>
        ProxyPass "http://0.0.0.0:8088/"
        ProxyPassReverse "http://0.0.0.0:8088/"
</Location>
```

I have docker forwarding the port 8088 to 8080 instead, because I use 8080 for other things. I have temporarily moved it to 8080 (and updated the config) to see if this fixed the issue, but it did not.  Again, this was functioning in the 2.x version, but not since updating to 3.x

**Edit:**
adding the following inside <Location> allows it to work, but is likely not what is expected by the project:
```
AddOutputFilterByType SUBSTITUTE text/html
Substitute "s|assets/|scanner/assets/|ni"
```

**Comment by sbs20** [comment]
Thanks for finding, reporting and the workaround.

I'll have a patch soon

**Comment by sbs20** [comment]
I'm holding off doing another proper release just yet, though I'm sure there will be one within a week or so.

GitHub should build a new staging image for docker tonight which should resolve this.

**Comment by skooj** [comment]
Thank you for the quick fix!
