### ISSUE TITLE
/usr/share must not be touched at runtime

### ISSUE THREAD

**Issue by chayleaf** [sbs20/scanservjs#695]
**Describe the bug**
/usr/share is only for the package's bundled data that has to be shipped with it and doesn't change at runtime. /usr may well be immutable on *many* systems. /var should be used for persistent runtime data. I also recommend making preview/default.jpg fall back to the package's file, so it doesn't have to be in /var.

**Expected behavior**
Only /var being used for storing outputs

**Comment by sbs20** [comment]
Thanks for this. I am going to change this to `/var/lib/scanservjs` - is that compliant? I've struggled with interpreting the FHS and reconciling it with what other apps do.

**Comment by chayleaf** [comment]
yes, you may also use systemd's StateDirectory for this

**Comment by sbs20** [comment]
Config is loaded here: https://github.com/sbs20/scanservjs/blob/f4b8bda4327e81e2c7d3f5b6fae578a9e57ab93d/app-server/src/application.js#L29

**Comment by chayleaf** [comment]
> Config is loaded here:
> 
> https://github.com/sbs20/scanservjs/blob/f4b8bda4327e81e2c7d3f5b6fae578a9e57ab93d/app-server/src/application.js#L29

Yes, and I see no references to /etc here

**Comment by chayleaf** [comment]
@sbs20 also, the app should work with empty /var - anything else makes packaging extremely annoying. I.e. the package shouldn't put any files to /var, though it may create an empty directory there.
