### ISSUE TITLE
ls not found

### ISSUE THREAD

**Issue by JnCrMx** [sbs20/scanservjs#77]
**Describe the bug**
Conversion to ``PDF (JPG)`` fails with
```Error: convert @- -quality 92 tmp-%d.jpg && ls tmp-*.jpg exited with code: 127, stderr: /bin/sh: 1: ls: not found```.

**To Reproduce**
1. Install the program without docker.
2. Select ``PDF (JPG)`` as format.
3. Scan something.

**Expected behavior**
``ls`` is found and executed properly.

**Server**
 - OS: Raspbian GNU/Linux 10 (buster) aarch64 
 - Node version v14.11.0
 - NPM version 6.14.8
 - Docker version N/A
 - dash version 0.5.10.2-5
- *``/bin``, ``/sbin``, ``/usr/bin``, etc. are different directories. This might not be the case for every system. Some distributions/setups have only one ``bin`` directory and use links for all other directories.*

**Cause**
This is caused by ``/bin`` not being in ``$PATH``.
``scanservjs.service`` sets ``PATH=/usr/bin:/usr/local/bin`` (https://github.com/sbs20/scanservjs/blob/staging/scanservjs.service#L10).
It seems like there is no reason for this, as it cannot be used for security limitations or anything like that anyway.

**Fixes**
Append ``:/bin`` to ``scanservjs.service`` line 10.
Alternatively replace all occurences of ``ls`` with its absolute path (``/bin/ls``) in ``config/config.js``.

**Comment by sbs20** [comment]
Thank you! Should be fixed now.
