### ISSUE TITLE
Scanservjs server not accessible after shutdown or reboot

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#82]
Hi,

After a shutdown (or reboot) of my raspberry, scanservjs server is not started.
I have to install scanservjs a new time.

After a shutdown of the raspberry : 
<pre><font color="#8AE234"><b>pi@SPRINT</b></font>:<font color="#729FCF"><b>~ $</b></font> wget -O - http://localhost:8080
--2020-10-03 17:57:05--  http://localhost:8080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8080... failed: Connection refused.</pre>

**Version scanservjs :** V2.0.3

**OS :** 
<pre><font color="#8AE234"><b>pi@SPRINT</b></font>:<font color="#729FCF"><b>~ $</b></font> cat /etc/os-release
PRETTY_NAME=&quot;Raspbian GNU/Linux 10 (buster)&quot;
NAME=&quot;Raspbian GNU/Linux&quot;
VERSION_ID=&quot;10&quot;
VERSION=&quot;10 (buster)&quot;
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
</pre>

**Comment by sbs20** [comment]
Hi. Try running

```console
sudo systemctl enable scanservjs
```

This enables start on boot. I need to add this to the install script. 

To start it just for the current session you can...

```console
sudo systemctl start scanservjs
```
