### ISSUE TITLE
Request : option output Print cups

### ISSUE THREAD

**Issue by GG700** [sbs20/scanservjs#91]
Hi,

Is that possible to create an option to print the document scanned in a printer ?
The printer can be by exemple included in a server like cups.

Thanks !

**Comment by sbs20** [comment]
I'll have a think. I'm not keen to start adding UI functionality for printing as it will add a whole lot of work that I'm not sure I can take on. However, it may be possible to add a new pipeline option to send the file using `lpr` or something. I'll leave the issue here for now.

**Comment by GG700** [comment]
HI,

I made a test : I modified a pipeline option to send the file using lp.
It works fine.
But before the install of scanservjs, we have to configure the print server...

<pre>  {
    extension: <font color="#AD7FA8"><b>&apos;pdf&apos;</b></font>,
    description: <font color="#AD7FA8"><b>&apos;IMPRESSION &amp; PDF&apos;</b></font>,
    commands: [
      <font color="#AD7FA8"><b>&apos;convert @- -quality 92 tmp-%04d.jpg &amp;&amp; ls tmp-*.jpg&apos;</b></font>,
      <font color="#729FCF"><b>/*&apos;ls toto*.*&apos;,*/</b></font>
      <font color="#AD7FA8"><b>&apos;cp /var/www/scanservjs/data/temp/tmp-0000.jpg /var/www/scanservjs/data/p</b></font>$
      <font color="#AD7FA8"><b>&apos;ls scan-*.*&apos;</b></font>
    ]
  },
</pre>

**Comment by sbs20** [comment]
I've decided I'm not going to proceed with this issue. It just broadens the scope of the app too much at this time. I have made pipeline injection a bit easier though - so you can add your own in `./config/config.local.js`.

**Comment by GG700** [comment]
Thank you for allowing me an easier integration of a new pipeline. I will study the procedure when I have more time. I realize that it takes a lot of time to add this issue.

**Comment by sbs20** [comment]
No problem. Sorry I couldn't do more. It's possible from now - v2.5.0
