### ISSUE TITLE
Ignore `auto|` on device parsing (fixes Pixma device issues)

### ISSUE THREAD

**Issue by tuxBurner** [sbs20/scanservjs#92]
**Describe the bug**
When i try to start scanning with my pixma mx 395 device i get for the -l -t -x -y NAN

/usr/bin/scanimage -d 'pixma:04A91766_004AE4' --mode 'Color' --resolution 100 -l NaN -t NaN -x NaN -y NaN --format 'tiff' --source 'Flatbed' > ./data/temp/~tmp-scan-0001.tif
 

**To Reproduce**
1. Start scanserv-js (v2.1.0) in docker
2. Click on 'scan'
3. Scanner starts making noises
4. Scanner stops after 2 seconds

**Expected behavior**
Scanner should scan the page.

**Client (please complete the following information):**
 - Browser chrome and firefox
 - Version [docker:latest]

**Server (please complete the following information):**
 - OS: Ubuntu
 - Node version [the one in docker]
 - NPM version [the one in docker]
 - Docker version [Docker version 19.03.8, build afacb8b7f0]

**Comment by Mayo42** [comment]
Exactly the same issue here. Also using scanservjs 2.1.0 in docker and also using pixma backend.

**Comment by sbs20** [comment]
Thanks for the reminder. A new image should be built (or building) now.
