### ISSUE TITLE
Saved brightness and contrast not respected

### ISSUE THREAD

**Issue by oujesky** [sbs20/scanservjs#96]
**Describe the bug**
Any setting of brightness or contrast is lost after page refresh in UI

**To Reproduce**
1. Set brightness/contrast
2. Refresh the page

**Expected behavior**
Brightness/contrast value loaded from localStorage

It seems that although value for brightness and contrast are saved into localStorage, when loaded back in `readRequest()` method in Scanserv.vue, it's always set to 0:

```
    ...
     if ('--brightness' in device.features) {
        request.params.brightness = 0;
      }
      if ('--contrast' in device.features) {
        request.params.contrast = 0;
      }
    ...
```

There are two things that seems to be problematic:

1. the values are overwritten even when stored `request` value is retrieved from localStorage 
2. the values are set to 0, even though `device.features['--brightness'].default` and `device.features['--contrast'].default` respectively could be used

**Comment by sbs20** [comment]
Thanks for taking the time to file this.
