### ISSUE TITLE
Convert: cache resources exhausted on large images

### ISSUE THREAD

**Issue by mildfuzz** [sbs20/scanservjs#97]
Device:
```
device `genesys:libusb:001:017' is a Canon LiDE 120 flatbed scanner
```

I am able to successfully run a preview, but when I run a scan, the scanner seems to be scanning, then just when it sounds like it is finished I get:

```
ERROR (Http): Error: convert @- -quality 92 scan-%04d.jpg exited with code: 1, stderr: convert-im6.q16: cache resources exhausted `~tmp-scan-0001.tif' @ error/cache.c/OpenPixelCache/4083.

convert-im6.q16: no images defined `scan-%04d.jpg' @ error/convert.c/ConvertImageCommand/3258.
    at ChildProcess.<anonymous> (/app/server/process.js:44:18)
    at ChildProcess.emit (node:events:327:20)
    at maybeClose (node:internal/child_process:1048:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
```

**Comment by sbs20** [comment]
Are you able to supply a bit more info regarding your setup, as per the issue template?

It looks as if imagemagick is running into resource constraints. I can't reproduce yet but maybe this will provide some useful ideas : https://github.com/ImageMagick/ImageMagick/issues/396

**Comment by mildfuzz** [comment]
So it turns out that it was freaking out when asked to scan more that 600dpi. Not sure if it qualifies as a valid issue?

**Comment by sbs20** [comment]
That makes sense. I'll leave this open for now to see if I can reproduce and find an easy fix.
