### ISSUE TITLE
Rename error when output folder is on a different mountpoint

### ISSUE THREAD

**Issue by franga2000** [sbs20/scanservjs#99]
**Describe the bug**
If the output folder (`/app/data/output/` in the Docker container) is on different mountpoint than the temporary folder, the rename operation after saving a file fails and the file is lost.

**To Reproduce**
1. Have some kind of external filesystem mounted (let's say a drive array at `/media/Documents`)
2. Set up Docker to mount that location into the container (`-v /media/Documents/Scan/:/app/data/output/`)
3. Run a scan (tested with manual batch PDF+OCR, but probably other types too)

**Log**
```
[2020-12-02T22:23:30.862Z] ERROR (Http): [Error: EXDEV: cross-device link not permitted, rename './data/temp/scan-0001.pdf' -> './data/output/scan_2020-12-02 22.23.30.pdf'] {
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: './data/temp/scan-0001.pdf',
  dest: './data/output/scan_2020-12-02 22.23.30.pdf'
}
```

**Additional context**
The problem comes from the `fs.rename` call below. The rename syscall on Linux isn't able to rename files across mountpoint boundaries (which, in fairness, does makes sense).
https://github.com/sbs20/scanservjs/blob/63788587586a080e538ccba262308ee0e3c3b0ab/server/file-info.js#L71

The usual solution is to try renaming and if that fails, do a proper move operation.  
This is conveniently packaged up in the [mv package](https://www.npmjs.com/package/mv) on NPM.

I recommend adding that package (seems like a pretty safe dependency) and replacing the above `fs.rename` call with `mv`. If that sounds good, I can send a PR this weekend.

**Comment by sbs20** [comment]
Thanks for finding, reporting and offering to fix. Yes, that would be awesome, thank you!

When you raise a PR could you do it against the development branch please?
